/-
The finite-support obstruction to an asymmetric varying-offspring theorem
based only on equality of shifted arity semigroups.

The laws `nuFour = δ₄` and `nuFourSeven = Unif{4,7}` have the same
shifted-support semigroup: both are generated by `3`.  Their renewal-depth
semigroups for the binary encoding are nevertheless different.  A counter
`4` returns to a fresh state only after two binary levels, whereas a counter
`7` can return after two or three levels.  Hence the second law has a
fresh-to-fresh return at odd depth and the first does not.

The companion paper amplifies this odd-depth defect along a selected fresh
spine.  At each attempt its conditional probability is at least `p/2`,
where `p` is the mass of an incompatible label.  The final lemma certifies
that the resulting avoidance bound `(1-p/2)^n` tends to zero.
-/
import GraphMarkovMatching.Grammar.Depths
import GraphMarkovMatching.Closure.Examples
import Mathlib.Probability.Distributions.Uniform

namespace GraphMarkovMatching

open scoped ENNReal Classical

/-- The deterministic offspring law supported at arity four. -/
noncomputable def nuFour : PMF ℕ := PMF.pure 4

/-- The uniform offspring law supported at arities four and seven. -/
noncomputable def nuFourSeven : PMF ℕ :=
  (PMF.uniformOfFintype Bool).map (fun b => if b then 7 else 4)

lemma nuFour_support : nuFour.support = ({4} : Set ℕ) := by
  simp [nuFour]

lemma nuFourSeven_support : nuFourSeven.support = ({4, 7} : Set ℕ) := by
  rw [nuFourSeven, PMF.support_map]
  have hu : (PMF.uniformOfFintype Bool).support = Set.univ := by
    simp
  rw [hu]
  ext n
  simp only [Set.mem_image, Set.mem_univ, Set.mem_insert_iff,
    Set.mem_singleton_iff]
  constructor
  · rintro ⟨b, _, rfl⟩
    cases b <;> simp
  · intro h
    rcases h with rfl | rfl
    · exact ⟨false, by simp⟩
    · exact ⟨true, by simp⟩

private lemma closure_three_eq_three_six :
    AddSubmonoid.closure ({3} : Set ℕ) =
      AddSubmonoid.closure ({3, 6} : Set ℕ) := by
  apply le_antisymm
  · exact AddSubmonoid.closure_mono (by simp)
  · apply AddSubmonoid.closure_le.mpr
    intro n hn
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hn
    rcases hn with rfl | rfl
    · exact AddSubmonoid.subset_closure (by simp)
    · have h3 : 3 ∈ AddSubmonoid.closure ({3} : Set ℕ) :=
        AddSubmonoid.subset_closure (by simp)
      simpa using (AddSubmonoid.add_mem _ h3 h3)

/-- The two different finite offspring laws satisfy exactly the shifted
semigroup hypothesis proposed for the asymmetric theorem. -/
theorem shiftedSupportSemigroup_nuFour_eq_nuFourSeven :
    shiftedSupportSemigroup nuFour = shiftedSupportSemigroup nuFourSeven := by
  rw [shiftedSupportSemigroup, shiftedSupportSemigroup,
    nuFour_support, nuFourSeven_support]
  rw [show (fun k : ℕ => k - 1) '' ({4} : Set ℕ) = {3} by
      ext n; simp]
  rw [show (fun k : ℕ => k - 1) '' ({4, 7} : Set ℕ) = {3, 6} by
      ext n; simp; omega]
  exact closure_three_eq_three_six

/-- The fresh-return depths of counter four. -/
lemma toFresh_four : toFresh 4 = {2} := by
  rw [toFresh_of_ge (by omega)]
  norm_num
  simp [toFresh_le_two]

/-- Counter seven has an additional odd fresh-return depth. -/
lemma toFresh_seven : toFresh 7 = {2, 3} := by
  rw [toFresh_of_ge (by omega)]
  norm_num
  rw [toFresh_three, toFresh_four]
  decide

lemma depthSet_four : depthSet {4} = {2} := by
  ext d
  simp [depthSet, toFresh_four]

lemma depthSet_four_seven : depthSet {4, 7} = {2, 3} := by
  ext d
  simp [depthSet, toFresh_four, toFresh_seven]

private lemma three_not_mem_closure_two :
    3 ∉ AddSubmonoid.closure ({2} : Set ℕ) := by
  intro h
  have hdvd := Nat.setGcd_dvd_of_mem_closure h
  have hsetGcd : Nat.setGcd ({2} : Set ℕ) = 2 := by
    rw [show ({2} : Set ℕ) = (({2} : Finset ℕ) : Set ℕ) by
      ext n; simp, setGcd_coe_finset]
    norm_num
  rw [hsetGcd] at hdvd
  omega

/-- Equality of shifted arity semigroups does not imply equality of the
renewal-depth semigroups actually used by the binary matching grammar. -/
theorem renewalDepthSemigroup_nuFour_ne_nuFourSeven :
    AddSubmonoid.closure ((depthSet {4} : Finset ℕ) : Set ℕ) ≠
      AddSubmonoid.closure ((depthSet {4, 7} : Finset ℕ) : Set ℕ) := by
  intro h
  have hright : 3 ∈ AddSubmonoid.closure
      ((depthSet {4, 7} : Finset ℕ) : Set ℕ) := by
    apply AddSubmonoid.subset_closure
    rw [depthSet_four_seven]
    simp
  have hleft : 3 ∈ AddSubmonoid.closure
      ((depthSet {4} : Finset ℕ) : Set ℕ) := by
    rw [h]
    exact hright
  apply three_not_mem_closure_two
  rw [depthSet_four] at hleft
  simpa only [Finset.coe_singleton] using hleft

/-- There is no odd-depth fresh-to-fresh descent under support `{4}`. -/
theorem no_fresh_return_three_nuFour :
    ¬ Descend {4} 3 Tgt.F Tgt.F := by
  intro h
  have hm := descend_FF_closure h
  rw [depthSet_four] at hm
  apply three_not_mem_closure_two
  simpa only [Finset.coe_singleton] using hm

/-- The support `{4,7}` does admit a three-level fresh-to-fresh descent. -/
theorem fresh_return_three_nuFourSeven :
    Descend {4, 7} 3 Tgt.F Tgt.F := by
  apply descend_closure
  apply AddSubmonoid.subset_closure
  rw [depthSet_four_seven]
  simp

/-- The selected-spine avoidance bound used in the counterexample tends
to zero for every positive incompatible-label mass `p ≤ 1`. -/
lemma geometric_avoidance_tendsto_zero {p : ℝ} (hp0 : 0 < p) (hp1 : p ≤ 1) :
    Filter.Tendsto (fun n : ℕ => (1 - p / 2) ^ n) Filter.atTop (nhds 0) := by
  apply tendsto_pow_atTop_nhds_zero_of_lt_one
  · linarith
  · linarith

/-! ### The discarded unweighted scalar closure

The concrete two-law product estimate for raw failure has two child terms.
Putting those terms into the same scalar supremum gives a next-step envelope
of the form `Θ + 2 * M`.  Such an envelope must never again be presented as a
small positive invariant: the following theorem shows that its finite closure
condition forces the budget to vanish.  The useful potential and screen rows
are retained in the two-law ledger files, but structural zero mass must be
carried by a separate coefficient-weighted debt coordinate.
-/

/-- A finite fixed budget cannot absorb the unweighted two-child raw-failure
term.  This is the formal no-go certificate for the deleted two-law scalar
closure. -/
theorem unweighted_twoLaw_closure_forces_zero {Θ M : ℝ≥0∞}
    (hM : M ≠ ∞) (hclose : Θ + 2 * M ≤ M) : M = 0 := by
  have h2M : 2 * M ≤ M := (le_add_left le_rfl).trans hclose
  have h2top : 2 * M ≠ ∞ := ENNReal.mul_ne_top (by norm_num) hM
  have hr : (2 * M).toReal ≤ M.toReal :=
    (ENNReal.toReal_le_toReal h2top hM).2 h2M
  rw [ENNReal.toReal_mul] at hr
  norm_num at hr
  have hnonneg : 0 ≤ M.toReal := ENNReal.toReal_nonneg
  have hz : M.toReal = 0 := by linarith
  exact ((ENNReal.toReal_eq_zero_iff M).mp hz).resolve_right hM

end GraphMarkovMatching
