/-
The renewal-depth combinatorics of the varying-offspring process
(`arbitrary_offspring_matching.tex`, `def:renewal` and
`thm:semigroup`): the return lengths from an exposed counter to the
next fresh state along descendant rays of the kernel, their finiteness
and bounds, and the numerical-semigroup input of the nilpotence
theorem, imported from mathlib.

* `toFresh k`: the finite set of distances from a vertex with counter
  `k` to the next fresh state below it, following the kernel: counters
  `k ≤ 2` emit two fresh children, `k = 3` emits the forced counter
  `2` and one fresh child, `k ≥ 4` forces the split `(k/2, k - k/2)`;
* `toFresh_nonempty`, `one_le_of_mem_toFresh`, `le_of_mem_toFresh`:
  every counter reaches a fresh state, in at least one and at most
  `k + 1` steps;
* `sq_le_eight_mul_succ_of_mem_toFresh`: the quantitative cascade
  estimate `d^2 \le 8(k+1)`, used by the exponential-tail ledger;
* `depthSet S`: the return lengths `𝒟_ν` of a support `S`;
* `setGcd_coe_finset`: the mathlib set-gcd of a finite set is its
  finset gcd;
* `depths_semigroup`: every sufficiently large multiple of
  `gcd 𝒟_ν` is a sum of return lengths (`thm:semigroup`, from
  `Nat.exists_mem_closure_of_ge`);
* `shiftedSupportSemigroup`: the additive semigroup generated by the
  shifted charged arities `k - 1` of an offspring law, finitely
  generated by `Nat.addSubmonoid_fg` (`shiftedSupportSemigroup_fg`).
-/
import Mathlib.NumberTheory.FrobeniusNumber
import Mathlib.Probability.ProbabilityMassFunction.Basic

namespace GraphMarkovMatching

/-- The return lengths from an exposed counter `k`: the distances to
the next fresh state along descendant rays of the varying-offspring
kernel. -/
def toFresh : ℕ → Finset ℕ
  | 0 => {1}
  | 1 => {1}
  | 2 => {1}
  | 3 => insert 1 ((toFresh 2).image (· + 1))
  | k + 4 => ((toFresh ((k + 4) / 2)).image (· + 1))
      ∪ ((toFresh (k + 4 - (k + 4) / 2)).image (· + 1))
decreasing_by all_goals omega

/-- Small counters reach a fresh state in one step. -/
lemma toFresh_le_two {k : ℕ} (hk : k ≤ 2) : toFresh k = {1} := by
  match k, hk with
  | 0, _ => simp [toFresh]
  | 1, _ => simp [toFresh]
  | 2, _ => simp [toFresh]

/-- The ternary counter reaches a fresh state in one or two steps. -/
lemma toFresh_three : toFresh 3 = {1, 2} := by
  rw [show toFresh 3 = insert 1 ((toFresh 2).image (· + 1)) from by
      simp [toFresh],
    toFresh_le_two (by omega), Finset.image_singleton]

/-- The forced-split recursion for large counters. -/
lemma toFresh_of_ge {k : ℕ} (hk : 4 ≤ k) :
    toFresh k = ((toFresh (k / 2)).image (· + 1))
      ∪ ((toFresh (k - k / 2)).image (· + 1)) := by
  obtain ⟨m, rfl⟩ : ∃ m, k = m + 4 := ⟨k - 4, by omega⟩
  rw [toFresh]

/-- Every counter reaches a fresh state. -/
lemma toFresh_nonempty : ∀ k, (toFresh k).Nonempty := by
  intro k
  induction k using Nat.strong_induction_on with
  | _ k ih =>
    by_cases h2 : k ≤ 2
    · rw [toFresh_le_two h2]
      exact ⟨1, Finset.mem_singleton_self 1⟩
    · by_cases h3 : k = 3
      · subst h3
        rw [toFresh_three]
        exact ⟨1, by simp⟩
      · have h4 : 4 ≤ k := by omega
        obtain ⟨d, hd⟩ := ih (k / 2) (by omega)
        rw [toFresh_of_ge h4]
        exact ⟨d + 1,
          Finset.mem_union_left _ (Finset.mem_image_of_mem _ hd)⟩

/-- Return lengths are positive. -/
lemma one_le_of_mem_toFresh : ∀ k, ∀ d ∈ toFresh k, 1 ≤ d := by
  intro k
  induction k using Nat.strong_induction_on with
  | _ k ih =>
    intro d hd
    by_cases h2 : k ≤ 2
    · rw [toFresh_le_two h2] at hd
      simp at hd
      omega
    · by_cases h3 : k = 3
      · subst h3
        rw [toFresh_three] at hd
        simp at hd
        omega
      · have h4 : 4 ≤ k := by omega
        rw [toFresh_of_ge h4] at hd
        rcases Finset.mem_union.mp hd with h | h <;>
          · obtain ⟨e, _, rfl⟩ := Finset.mem_image.mp h
            omega

/-- Return lengths are at most `k + 1`. -/
lemma le_of_mem_toFresh : ∀ k, ∀ d ∈ toFresh k, d ≤ k + 1 := by
  intro k
  induction k using Nat.strong_induction_on with
  | _ k ih =>
    intro d hd
    by_cases h2 : k ≤ 2
    · rw [toFresh_le_two h2] at hd
      simp at hd
      omega
    · by_cases h3 : k = 3
      · subst h3
        rw [toFresh_three] at hd
        simp at hd
        omega
      · have h4 : 4 ≤ k := by omega
        rw [toFresh_of_ge h4] at hd
        rcases Finset.mem_union.mp hd with h | h
        · obtain ⟨e, he, rfl⟩ := Finset.mem_image.mp h
          have := ih (k / 2) (by omega) e he
          omega
        · obtain ⟨e, he, rfl⟩ := Finset.mem_image.mp h
          have := ih (k - k / 2) (by omega) e he
          omega

/-- **Quadratic cascade bound.**  A return from counter `k` at depth
`d` satisfies `d² ≤ 8(k+1)`.  The true order is logarithmic, but this
weaker estimate is deliberately used by the exponential-tail proof:
it is elementary to propagate through the two halving branches, and
it already turns an exponential counter tail into Gaussian decay in
the length of a live screen path. -/
lemma sq_le_eight_mul_succ_of_mem_toFresh :
    ∀ k, ∀ d ∈ toFresh k, d * d ≤ 8 * (k + 1) := by
  intro k
  induction k using Nat.strong_induction_on with
  | _ k ih =>
    intro d hd
    by_cases h2 : k ≤ 2
    · rw [toFresh_le_two h2] at hd
      have : d = 1 := Finset.mem_singleton.mp hd
      subst d
      omega
    · by_cases h3 : k = 3
      · subst h3
        rw [toFresh_three] at hd
        simp only [Finset.mem_insert, Finset.mem_singleton] at hd
        rcases hd with rfl | rfl <;> norm_num
      · have h4 : 4 ≤ k := by omega
        rw [toFresh_of_ge h4] at hd
        rcases Finset.mem_union.mp hd with hd | hd
        · obtain ⟨e, he, rfl⟩ := Finset.mem_image.mp hd
          have hsquare := ih (k / 2) (by omega) e he
          have hlinear := le_of_mem_toFresh (k / 2) e he
          have hhalf : 2 * (k / 2) ≤ k := Nat.mul_div_le k 2
          nlinarith
        · obtain ⟨e, he, rfl⟩ := Finset.mem_image.mp hd
          have hsquare := ih (k - k / 2) (by omega) e he
          have hlinear := le_of_mem_toFresh (k - k / 2) e he
          have hhalf : 2 * (k - k / 2) ≤ k + 1 := by omega
          nlinarith

/-- The return lengths `𝒟_ν` of a support `S`. -/
def depthSet (S : Finset ℕ) : Finset ℕ := S.biUnion toFresh

/-- A nonempty support has a return length. -/
lemma depthSet_nonempty {S : Finset ℕ} (hS : S.Nonempty) :
    (depthSet S).Nonempty := by
  obtain ⟨k, hk⟩ := hS
  obtain ⟨d, hd⟩ := toFresh_nonempty k
  exact ⟨d, Finset.mem_biUnion.mpr ⟨k, hk, hd⟩⟩

/-- Return lengths of a bounded support are bounded. -/
lemma depthSet_le {S : Finset ℕ} {N : ℕ} (hS : ∀ k ∈ S, k ≤ N) :
    ∀ d ∈ depthSet S, d ≤ N + 1 := by
  intro d hd
  obtain ⟨k, hk, hdk⟩ := Finset.mem_biUnion.mp hd
  have h1 := le_of_mem_toFresh k d hdk
  have h2 := hS k hk
  omega

/-- The mathlib set-gcd of a finite set is its finset gcd. -/
lemma setGcd_coe_finset (D : Finset ℕ) :
    Nat.setGcd (D : Set ℕ) = D.gcd id := by
  refine Nat.dvd_antisymm ?_ ?_
  · exact Finset.dvd_gcd fun i hi => Nat.setGcd_dvd_of_mem hi
  · exact Nat.dvd_setGcd_iff.mpr fun m hm => Finset.gcd_dvd hm

/-- **The numerical semigroup lemma** (`thm:semigroup`): every
sufficiently large multiple of `gcd 𝒟_ν` is a sum of return
lengths. -/
theorem depths_semigroup (S : Finset ℕ) :
    ∃ R, ∀ m, R ≤ m → (depthSet S).gcd id ∣ m →
      m ∈ AddSubmonoid.closure ((depthSet S : Set ℕ)) := by
  obtain ⟨R, hR⟩ := Nat.exists_mem_closure_of_ge ((depthSet S : Set ℕ))
  refine ⟨R, fun m hm hdvd => hR m hm ?_⟩
  rw [setGcd_coe_finset]
  exact hdvd

/-! ### The shifted-support semigroup -/

/-- The branching semigroup generated by the shifted charged counters. -/
def shiftedSupportSemigroup (ν : PMF ℕ) : AddSubmonoid ℕ :=
  AddSubmonoid.closure ((fun k : ℕ => k - 1) '' ν.support)

/-- Every additive submonoid of `ℕ` is finitely generated, so the
shifted-support semigroup of every offspring law is. -/
theorem shiftedSupportSemigroup_fg (ν : PMF ℕ) :
    (shiftedSupportSemigroup ν).FG :=
  Nat.addSubmonoid_fg _

end GraphMarkovMatching
