/-
Axiom audit for the live library: every headline theorem of the one-law
development, of the abstract perturbation and ledger layers, and of the tail
and heavy-core layers reports `propext, Classical.choice, Quot.sound` and
nothing else.

The audit of the archived routes lives in `Archive/AxCheck.lean`.
-/
import GraphMarkovMatching.Closure.Main
import GraphMarkovMatching.Closure.Numeric
import GraphMarkovMatching.Closure.Examples
import GraphMarkovMatching.Tail.Block
import GraphMarkovMatching.Closure.RareMatrix
import GraphMarkovMatching.Obstructions.FiniteZipper
import GraphMarkovMatching.Closure.Green
import GraphMarkovMatching.Grammar.Depths
import GraphMarkovMatching.Tail.Combinatorics
import GraphMarkovMatching.Tail.Mixture
import GraphMarkovMatching.Tail.QuenchedObstruction
import GraphMarkovMatching.Obstructions.Semigroup
import GraphMarkovMatching.Obstructions.HeavyCore
import GraphMarkovMatching.Obstructions.ExitLedger
import GraphMarkovMatching.Obstructions.DepthPairing
import GraphMarkovMatching.Tail.Hybrid
import GraphMarkovMatching.Process.Ledger
import GraphMarkovMatching.Delta3.Infinite
#print axioms GraphMarkovMatching.varying_failure_le
#print axioms GraphMarkovMatching.varying_matching_le
#print axioms GraphMarkovMatching.varying_matching_le_traj
#print axioms GraphMarkovMatching.genKcC_le_third
#print axioms GraphMarkovMatching.main_matching_failure_le
#print axioms GraphMarkovMatching.main_matching_le_traj
#print axioms GraphMarkovMatching.delta3_failure_le_of_general
#print axioms GraphMarkovMatching.delta2_failure_le_of_general
#print axioms GraphMarkovMatching.varying_exp3_failure_le
#print axioms GraphMarkovMatching.varying_exp3_matching_le
#print axioms GraphMarkovMatching.varying_doubleExp_failure_le
#print axioms GraphMarkovMatching.varying_doubleExp_matching_le
#print axioms GraphMarkovMatching.varying_failure_uniform
#print axioms GraphMarkovMatching.delta3_failure_le
#print axioms GraphMarkovMatching.delta3Matching_infinite
#print axioms GraphMarkovMatching.delta3Matching_infinite_traj
#print axioms GraphMarkovMatching.varyingMatching_failure_le_closed
#print axioms GraphMarkovMatching.varying_matching_infinite_closed
#print axioms GraphMarkovMatching.varyingMatching_infinite
#print axioms GraphMarkovMatching.varyingMatching_infinite_traj
#print axioms GraphMarkovMatching.Support.trajLab_map_consLab
#print axioms GraphMarkovMatching.Support.trajPairLab_map_consLab
#print axioms GraphMarkovMatching.genE_step
#print axioms GraphMarkovMatching.genPsi_step
#print axioms GraphMarkovMatching.accN_nilpotent
#print axioms GraphMarkovMatching.accN_acyclic
#print axioms GraphMarkovMatching.hallFactorize
#print axioms GraphMarkovMatching.memInd_branch_iff
#print axioms GraphMarkovMatching.eRowZ_fresh
#print axioms GraphMarkovMatching.eRowF_fresh
#print axioms GraphMarkovMatching.psiRow_FF
#print axioms GraphMarkovMatching.oneSided_charge_le
#print axioms GraphMarkovMatching.interpScreen_base
#print axioms GraphMarkovMatching.WresD_XiBar_le_sum
#print axioms GraphMarkovMatching.screened_uniform_bound_invariant
#print axioms GraphMarkovMatching.screened_uniform_bound_functional
#print axioms GraphMarkovMatching.screened_uniform_bound_resolvent
#print axioms GraphMarkovMatching.rareMatrix_block_contraction
#print axioms GraphMarkovMatching.rareMatrix_resolvent_le
#print axioms GraphMarkovMatching.screened_uniform_bound_rareMatrix
#print axioms GraphMarkovMatching.screened_uniform_bound_invariant_state
#print axioms GraphMarkovMatching.screened_uniform_bound_resolvent_with_debt
#print axioms GraphMarkovMatching.screened_uniform_bound_rareMatrix_with_debt
#print axioms GraphMarkovMatching.weightedLedger_polynomial_closure
#print axioms GraphMarkovMatching.weightedLedger_polynomial_function_closure
#print axioms GraphMarkovMatching.exists_pos_weightedLedger_polynomial_smallness
#print axioms GraphMarkovMatching.dominated_block_contraction
#print axioms GraphMarkovMatching.dominated_resolvent_le
#print axioms GraphMarkovMatching.screened_uniform_bound_dominated
#print axioms GraphMarkovMatching.graft_geometric_denominator_le_two
#print axioms GraphMarkovMatching.rareMatrix_resolvent_le_graftGreen
#print axioms GraphMarkovMatching.graftWeightedLedger_estimate
#print axioms GraphMarkovMatching.FiniteZipper.liveKernel_sum_add_killedMass
#print axioms GraphMarkovMatching.FiniteZipper.liveKernel_row_sum_le_one_sub
#print axioms GraphMarkovMatching.FiniteZipper.retainedMass_eq_one_of_all
#print axioms GraphMarkovMatching.FiniteZipper.exists_uniform_positive_kill
#print axioms GraphMarkovMatching.FiniteZipper.normalizedScreenKernel_eq_screenKernel_of_all
#print axioms GraphMarkovMatching.FiniteZipper.integratedLabelTilt_le
#print axioms GraphMarkovMatching.FiniteZipper.integrated_screenKernel_le
#print axioms GraphMarkovMatching.FiniteZipper.screenKernel_resolvent_le
#print axioms GraphMarkovMatching.FiniteZipper.exists_positive_kill_screenKernel_resolvent
#print axioms GraphMarkovMatching.FiniteZipper.screened_uniform_bound_finiteZipper
#print axioms GraphMarkovMatching.screenE_le_failureD_of_mem
#print axioms GraphMarkovMatching.screenE_WresD_le_crossDres_of_mem
#print axioms GraphMarkovMatching.exists_consecutive_mem_toFresh
#print axioms GraphMarkovMatching.depthSet_gcd_eq_one_of_nonpower_mem
#print axioms GraphMarkovMatching.eventually_common_depths_of_nonpower_mem
#print axioms GraphMarkovMatching.exists_finite_renewal_support
#print axioms GraphMarkovMatching.shiftedSupportSemigroup_fg
#print axioms GraphMarkovMatching.sq_le_eight_mul_succ_of_mem_toFresh
#print axioms GraphMarkovMatching.screenE_WresD_le
#print axioms GraphMarkovMatching.PhiDres_bind_eq_tsum_bad_tilt
#print axioms GraphMarkovMatching.exists_screen_prune_sq_le
#print axioms GraphMarkovMatching.counterEnv_bind_quenched
#print axioms GraphMarkovMatching.failureD_Tlaw_eq_quenched
#print axioms GraphMarkovMatching.failureD_le_PhiDres_add_zMass
#print axioms GraphMarkovMatching.PhiDres_qInterp_Z_Z_succ
#print axioms GraphMarkovMatching.PhiDres_qInterp_Z_F_succ
#print axioms GraphMarkovMatching.PhiDres_qInterp_F_Z_succ
#print axioms GraphMarkovMatching.PhiDres_qInterp_F_F_succ
#print axioms GraphMarkovMatching.qFresh_mode_screen_ne_zero
#print axioms GraphMarkovMatching.EventuallyChargesShiftedSemigroup.eventually_succ_ne_zero_iff
#print axioms GraphMarkovMatching.EventuallyChargesShiftedSemigroup.large_Z_cell_prune
#print axioms GraphMarkovMatching.EventuallyChargesShiftedSemigroup.large_Fk_cell_prune
#print axioms GraphMarkovMatching.EventuallyChargesShiftedSemigroup.large_Z_tilt_prune
#print axioms GraphMarkovMatching.EventuallyChargesShiftedSemigroup.large_Fk_tilt_prune
#print axioms GraphMarkovMatching.exists_finite_renewal_support_closure
#print axioms GraphMarkovMatching.screenE_component_to_mix_mem_eq_zero
#print axioms GraphMarkovMatching.screenE_mix_mem_component_WresD_eq_zero
#print axioms GraphMarkovMatching.avg_component_screen_WresD_le_PhiDres
#print axioms GraphMarkovMatching.avg_component_screen_component_WresD_le
#print axioms GraphMarkovMatching.crossDres_self
#print axioms GraphMarkovMatching.crossDres_bind_bad
#print axioms GraphMarkovMatching.crossDres_bind_source
#print axioms GraphMarkovMatching.qE_square_le_straight_sum
#print axioms GraphMarkovMatching.qE_map_branch_law
#print axioms GraphMarkovMatching.WresD_map_branch_law
#print axioms GraphMarkovMatching.crossDres_map_branch_law
#print axioms GraphMarkovMatching.qE_qInterp_F_succ_branch
#print axioms GraphMarkovMatching.WresD_qInterp_F_succ_branch
#print axioms GraphMarkovMatching.crossDres_qInterp_Z_Z_Z_succ
#print axioms GraphMarkovMatching.crossDres_qInterp_Z_Z_F_succ
#print axioms GraphMarkovMatching.crossDres_qInterp_Z_F_Z_succ
#print axioms GraphMarkovMatching.crossDres_qInterp_Z_F_F_succ
#print axioms GraphMarkovMatching.crossDres_square_le_four_moments
#print axioms GraphMarkovMatching.crossDres_square_le
#print axioms GraphMarkovMatching.crossDres_qChildren_le
#print axioms GraphMarkovMatching.regularBadTilt_WresD_le_PhiDres_add
#print axioms GraphMarkovMatching.avg_regular_component_WresD_le_PhiDres
#print axioms GraphMarkovMatching.avg_component_screen_component_WresD_le_PhiDres_pair
#print axioms GraphMarkovMatching.avg_quenchedFresh_screen_le_PhiDres_pair
#print axioms GraphMarkovMatching.crossDres_le_failureD_add_PhiDres
#print axioms GraphMarkovMatching.avg_component_screen_component_WresD_le_crossDres
#print axioms GraphMarkovMatching.avg_quenchedFresh_screen_le_crossDres
#print axioms GraphMarkovMatching.shiftedSupportSemigroup_nuFour_eq_nuFourSeven
#print axioms GraphMarkovMatching.nuFourSeven_four
#print axioms GraphMarkovMatching.nuFourSeven_seven
#print axioms GraphMarkovMatching.renewalDepthSemigroup_nuFour_ne_nuFourSeven
#print axioms GraphMarkovMatching.no_fresh_return_three_nuFour
#print axioms GraphMarkovMatching.fresh_return_three_nuFourSeven
#print axioms GraphMarkovMatching.exp3_two_ne_zero
#print axioms GraphMarkovMatching.zero_two_incompatible
#print axioms GraphMarkovMatching.geometric_avoidance_tendsto_zero
#print axioms GraphMarkovMatching.rareCore_exception_offsets_mem
#print axioms GraphMarkovMatching.heavyCoreIndex_spec
#print axioms GraphMarkovMatching.heavyCoreWeight_rpow_neg_le
#print axioms GraphMarkovMatching.uniform_epsilon_implies_heavy_epsilon
#print axioms GraphMarkovMatching.heavy_block_mass_lower
#print axioms GraphMarkovMatching.rareCoreArity_has_consecutive_returns
#print axioms GraphMarkovMatching.exists_heavy_rare_core_repair
#print axioms GraphMarkovMatching.FiniteZipper.survival_eq_iterate
#print axioms GraphMarkovMatching.FiniteZipper.survival_add_pathMass_le_one
#print axioms GraphMarkovMatching.FiniteZipper.iterate_liveKernel_le_one_sub_of_closingWord
#print axioms GraphMarkovMatching.heavyLagNext_value
#print axioms GraphMarkovMatching.fifoAllocate_coverage
#print axioms GraphMarkovMatching.heavyQueueStep_state
#print axioms GraphMarkovMatching.heavyLag_liveKernel_eq_rareMatrix
#print axioms GraphMarkovMatching.heavyLag_retainedMass_eq_one
#print axioms GraphMarkovMatching.heavyLagCorrection_closes
#print axioms GraphMarkovMatching.heavyLagCorrection_wordValid
#print axioms GraphMarkovMatching.ExitLedger.run_left_coverage
#print axioms GraphMarkovMatching.ExitLedger.run_queueState
#print axioms GraphMarkovMatching.heavyLagCorrection_isHallExitAllocation
#print axioms GraphMarkovMatching.heavyLagCorrection_isCompleteExitAllocation
#print axioms GraphMarkovMatching.q_pow_four_le_heavyLagCorrectionMass
#print axioms GraphMarkovMatching.heavyLag_four_step_killing_min
#print axioms GraphMarkovMatching.heavyCoreLag_four_step_killing
#print axioms GraphMarkovMatching.heavyLag_normalizedScreenKernel_eq_screenKernel
#print axioms GraphMarkovMatching.heavyLag_integrated_screenKernel_le
#print axioms GraphMarkovMatching.heavyLagCommonKernel_not_two_step_nilpotent
#print axioms GraphMarkovMatching.heavyLagCommonKernel_not_nilpotent
#print axioms GraphMarkovMatching.mapBinaryAddress_length
#print axioms GraphMarkovMatching.counterThreeFreshFrontier_depthSet
#print axioms GraphMarkovMatching.counterFiveFreshFrontier_depthSet
#print axioms GraphMarkovMatching.counterThreeFive_fifo_not_autRealizable
#print axioms GraphMarkovMatching.ExitLedger.run_pairs_append
#print axioms GraphMarkovMatching.counterThreeFive_run_not_autRealizable
#print axioms GraphMarkovMatching.unweighted_twoLaw_closure_forces_zero
