/-
Axiom audit for the composite subfolder: the headline statements must
use only `propext`, `Classical.choice`, and `Quot.sound`.
-/
import GraphMarkovMatching.Composite.Grammar
import GraphMarkovMatching.Composite.Anchor
import GraphMarkovMatching.Composite.Rank
import GraphMarkovMatching.Composite.Kernel
import GraphMarkovMatching.Composite.Support
import GraphMarkovMatching.Composite.Tilt
import GraphMarkovMatching.Composite.Endpoint
import GraphMarkovMatching.Composite.Ledger
import GraphMarkovMatching.Composite.CellStep
import GraphMarkovMatching.Composite.Bridge
import GraphMarkovMatching.Composite.ScreenDescent
import GraphMarkovMatching.Composite.Assembly
import GraphMarkovMatching.Composite.Main
import GraphMarkovMatching.Composite.Debt
import GraphMarkovMatching.Composite.Step
import GraphMarkovMatching.Composite.Numeric

#print axioms GraphMarkovMatching.Composite.chartPorts_cases
#print axioms GraphMarkovMatching.Composite.descend_F_iff_mem_sigmaS
#print axioms GraphMarkovMatching.Composite.no_live_common_cycle
#print axioms GraphMarkovMatching.Composite.matApply_iter_eq_zero
#print axioms GraphMarkovMatching.Composite.nilpotent_of_acyclic
#print axioms GraphMarkovMatching.Composite.mul_repZ_le_cZ
#print axioms GraphMarkovMatching.Composite.repXi_le_cXiBar
#print axioms GraphMarkovMatching.Composite.exists_sim_of_muM_ne_zero
#print axioms GraphMarkovMatching.Composite.exists_sim_of_cT_ne_zero
#print axioms GraphMarkovMatching.Composite.fresh_dead_screen_eq_zero
#print axioms GraphMarkovMatching.Composite.mul_simDeg_repXi_le_simDeg_cXiBar
#print axioms GraphMarkovMatching.Composite.stateMap_cXi_exc
#print axioms GraphMarkovMatching.Composite.invTilt_simDeg_cXiBar_le
#print axioms GraphMarkovMatching.Composite.cT_map_restrictLab
#print axioms GraphMarkovMatching.Composite.cMatching_infinite_of_PhiDres
#print axioms GraphMarkovMatching.Composite.no_common_step_cycle
#print axioms GraphMarkovMatching.Composite.ledger_nilpotent
#print axioms GraphMarkovMatching.Composite.screenUniv_card_le
#print axioms GraphMarkovMatching.Composite.cPhiDres_cT_cT_succ
#print axioms GraphMarkovMatching.Composite.WresD_cXiBar_le_sum
#print axioms GraphMarkovMatching.Composite.screenE_muM_mirror_mem
#print axioms GraphMarkovMatching.Composite.cRow_TT
#print axioms GraphMarkovMatching.Composite.cScr_TZ_tiltT
#print axioms GraphMarkovMatching.Composite.cPsi_step
#print axioms GraphMarkovMatching.Composite.cGood_nilpotent
#print axioms GraphMarkovMatching.Composite.cReach_anchored
#print axioms GraphMarkovMatching.Composite.screenDebtBound_holds
#print axioms GraphMarkovMatching.Composite.composite_failure_le_closed
#print axioms GraphMarkovMatching.Composite.composite_matching_le_closed
#print axioms GraphMarkovMatching.Composite.screenLedgerInput_holds
#print axioms GraphMarkovMatching.Composite.composite_failure_le_final
#print axioms GraphMarkovMatching.Composite.composite_matching_le_final
#print axioms GraphMarkovMatching.Composite.composite_failure_bound
#print axioms GraphMarkovMatching.Composite.composite_matching_bound
#print axioms GraphMarkovMatching.Composite.compEtaStar_pos
#print axioms GraphMarkovMatching.Composite.compDomThreshold_pos
#print axioms GraphMarkovMatching.Composite.hdom_of_compEM_le
#print axioms GraphMarkovMatching.Composite.composite_failure_bound_no_exceptions
#print axioms GraphMarkovMatching.Composite.no_live_step_cycle
#print axioms GraphMarkovMatching.Composite.ledger_nilpotentE
#print axioms GraphMarkovMatching.Composite.no_live_step_cycleS
#print axioms GraphMarkovMatching.Composite.ledger_nilpotentES
#print axioms GraphMarkovMatching.Composite.cGoodE_nilpotent
#print axioms GraphMarkovMatching.Composite.cW_nilpotent
#print axioms GraphMarkovMatching.Composite.screenLedgerInputM_holds
#print axioms GraphMarkovMatching.Composite.composite_failure_le_merged
#print axioms GraphMarkovMatching.Composite.composite_matching_le_merged
#print axioms GraphMarkovMatching.Composite.composite_failure_bound_massfree
#print axioms GraphMarkovMatching.Composite.composite_matching_bound_massfree
#print axioms GraphMarkovMatching.Composite.composite_matching_bound_massfree_traj
#print axioms GraphMarkovMatching.Composite.compEtaStarM_pos
#print axioms GraphMarkovMatching.Composite.compKcFinalM_ne_top
#print axioms GraphMarkovMatching.Composite.cLinB_eq
#print axioms GraphMarkovMatching.Composite.compCM_eq
#print axioms GraphMarkovMatching.Composite.compXM_eq
#print axioms GraphMarkovMatching.Composite.compKcFinalM_eq
#print axioms GraphMarkovMatching.Composite.compB2Of_eq
#print axioms GraphMarkovMatching.Composite.compAM_eq
#print axioms GraphMarkovMatching.Composite.compHuCOf_eq
#print axioms GraphMarkovMatching.Composite.compEtaStarM_eq
#print axioms GraphMarkovMatching.Composite.composite_failure_bound_massfree_no_exceptions
#print axioms GraphMarkovMatching.Composite.composite_matching_bound_massfree_no_exceptions
#print axioms GraphMarkovMatching.Composite.composite_matching_bound_massfree_no_exceptions_traj
#print axioms GraphMarkovMatching.Composite.compKcFinalM_mul_le_half
#print axioms GraphMarkovMatching.Composite.cLetterBox_card
#print axioms GraphMarkovMatching.Composite.cRank_eq
#print axioms GraphMarkovMatching.Composite.compEtaStarMT_pos
#print axioms GraphMarkovMatching.Composite.composite_failure_bound_massfree_T
#print axioms GraphMarkovMatching.Composite.composite_matching_bound_massfree_traj_T
