/-
The composite tagged grammar (`arbitrary_offspring_matching.tex`,
`sec:composite`, `def:composite-grammar`): letters, successor sets,
descents, chart ports, and the realization theorem.

This subfolder is the composite two-law development.  Its grammar imports
only `Grammar/Depths` (the certified counter-depth combinatorics `toFresh`,
`depthSet`, `depths_semigroup`) from the one-law grammar.

* `Letter`: fresh `F`, forced `Z j`, exposed `Fk k`, and the pair-indexed
  markers `M a b i` carrying the pending port of the composite chart of
  the declared pair `(a, b)` at stage `i` (`eq:composite-alphabet`);
* `succZ`, `succM`, `succ S E`: the successor sets; only the fresh letter
  has side-dependent successors, through the exceptional entrances
  `succM a b 0` of the pairs in `E`;
* `chartPorts b v`: the port depths of the composite chart below a
  pending vertex of running value `v` (`thm:chart-returns`);
* `chartPorts_cases`: every chart port depth is a return length of `v`
  or a return length of `v` plus one of `b`, the Lean form of
  `thm:chart-returns`;
* `Descend S E t m t'`: admissible `m`-step descents
  (`def:composite-descents`);
* `descend_F_iff_mem_sigmaS`: the realization theorem
  `thm:composite-realise`,
  fresh-to-fresh descent lengths are exactly the additive monoid
  `Σ_S` generated by the common return depths, on either side;
* `meas`, `meas_lt_of_mem_succ`, `exists_descend_F`: the strictly
  decreasing forced-depth measure below any non-fresh letter, giving the
  bounded reach of the fresh letter used by the acyclicity theorem.
-/
import GraphMarkovMatching.Grammar.Depths

namespace GraphMarkovMatching
namespace Composite

/-- Letters of the composite tagged grammar: the fresh letter, the forced
letters, the exposed letters, and the markers of a declared pair `(a, b)`
at stage `i` along the designated path. -/
inductive Letter : Type where
  | F : Letter
  | Z (j : ℕ) : Letter
  | Fk (k : ℕ) : Letter
  | M (a b i : ℕ) : Letter
deriving DecidableEq

/-- The running value of the designated path of the pair `(a, b)` at
stage `i`: the `i`-fold iterated floor halving of `a`. -/
def val (a i : ℕ) : ℕ := a / 2 ^ i

@[simp] lemma val_zero (a : ℕ) : val a 0 = a := by simp [val]

lemma val_succ (a i : ℕ) : val a (i + 1) = val a i / 2 := by
  simp [val, pow_succ, Nat.div_div_eq_div_mul]

/-- Successors of a forced counter `j` under the balanced rule. -/
def succZ : ℕ → Finset Letter
  | 0 => {.F}
  | 1 => {.F}
  | 2 => {.F}
  | 3 => {.Z 2, .F}
  | j + 4 => {.Z ((j + 4) / 2), .Z ((j + 4) - (j + 4) / 2)}

lemma succZ_le_two {j : ℕ} (hj : j ≤ 2) : succZ j = {.F} := by
  match j, hj with
  | 0, _ => rfl
  | 1, _ => rfl
  | 2, _ => rfl

lemma succZ_three : succZ 3 = {.Z 2, .F} := rfl

lemma succZ_of_ge {j : ℕ} (hj : 4 ≤ j) :
    succZ j = {.Z (j / 2), .Z (j - j / 2)} := by
  obtain ⟨m, rfl⟩ : ∃ m, j = m + 4 := ⟨j - 4, by omega⟩
  rfl

/-- Successors of the marker of the pair `(a, b)` at stage `i`
(`def:composite-kernel`, rules (ii) at `i = 0` and (iii) at
`i ≥ 1`): at running value at least `4` the designated child carries the
next marker, at value `3` the port is the right child, at value `2` the
port is the left child. -/
def succM (a b i : ℕ) : Finset Letter :=
  if val a i ≤ 2 then {.Z b, .F}
  else if val a i = 3 then {.Z 2, .Z b}
  else {.M a b (i + 1), .Z (val a i - val a i / 2)}

lemma succM_le_two {a b i : ℕ} (h : val a i ≤ 2) :
    succM a b i = {.Z b, .F} := by
  simp [succM, h]

lemma succM_three {a b i : ℕ} (h : val a i = 3) :
    succM a b i = {.Z 2, .Z b} := by
  simp [succM, h]

lemma succM_of_ge {a b i : ℕ} (h : 4 ≤ val a i) :
    succM a b i = {.M a b (i + 1), .Z (val a i - val a i / 2)} := by
  have h2 : ¬ val a i ≤ 2 := by omega
  have h3 : ¬ val a i = 3 := by omega
  simp [succM, h2, h3]

/-- Letter successors on the side whose common support is `S` and whose
declared exceptional pairs are `E`.  Only the fresh letter sees `E`,
through the exceptional entrances `succM p.1 p.2 0`. -/
def succ (S : Finset ℕ) (E : Finset (ℕ × ℕ)) : Letter → Finset Letter
  | .F => S.biUnion succZ ∪ E.biUnion fun p => succM p.1 p.2 0
  | .Z j => succZ j
  | .Fk k => succZ k
  | .M a b i => succM a b i

@[simp] lemma succ_F (S : Finset ℕ) (E : Finset (ℕ × ℕ)) :
    succ S E .F = S.biUnion succZ ∪ E.biUnion fun p => succM p.1 p.2 0 := rfl

@[simp] lemma succ_Z (S : Finset ℕ) (E : Finset (ℕ × ℕ)) (j : ℕ) :
    succ S E (.Z j) = succZ j := rfl

@[simp] lemma succ_Fk (S : Finset ℕ) (E : Finset (ℕ × ℕ)) (k : ℕ) :
    succ S E (.Fk k) = succZ k := rfl

@[simp] lemma succ_M (S : Finset ℕ) (E : Finset (ℕ × ℕ)) (a b i : ℕ) :
    succ S E (.M a b i) = succM a b i := rfl

/-- Removing the exceptional entrances shrinks the successor sets: the
common successors are successors on either side. -/
lemma succ_empty_subset (S : Finset ℕ) (E : Finset (ℕ × ℕ)) :
    ∀ t, succ S ∅ t ⊆ succ S E t := by
  intro t
  cases t with
  | F =>
      intro x hx
      rcases Finset.mem_union.mp hx with h | h
      · exact Finset.mem_union_left _ h
      · exact absurd h (by simp)
  | Z j => exact fun x hx => hx
  | Fk k => exact fun x hx => hx
  | M a b i => exact fun x hx => hx

lemma succZ_nonempty (j : ℕ) : (succZ j).Nonempty := by
  rcases Nat.lt_or_ge j 3 with hj | hj
  · rw [succZ_le_two (by omega)]
    exact ⟨.F, Finset.mem_singleton_self _⟩
  · rcases Nat.lt_or_ge j 4 with hj4 | hj4
    · have h3 : j = 3 := by omega
      subst h3
      exact ⟨.Z 2, by rw [succZ_three]; simp⟩
    · exact ⟨.Z (j / 2), by rw [succZ_of_ge hj4]; simp⟩

lemma succM_nonempty (a b i : ℕ) : (succM a b i).Nonempty := by
  rcases Nat.lt_or_ge (val a i) 3 with h | h
  · exact ⟨.Z b, by rw [succM_le_two (by omega)]; simp⟩
  · rcases Nat.lt_or_ge (val a i) 4 with h4 | h4
    · exact ⟨.Z 2, by rw [succM_three (by omega)]; simp⟩
    · exact ⟨.M a b (i + 1), by rw [succM_of_ge h4]; simp⟩

lemma succ_nonempty_of_ne_F {S : Finset ℕ} {E : Finset (ℕ × ℕ)}
    {t : Letter} (ht : t ≠ .F) : (succ S E t).Nonempty := by
  cases t with
  | F => exact absurd rfl ht
  | Z j => simpa using succZ_nonempty j
  | Fk k => simpa using succZ_nonempty k
  | M a b i => simpa using succM_nonempty a b i

/-- With a nonempty common support every letter has a successor. -/
lemma succ_nonempty {S : Finset ℕ} (hS : S.Nonempty)
    (E : Finset (ℕ × ℕ)) (t : Letter) : (succ S E t).Nonempty := by
  by_cases hF : t = .F
  · subst hF
    obtain ⟨k, hk⟩ := hS
    obtain ⟨x, hx⟩ := succZ_nonempty k
    exact ⟨x, Finset.mem_union_left _ (Finset.mem_biUnion.mpr ⟨k, hk, hx⟩)⟩
  · exact succ_nonempty_of_ne_F hF

/-- The port depths of the composite chart below a pending vertex of
running value `v`, with port continuation `b`: the depths at which the
chart of a declared pair first exposes a fresh vertex, relative to the
pending vertex. -/
def chartPorts (b : ℕ) : ℕ → Finset ℕ
  | 0 => ((toFresh b).image (· + 1)) ∪ {1}
  | 1 => ((toFresh b).image (· + 1)) ∪ {1}
  | 2 => ((toFresh b).image (· + 1)) ∪ {1}
  | 3 => insert 2 ((toFresh b).image (· + 1))
  | v + 4 => ((chartPorts b ((v + 4) / 2)).image (· + 1))
      ∪ ((toFresh ((v + 4) - (v + 4) / 2)).image (· + 1))
decreasing_by all_goals omega

lemma chartPorts_le_two {b v : ℕ} (hv : v ≤ 2) :
    chartPorts b v = ((toFresh b).image (· + 1)) ∪ {1} := by
  match v, hv with
  | 0, _ => rw [chartPorts]
  | 1, _ => rw [chartPorts]
  | 2, _ => rw [chartPorts]

lemma chartPorts_three (b : ℕ) :
    chartPorts b 3 = insert 2 ((toFresh b).image (· + 1)) := by
  rw [chartPorts]

lemma chartPorts_of_ge {b v : ℕ} (hv : 4 ≤ v) :
    chartPorts b v = ((chartPorts b (v / 2)).image (· + 1))
      ∪ ((toFresh (v - v / 2)).image (· + 1)) := by
  obtain ⟨m, rfl⟩ : ∃ m, v = m + 4 := ⟨v - 4, by omega⟩
  rw [chartPorts]

/-- The port-depth set of a letter: the possible distances to the first
fresh vertex below it. -/
def ports : Letter → Finset ℕ
  | .F => {0}
  | .Z j => toFresh j
  | .Fk k => toFresh k
  | .M a b i => chartPorts b (val a i)

@[simp] lemma ports_F : ports .F = {0} := rfl
@[simp] lemma ports_Z (j : ℕ) : ports (.Z j) = toFresh j := rfl
@[simp] lemma ports_Fk (k : ℕ) : ports (.Fk k) = toFresh k := rfl
@[simp] lemma ports_M (a b i : ℕ) :
    ports (.M a b i) = chartPorts b (val a i) := rfl

/-- Stepping into a successor of a forced counter shifts its port depths
into the counter's return lengths. -/
lemma add_one_mem_toFresh_of_mem_succZ {j : ℕ} {t : Letter}
    (ht : t ∈ succZ j) {e : ℕ} (he : e ∈ ports t) :
    e + 1 ∈ toFresh j := by
  rcases Nat.lt_or_ge j 3 with hj | hj
  · rw [succZ_le_two (by omega)] at ht
    rw [Finset.mem_singleton] at ht
    subst ht
    rw [ports_F, Finset.mem_singleton] at he
    subst he
    rw [toFresh_le_two (by omega)]
    simp
  · rcases Nat.lt_or_ge j 4 with hj4 | hj4
    · have h3 : j = 3 := by omega
      subst h3
      rw [succZ_three] at ht
      rcases Finset.mem_insert.mp ht with rfl | ht
      · rw [ports_Z, toFresh_le_two (by omega), Finset.mem_singleton] at he
        subst he
        rw [toFresh_three]
        simp
      · rw [Finset.mem_singleton] at ht
        subst ht
        rw [ports_F, Finset.mem_singleton] at he
        subst he
        rw [toFresh_three]
        simp
    · rw [succZ_of_ge hj4] at ht
      rw [toFresh_of_ge hj4]
      rcases Finset.mem_insert.mp ht with rfl | ht
      · exact Finset.mem_union_left _ (Finset.mem_image_of_mem _ he)
      · rw [Finset.mem_singleton] at ht
        subst ht
        exact Finset.mem_union_right _ (Finset.mem_image_of_mem _ he)

/-- Stepping into a successor of a marker shifts its port depths into the
chart ports of the current running value. -/
lemma add_one_mem_chartPorts_of_mem_succM {a b i : ℕ} {t : Letter}
    (ht : t ∈ succM a b i) {e : ℕ} (he : e ∈ ports t) :
    e + 1 ∈ chartPorts b (val a i) := by
  rcases Nat.lt_or_ge (val a i) 3 with h2 | h2
  · rw [succM_le_two (by omega)] at ht
    rw [chartPorts_le_two (by omega)]
    rcases Finset.mem_insert.mp ht with rfl | ht
    · exact Finset.mem_union_left _ (Finset.mem_image_of_mem _ he)
    · rw [Finset.mem_singleton] at ht
      subst ht
      rw [ports_F, Finset.mem_singleton] at he
      subst he
      exact Finset.mem_union_right _ (by simp)
  · rcases Nat.lt_or_ge (val a i) 4 with h4 | h4
    · have h3 : val a i = 3 := by omega
      rw [succM_three h3] at ht
      rw [h3, chartPorts_three]
      rcases Finset.mem_insert.mp ht with rfl | ht
      · rw [ports_Z, toFresh_le_two (by omega), Finset.mem_singleton] at he
        subst he
        simp
      · rw [Finset.mem_singleton] at ht
        subst ht
        exact Finset.mem_insert_of_mem (Finset.mem_image_of_mem _ he)
    · rw [succM_of_ge h4] at ht
      rw [chartPorts_of_ge h4]
      rcases Finset.mem_insert.mp ht with rfl | ht
      · rw [ports_M, val_succ] at he
        exact Finset.mem_union_left _ (Finset.mem_image_of_mem _ he)
      · rw [Finset.mem_singleton] at ht
        subst ht
        exact Finset.mem_union_right _ (Finset.mem_image_of_mem _ he)

/-- **Chart returns** (`thm:chart-returns`): every chart port depth is
a return length of the running value, or a return length of the running
value plus a return length of the port continuation. -/
lemma chartPorts_cases (b : ℕ) : ∀ v, ∀ e ∈ chartPorts b v,
    e ∈ toFresh v ∨ ∃ d ∈ toFresh v, ∃ f ∈ toFresh b, e = d + f := by
  intro v
  induction v using Nat.strong_induction_on with
  | _ v ih =>
    intro e he
    rcases Nat.lt_or_ge v 3 with hv | hv
    · rw [chartPorts_le_two (by omega)] at he
      rw [toFresh_le_two (by omega)]
      rcases Finset.mem_union.mp he with h | h
      · obtain ⟨f, hf, rfl⟩ := Finset.mem_image.mp h
        exact Or.inr ⟨1, by simp, f, hf, by omega⟩
      · rw [Finset.mem_singleton] at h
        subst h
        exact Or.inl (by simp)
    · rcases Nat.lt_or_ge v 4 with hv4 | hv4
      · have h3 : v = 3 := by omega
        subst h3
        rw [chartPorts_three] at he
        rw [toFresh_three]
        rcases Finset.mem_insert.mp he with rfl | h
        · exact Or.inl (by simp)
        · obtain ⟨f, hf, rfl⟩ := Finset.mem_image.mp h
          exact Or.inr ⟨1, by simp, f, hf, by omega⟩
      · rw [chartPorts_of_ge hv4] at he
        rcases Finset.mem_union.mp he with h | h
        · obtain ⟨e', he', rfl⟩ := Finset.mem_image.mp h
          rcases ih (v / 2) (by omega) e' he' with h' | ⟨d, hd, f, hf, rfl⟩
          · refine Or.inl ?_
            rw [toFresh_of_ge hv4]
            exact Finset.mem_union_left _ (Finset.mem_image_of_mem _ h')
          · refine Or.inr ⟨d + 1, ?_, f, hf, by omega⟩
            rw [toFresh_of_ge hv4]
            exact Finset.mem_union_left _ (Finset.mem_image_of_mem _ hd)
        · obtain ⟨e', he', rfl⟩ := Finset.mem_image.mp h
          refine Or.inl ?_
          rw [toFresh_of_ge hv4]
          exact Finset.mem_union_right _ (Finset.mem_image_of_mem _ he')

/-- Admissible descents (`def:composite-descents`): chains of letter
successors. -/
inductive Descend (S : Finset ℕ) (E : Finset (ℕ × ℕ)) :
    Letter → ℕ → Letter → Prop where
  | refl (t : Letter) : Descend S E t 0 t
  | step {t t' t'' : Letter} {m : ℕ} (h : t' ∈ succ S E t)
      (hd : Descend S E t' m t'') : Descend S E t (m + 1) t''

lemma Descend.trans {S : Finset ℕ} {E : Finset (ℕ × ℕ)}
    {t t' t'' : Letter} {m m' : ℕ}
    (h : Descend S E t m t') (h' : Descend S E t' m' t'') :
    Descend S E t (m + m') t'' := by
  revert h'
  induction h with
  | refl t => intro h'; simpa using h'
  | @step t₁ t₂ t₃ m₁ hst hd ih =>
      intro h'
      rw [show m₁ + 1 + m' = m₁ + m' + 1 by omega]
      exact .step hst (ih h')

/-- The common return-depth monoid `Σ_S` of
`def:return-lengths`. -/
def SigmaS (S : Finset ℕ) : AddSubmonoid ℕ :=
  AddSubmonoid.closure (depthSet S : Set ℕ)

lemma mem_sigmaS_of_mem_depthSet {S : Finset ℕ} {d : ℕ}
    (hd : d ∈ depthSet S) : d ∈ SigmaS S :=
  AddSubmonoid.subset_closure hd

/-- Every return length of a charged counter is realized by a descent, from
any letter whose successor set contains the counter's cascade successors. -/
lemma descend_toFresh {S : Finset ℕ} {E : Finset (ℕ × ℕ)} :
    ∀ k, ∀ d ∈ toFresh k, ∀ t : Letter, succZ k ⊆ succ S E t →
      Descend S E t d .F := by
  intro k
  induction k using Nat.strong_induction_on with
  | _ k ih =>
    intro d hd t hsub
    rcases Nat.lt_or_ge k 3 with hk | hk
    · rw [toFresh_le_two (by omega), Finset.mem_singleton] at hd
      subst hd
      refine .step (hsub ?_) (.refl _)
      rw [succZ_le_two (by omega)]
      simp
    · rcases Nat.lt_or_ge k 4 with hk4 | hk4
      · have h3 : k = 3 := by omega
        subst h3
        rw [toFresh_three] at hd
        rcases Finset.mem_insert.mp hd with rfl | hd
        · refine .step (hsub ?_) (.refl _)
          rw [succZ_three]
          simp
        · rw [Finset.mem_singleton] at hd
          subst hd
          refine .step (t' := .Z 2) (hsub ?_) ?_
          · rw [succZ_three]
            simp
          · refine ih 2 (by omega) 1 ?_ (.Z 2) (fun x hx => hx)
            rw [toFresh_le_two (by omega)]
            simp
      · rw [toFresh_of_ge hk4] at hd
        rcases Finset.mem_union.mp hd with h | h
        · obtain ⟨e, he, rfl⟩ := Finset.mem_image.mp h
          refine .step (hsub ?_)
            (ih (k / 2) (by omega) e he (.Z (k / 2)) (fun x hx => hx))
          rw [succZ_of_ge hk4]
          simp
        · obtain ⟨e, he, rfl⟩ := Finset.mem_image.mp h
          refine .step (hsub ?_)
            (ih (k - k / 2) (by omega) e he (.Z (k - k / 2)) (fun x hx => hx))
          rw [succZ_of_ge hk4]
          simp

/-- Realization, the containment `Σ_S ⊆ {m : F ⇓_m F}` of
`thm:composite-realise`: valid on either side, using common letters
only. -/
lemma descend_F_of_mem_sigmaS {S : Finset ℕ} {E : Finset (ℕ × ℕ)} {m : ℕ}
    (hm : m ∈ SigmaS S) : Descend S E .F m .F := by
  refine AddSubmonoid.closure_induction (fun d hd => ?_) (.refl _)
    (fun x y _ _ ihx ihy => ihx.trans ihy) hm
  obtain ⟨k, hk, hdk⟩ := Finset.mem_biUnion.mp (Finset.mem_coe.mp hd)
  exact descend_toFresh k d hdk .F
    (fun x hx => Finset.mem_union_left _ (Finset.mem_biUnion.mpr ⟨k, hk, hx⟩))

/-- Every descent to the fresh letter decomposes as a port depth of its
source plus an element of `Σ_S`.  The hypothesis on `E` is the declared
membership of the composite pairs in the common support. -/
lemma exists_ports_decomp {S : Finset ℕ} {E : Finset (ℕ × ℕ)}
    (hE : ∀ p ∈ E, p.1 ∈ S ∧ p.2 ∈ S) :
    ∀ {t : Letter} {m : ℕ} {u : Letter}, Descend S E t m u → u = .F →
      ∃ e ∈ ports t, ∃ s ∈ SigmaS S, m = e + s := by
  intro t m u h
  induction h with
  | refl t =>
      rintro rfl
      exact ⟨0, by simp, 0, zero_mem _, by simp⟩
  | @step t₁ t₂ t₃ m₁ hst hd ih =>
      intro hu
      obtain ⟨e', he', s, hs, rfl⟩ := ih hu
      cases t₁ with
      | F =>
          rcases Finset.mem_union.mp hst with hcom | hexc
          · obtain ⟨k, hk, ht₂⟩ := Finset.mem_biUnion.mp hcom
            have hgen : e' + 1 ∈ toFresh k :=
              add_one_mem_toFresh_of_mem_succZ ht₂ he'
            refine ⟨0, by simp, (e' + 1) + s, ?_, by omega⟩
            exact add_mem
              (mem_sigmaS_of_mem_depthSet (Finset.mem_biUnion.mpr ⟨k, hk, hgen⟩)) hs
          · obtain ⟨p, hp, ht₂⟩ := Finset.mem_biUnion.mp hexc
            have hstep : e' + 1 ∈ chartPorts p.2 (val p.1 0) :=
              add_one_mem_chartPorts_of_mem_succM ht₂ he'
            rw [val_zero] at hstep
            have hmem : e' + 1 ∈ SigmaS S := by
              rcases chartPorts_cases p.2 p.1 (e' + 1) hstep with
                h1 | ⟨d, hd', f, hf, heq⟩
              · exact mem_sigmaS_of_mem_depthSet
                  (Finset.mem_biUnion.mpr ⟨p.1, (hE p hp).1, h1⟩)
              · rw [heq]
                exact add_mem
                  (mem_sigmaS_of_mem_depthSet
                    (Finset.mem_biUnion.mpr ⟨p.1, (hE p hp).1, hd'⟩))
                  (mem_sigmaS_of_mem_depthSet
                    (Finset.mem_biUnion.mpr ⟨p.2, (hE p hp).2, hf⟩))
            exact ⟨0, by simp, (e' + 1) + s, add_mem hmem hs, by omega⟩
      | Z j =>
          have hst' : t₂ ∈ succZ j := hst
          exact ⟨e' + 1, add_one_mem_toFresh_of_mem_succZ hst' he', s, hs, by omega⟩
      | Fk k =>
          have hst' : t₂ ∈ succZ k := hst
          exact ⟨e' + 1, add_one_mem_toFresh_of_mem_succZ hst' he', s, hs, by omega⟩
      | M a b i =>
          have hst' : t₂ ∈ succM a b i := hst
          exact ⟨e' + 1, add_one_mem_chartPorts_of_mem_succM hst' he', s, hs, by omega⟩

/-- **Realization** (`thm:composite-realise`): the fresh-to-fresh descent
lengths are exactly the common return-depth monoid, on either side. -/
theorem descend_F_iff_mem_sigmaS {S : Finset ℕ} {E : Finset (ℕ × ℕ)}
    (hE : ∀ p ∈ E, p.1 ∈ S ∧ p.2 ∈ S) {m : ℕ} :
    Descend S E .F m .F ↔ m ∈ SigmaS S := by
  constructor
  · intro h
    obtain ⟨e, he, s, hs, rfl⟩ := exists_ports_decomp hE h rfl
    have he0 : e = 0 := by simpa using he
    subst he0
    simpa using hs
  · exact descend_F_of_mem_sigmaS

/-- The forced-depth measure: strictly decreasing along successors below
any non-fresh letter. -/
def meas : Letter → ℕ
  | .F => 0
  | .Z j => j
  | .Fk k => k
  | .M a b i => val a i + b + 1

lemma meas_lt_of_mem_succ {S : Finset ℕ} {E : Finset (ℕ × ℕ)}
    {t t' : Letter} (ht : t ≠ .F) (ht' : t' ≠ .F)
    (h : t' ∈ succ S E t) : meas t' < meas t := by
  cases t with
  | F => exact absurd rfl ht
  | Z j =>
      have h' : t' ∈ succZ j := h
      rcases Nat.lt_or_ge j 3 with hj | hj
      · rw [succZ_le_two (by omega), Finset.mem_singleton] at h'
        exact absurd h' ht'
      · rcases Nat.lt_or_ge j 4 with hj4 | hj4
        · have h3 : j = 3 := by omega
          subst h3
          rw [succZ_three] at h'
          rcases Finset.mem_insert.mp h' with rfl | h'
          · simp [meas]
          · rw [Finset.mem_singleton] at h'
            exact absurd h' ht'
        · rw [succZ_of_ge hj4] at h'
          rcases Finset.mem_insert.mp h' with rfl | h'
          · simp only [meas]
            omega
          · rw [Finset.mem_singleton] at h'
            subst h'
            simp only [meas]
            omega
  | Fk k =>
      have h' : t' ∈ succZ k := h
      rcases Nat.lt_or_ge k 3 with hk | hk
      · rw [succZ_le_two (by omega), Finset.mem_singleton] at h'
        exact absurd h' ht'
      · rcases Nat.lt_or_ge k 4 with hk4 | hk4
        · have h3 : k = 3 := by omega
          subst h3
          rw [succZ_three] at h'
          rcases Finset.mem_insert.mp h' with rfl | h'
          · simp [meas]
          · rw [Finset.mem_singleton] at h'
            exact absurd h' ht'
        · rw [succZ_of_ge hk4] at h'
          rcases Finset.mem_insert.mp h' with rfl | h'
          · simp only [meas]
            omega
          · rw [Finset.mem_singleton] at h'
            subst h'
            simp only [meas]
            omega
  | M a b i =>
      have h' : t' ∈ succM a b i := h
      rcases Nat.lt_or_ge (val a i) 3 with h2 | h2
      · rw [succM_le_two (by omega)] at h'
        rcases Finset.mem_insert.mp h' with rfl | h'
        · simp only [meas]
          omega
        · rw [Finset.mem_singleton] at h'
          exact absurd h' ht'
      · rcases Nat.lt_or_ge (val a i) 4 with h4 | h4
        · have h3 : val a i = 3 := by omega
          rw [succM_three h3] at h'
          rcases Finset.mem_insert.mp h' with rfl | h'
          · simp only [meas]
            omega
          · rw [Finset.mem_singleton] at h'
            subst h'
            simp only [meas]
            omega
        · rw [succM_of_ge h4] at h'
          rcases Finset.mem_insert.mp h' with rfl | h'
          · simp only [meas, val_succ]
            omega
          · rw [Finset.mem_singleton] at h'
            subst h'
            simp only [meas]
            omega

/-- Every letter has a descent to the fresh letter. -/
lemma exists_descend_F {S : Finset ℕ} {E : Finset (ℕ × ℕ)} (t : Letter) :
    ∃ m, Descend S E t m .F := by
  suffices h : ∀ M t, meas t ≤ M → ∃ m, Descend S E t m .F from
    h (meas t) t le_rfl
  intro M
  induction M with
  | zero =>
      intro t hM
      by_cases hF : t = .F
      · exact ⟨0, hF ▸ .refl _⟩
      · obtain ⟨t', ht'⟩ := succ_nonempty_of_ne_F (S := S) (E := E) hF
        by_cases hF' : t' = .F
        · exact ⟨1, .step (hF' ▸ ht') (.refl _)⟩
        · exact absurd (lt_of_lt_of_le (meas_lt_of_mem_succ hF hF' ht') hM)
            (Nat.not_lt_zero _)
  | succ M ih =>
      intro t hM
      by_cases hF : t = .F
      · exact ⟨0, hF ▸ .refl _⟩
      · obtain ⟨t', ht'⟩ := succ_nonempty_of_ne_F (S := S) (E := E) hF
        by_cases hF' : t' = .F
        · exact ⟨1, .step (hF' ▸ ht') (.refl _)⟩
        · have hlt := meas_lt_of_mem_succ hF hF' ht'
          obtain ⟨m, hm⟩ := ih t' (by omega)
          exact ⟨m + 1, .step ht' hm⟩

end Composite
end GraphMarkovMatching
