/-
`thm:harris` of `matching_classes_simple.tex` and `thm:harris-general` of
`matching_classes_general.tex` beyond the root: **the Harris decomposition**.  Conditioned
on survival the skeleton of a sample is again a Galton-Watson tree, for the reduced law
`eq:hs-transform`, and conditioned on extinction a sample is a Galton-Watson tree for the
conjugate law.

`Conditioned` settles the root: conditioned on survival the number of surviving children
of the root has the reduced law, and conditioned on dying the offspring count at the root
carries the conjugate tilt.  Propagating those through the generations needs a carrier for
"the law of a random tree", which is what the first section supplies.

*The design.*  Two carriers are in play and the file uses both, each where it is exact.
A sample is cut out by an offspring field `c : Word N → ℕ`, and the whole existing
machinery, `sampleMeasure`, the splitting `map_split`, `survivalMeasure`, lives on that
function space, so the skeleton is built there too: `skelField` is the offspring field of
the skeleton, re-addressed so that the `m`-th surviving child of a skeleton vertex is
reached by the letter `m`.  The field is the right carrier for the construction.  It is
not the right carrier for the statement.  The re-addressing is defined at every word, but
only the words naming an actual skeleton vertex carry information; at the others
`skelField` returns a value fixed by the construction, and no convention there can be
distributed like an offspring count.  So the *law* is carried by the tree: `Subtree N`
gets the measurable structure generated by the vertex events `{T | v ∈ T}`, `sample` is
measurable into it, and `treeLaw θ` is the law of the Galton-Watson tree of `θ`.  The
skeleton law `skeletonTreeLaw θ` is the pushforward of `survivalMeasure θ` along
`skelTree = sample ∘ skelField`, which forgets exactly the addresses that carry nothing,
and the bush law `bushTreeLaw θ` is the pushforward of `bushMeasure θ` along `sample`.

* `Subtree.instMeasurableSpace`, `measurableSet_mem_subtree`, `measurable_of_mem_subtree`
  and `measurable_sample`: the measurable structure on subtrees generated by the vertex
  events, and the sample as a random tree.
* `treeLaw`: **the law of the Galton-Watson tree** of an offspring law.
* `Offspring.surviveWeight_vanishing`, `Offspring.sum_surviveWeight`,
  `Offspring.sum_skeletonWeight` and `Offspring.reduced`: **the reduced law**
  `eq:hs-transform` as an offspring law in its own right, of the same support bound; the
  weights sum to one by the binomial theorem at `(1-q) + q = 1`.
* `Offspring.conjugateWeight`, `Offspring.sum_conjugateWeight` and
  `Offspring.conjugate`: **the conjugate law** `θ_j q^j / q`, likewise; its weights sum to
  one because `q` is a fixed point of the generating function.
* `Offspring.tail`, `Offspring.tailGe` and `Offspring.skeletonTail`: the mass a law puts
  above an arity.
* `bushOf`, `bushAt`: the offspring field of the `m`-th surviving child subtree of the
  root, with `bushAt_of_lt`, `survives_bushAt` and `measurable_bushAt`.
* `skelSub`, `skelField`, `skelTree`: **the skeleton re-addressed**, the offspring field
  of the skeleton and the tree it cuts out, with the recursion `mem_skelTree_cons` and
  `measurable_skelField`.
* `rankOf`, `rankOf_orderEmbOfFin` and `prod_rankOf`: the rank of a surviving child among
  the survivors, the address it receives in the re-addressed skeleton, and the reindexing
  of a product over the survivors by that rank.
* `prod_ite_survivors_family`, `bushesBox`, `dyingBox` and their preimage lemmas: the
  survival pattern of the children of the root with every surviving or with every dying
  subtree constrained, read through the splitting as a product event; the statements
  with one subtree constrained are the instances with a single constraint.
* `survivalMeasure_bushAt` and `survivalMeasure_skeletonDegree_bushes`: **the branching
  property of the skeleton**.  Conditioned on survival, the root has `k` skeleton children
  with probability `θ̃_k`, and the `k` surviving subtrees are independent copies of the
  conditioned law.
* `PrefixClosed`, `wordSub`, `rootDeg`, `subset_skelTree_iff` and `subset_sample_iff`: the
  finite prefix-closed sets of words and the one-step criteria for a tree to contain one.
* `survivalMeasure_subset_skelTree_step`, `sampleMeasure_subset_sample_step` and
  `survivalMeasure_subset_skelTree`: the two recursions and the induction on the height of
  the set that matches them.
* `containmentSets`, `isPiSystem_containmentSets` and `generateFrom_containmentSets`: the
  containment events of the finite prefix-closed sets of words, a π-system generating the
  measurable structure on subtrees.
* `skeletonTreeLaw_eq_treeLaw`: **the Harris recursion**,
  `thm:harris`\labelcref{it:harris-skeleton}.  The law of the re-addressed skeleton of a
  sample conditioned to survive is the law of the Galton-Watson tree of the reduced law.
* `bushMeasure_dying`, `bushMeasure_subset_sample` and `bushTreeLaw_eq_treeLaw`: **the
  bushes**, `thm:harris`\labelcref{it:harris-bushes}.  The same route with the dying
  subtrees constrained: the law of a sample conditioned to die is the law of the
  Galton-Watson tree of the conjugate law.

The alphabet has to be wide enough to carry the law, so `J ≤ N` runs through the measure
statements as in `Law` and `Conditioned`, together with `q < 1` for the skeleton, without
which the conditioning is on a null event, and `0 < q` for the bushes.
-/
import BranchingProcess.Conditioned

namespace BranchingProcess

open MeasureTheory ProbabilityTheory ENNReal

variable {J N : ℕ}

/-! ### The measurable space of subtrees -/

/-- The measurable structure on subtrees of `𝒩(N)`: the one generated by the vertex
events `{T | v ∈ T}`.  A subtree is determined by which words it contains, so these are
the events a random tree has to answer, and the σ-algebra they generate is the smallest
making every such question measurable. -/
instance Subtree.instMeasurableSpace : MeasurableSpace (Subtree N) :=
  MeasurableSpace.generateFrom {s | ∃ v : Word N, s = {T : Subtree N | v ∈ T}}

/-- A vertex event is measurable. -/
theorem measurableSet_mem_subtree (v : Word N) :
    MeasurableSet {T : Subtree N | v ∈ T} :=
  MeasurableSpace.measurableSet_generateFrom ⟨v, rfl⟩

/-- **The criterion for a random tree.**  A map into subtrees is measurable exactly when
every vertex event pulls back to a measurable event. -/
theorem measurable_of_mem_subtree {α : Type*} [MeasurableSpace α] {f : α → Subtree N}
    (h : ∀ v : Word N, MeasurableSet {x | v ∈ f x}) : Measurable f :=
  measurable_generateFrom (by rintro _ ⟨v, rfl⟩; exact h v)

/-- **The sample is a random tree**: the tree cut out by an offspring field is a
measurable function of the field, by `measurableSet_mem_sample`. -/
theorem measurable_sample : Measurable (sample : (Word N → ℕ) → Subtree N) :=
  measurable_of_mem_subtree fun v ↦ measurableSet_mem_sample v

/-- **The law of the Galton-Watson tree** of an offspring law: the pushforward of the
law of the offspring field along the sample. -/
noncomputable def treeLaw (θ : Offspring J) : Measure (Subtree N) :=
  (sampleMeasure θ).map sample

instance isProbabilityMeasure_treeLaw (θ : Offspring J) :
    IsProbabilityMeasure (treeLaw (N := N) θ) := by
  rw [treeLaw]
  exact Measure.isProbabilityMeasure_map measurable_sample.aemeasurable

/-! ### The reduced law as an offspring law -/

namespace Offspring

variable (θ : Offspring J)

/-- The surviving-children weights vanish above the support bound: a root with at most
`J` children cannot have more than `J` of them survive. -/
lemma surviveWeight_vanishing {k : ℕ} (hk : J < k) : θ.surviveWeight k = 0 := by
  refine Finset.sum_eq_zero fun j hj ↦ ?_
  rw [Finset.mem_range] at hj
  rw [Nat.choose_eq_zero_of_lt (by omega)]
  simp

/-- **The surviving-children weights are a probability distribution.**  Summing the
binomial count over the number of survivors is the binomial theorem at `(1-q) + q = 1`,
and what is left is the offspring law itself. -/
lemma sum_surviveWeight : ∑ k ∈ Finset.range (J + 1), θ.surviveWeight k = 1 := by
  have hbinom : ∀ j ∈ Finset.range (J + 1),
      ∑ k ∈ Finset.range (J + 1),
          (1 - θ.extinction) ^ k * θ.extinction ^ (j - k) * (j.choose k : ℝ) = 1 := by
    intro j hj
    rw [Finset.mem_range] at hj
    have hext : ∑ k ∈ Finset.range (j + 1),
        (1 - θ.extinction) ^ k * θ.extinction ^ (j - k) * (j.choose k : ℝ)
        = ∑ k ∈ Finset.range (J + 1),
            (1 - θ.extinction) ^ k * θ.extinction ^ (j - k) * (j.choose k : ℝ) := by
      refine Finset.sum_subset ?_ ?_
      · exact Finset.range_subset_range.mpr (by omega)
      · intro k _ hk
        simp only [Finset.mem_range, not_lt] at hk
        rw [Nat.choose_eq_zero_of_lt (by omega)]
        simp
    rw [← hext, ← add_pow]
    simp
  calc ∑ k ∈ Finset.range (J + 1), θ.surviveWeight k
      = ∑ j ∈ Finset.range (J + 1), ∑ k ∈ Finset.range (J + 1),
          θ j * (j.choose k : ℝ) * (1 - θ.extinction) ^ k * θ.extinction ^ (j - k) :=
        Finset.sum_comm
    _ = ∑ j ∈ Finset.range (J + 1), θ j * ∑ k ∈ Finset.range (J + 1),
          (1 - θ.extinction) ^ k * θ.extinction ^ (j - k) * (j.choose k : ℝ) := by
        refine Finset.sum_congr rfl fun j _ ↦ ?_
        rw [Finset.mul_sum]
        exact Finset.sum_congr rfl fun k _ ↦ by ring
    _ = ∑ j ∈ Finset.range (J + 1), θ j := by
        refine Finset.sum_congr rfl fun j hj ↦ ?_
        rw [hbinom j hj, mul_one]
    _ = 1 := θ.total

/-- The reduced weights are nonnegative once the tree survives with positive
probability. -/
lemma skeletonWeight_nonneg (hq : θ.extinction < 1) (k : ℕ) : 0 ≤ θ.skeletonWeight k := by
  rw [skeletonWeight]
  split
  · exact le_rfl
  · exact div_nonneg (θ.surviveWeight_nonneg k) (by linarith)

/-- The reduced weights vanish above the support bound, which is therefore inherited. -/
lemma skeletonWeight_vanishing {k : ℕ} (hk : J < k) : θ.skeletonWeight k = 0 := by
  rw [skeletonWeight]
  split
  · rfl
  · rw [θ.surviveWeight_vanishing hk, zero_div]

/-- **The reduced weights sum to one.**  The surviving-children weights sum to one, the
weight at zero is the extinction probability, and the renormalisation by `1-q` is exactly
what removes it. -/
lemma sum_skeletonWeight (hq : θ.extinction < 1) :
    ∑ k ∈ Finset.range (J + 1), θ.skeletonWeight k = 1 := by
  have hne : (1 : ℝ) - θ.extinction ≠ 0 := by linarith
  have hshift : ∑ k ∈ Finset.range J, θ.surviveWeight (k + 1) = 1 - θ.extinction := by
    have h := θ.sum_surviveWeight
    rw [Finset.sum_range_succ' θ.surviveWeight J, θ.surviveWeight_zero] at h
    linarith
  rw [Finset.sum_range_succ' θ.skeletonWeight J, θ.skeletonWeight_zero, add_zero]
  have hterm : ∀ k ∈ Finset.range J,
      θ.skeletonWeight (k + 1) = θ.surviveWeight (k + 1) / (1 - θ.extinction) :=
    fun k _ ↦ θ.skeletonWeight_of_ne_zero (Nat.succ_ne_zero k)
  rw [Finset.sum_congr rfl hterm, ← Finset.sum_div, hshift, div_self hne]

/-- **The reduced law** `eq:hs-transform` as an offspring law in its own right: the
Harris-Sevastyanov transform of `θ`, of the same support bound `J`.  This is the law the
skeleton of a surviving sample branches with. -/
noncomputable def reduced (hq : θ.extinction < 1) : Offspring J where
  mass := θ.skeletonWeight
  nonneg := θ.skeletonWeight_nonneg hq
  vanishing := fun _ hj ↦ θ.skeletonWeight_vanishing hj
  total := θ.sum_skeletonWeight hq

@[simp] lemma reduced_apply (hq : θ.extinction < 1) (k : ℕ) :
    θ.reduced hq k = θ.skeletonWeight k := rfl

/-- The mass the reduced law puts on a skeleton arity above `m`: the probability that a
skeleton vertex has more than `m` children. -/
noncomputable def skeletonTail (m : ℕ) : ℝ :=
  ∑ k ∈ Finset.range (J + 1), if m < k then θ.skeletonWeight k else 0

end Offspring

/-! ### The surviving subtrees of the root, re-addressed -/

/-- The offspring field of the `m`-th surviving child subtree of a root whose surviving
children are named by `S`, the children being ordered by the alphabet; the zero field
when there are at most `m` of them.  The junk value is never read: every statement below
guards it by `m < skeletonDegree c`. -/
noncomputable def bushOf (S : Finset (Fin N)) (m : ℕ) (c : Word N → ℕ) : Word N → ℕ :=
  if h : m < S.card then (fun w ↦ c (S.orderEmbOfFin rfl ⟨m, h⟩ :: w)) else fun _ ↦ 0

/-- **The `m`-th surviving subtree of the root**: the offspring field of the subtree
founded by the `m`-th child of the root that survives. -/
noncomputable def bushAt (c : Word N → ℕ) (m : ℕ) : Word N → ℕ := bushOf (survivors c) m c

/-- The skeleton degree is the number of surviving children, unfolded. -/
lemma skeletonDegree_eq_card (c : Word N → ℕ) : skeletonDegree c = (survivors c).card := rfl

/-- Below the skeleton degree the `m`-th surviving subtree is the shift of the field to
the letter naming that child. -/
lemma bushAt_of_lt {c : Word N → ℕ} {m : ℕ} (h : m < (survivors c).card) :
    bushAt c m = fun w ↦ c ((survivors c).orderEmbOfFin rfl ⟨m, h⟩ :: w) := by
  rw [bushAt, bushOf, dif_pos h]

/-- The letter naming the `m`-th surviving child is one of the surviving children. -/
lemma orderEmbOfFin_mem_survivors {c : Word N → ℕ} {m : ℕ} (h : m < (survivors c).card) :
    (survivors c).orderEmbOfFin rfl ⟨m, h⟩ ∈ survivors c :=
  Finset.orderEmbOfFin_mem _ _ _

/-- **A surviving subtree survives.** -/
lemma survives_bushAt {c : Word N → ℕ} {m : ℕ} (h : m < skeletonDegree c) :
    Survives (bushAt c m) := by
  rw [bushAt_of_lt h]
  exact (mem_survivors.mp (orderEmbOfFin_mem_survivors h)).2

/-- The `m`-th surviving subtree of a prescribed pattern of survivors is a measurable
function of the field: it is a shift, or a constant. -/
lemma measurable_bushOf (S : Finset (Fin N)) (m : ℕ) :
    Measurable (fun c : Word N → ℕ ↦ bushOf S m c) := by
  by_cases h : m < S.card
  · simp only [bushOf, dif_pos h]
    exact measurable_pi_lambda _ fun _ ↦ measurable_pi_apply _
  · simp only [bushOf, dif_neg h]
    exact measurable_const

/-- **The surviving subtrees are measurable.**  The pattern of survivors takes finitely
many values, and on each of the corresponding events the subtree is a shift. -/
lemma measurable_bushAt (m : ℕ) : Measurable (fun c : Word N → ℕ ↦ bushAt c m) := by
  intro t ht
  have h : (fun c : Word N → ℕ ↦ bushAt c m) ⁻¹' t
      = ⋃ S : Finset (Fin N),
          ({c : Word N → ℕ | survivors c = S} ∩ (fun c : Word N → ℕ ↦ bushOf S m c) ⁻¹' t) := by
    ext c
    simp only [Set.mem_preimage, Set.mem_iUnion, Set.mem_inter_iff, Set.mem_setOf_eq]
    constructor
    · intro hc
      exact ⟨survivors c, rfl, hc⟩
    · rintro ⟨S, rfl, hc⟩
      exact hc
  rw [h]
  exact MeasurableSet.iUnion fun S ↦
    (measurableSet_survivors_eq S).inter (measurable_bushOf S m ht)

/-! ### The skeleton as an offspring field -/

/-- **The subtree of the skeleton at an address.**  A word `u` is read as an address in
the skeleton: its letters name successive surviving children, the letter `m` selecting
the `m`-th of them, and `skelSub c u` is the offspring field of the subtree the address
leads to. -/
noncomputable def skelSub : (Word N → ℕ) → Word N → (Word N → ℕ)
  | c, [] => c
  | c, (j :: u) => skelSub (bushAt c j) u

@[simp] lemma skelSub_nil (c : Word N → ℕ) : skelSub c [] = c := rfl

@[simp] lemma skelSub_cons (c : Word N → ℕ) (j : Fin N) (u : Word N) :
    skelSub c (j :: u) = skelSub (bushAt c j) u := rfl

/-- **The offspring field of the skeleton**: the number of surviving children of the
skeleton vertex an address leads to.  The re-addressing is what makes the skeleton a
sample again: the `m`-th surviving child is reached by the letter `m`. -/
noncomputable def skelField (c : Word N → ℕ) : Word N → ℕ := fun u ↦ skeletonDegree (skelSub c u)

@[simp] lemma skelField_nil (c : Word N → ℕ) : skelField c [] = skeletonDegree c := rfl

@[simp] lemma skelField_cons (c : Word N → ℕ) (j : Fin N) (u : Word N) :
    skelField c (j :: u) = skelField (bushAt c j) u := rfl

/-- **The skeleton, re-addressed**: the tree cut out by the offspring field of the
skeleton, an isomorphic copy of the skeleton of `sample c` inside `𝒩(N)`. -/
noncomputable def skelTree (c : Word N → ℕ) : Subtree N := sample (skelField c)

/-- **The one-step criterion for the skeleton.**  An address `j :: u` names a skeleton
vertex exactly when the root has more than `j` surviving children and `u` names a vertex
of the skeleton of the `j`-th of them. -/
lemma mem_skelTree_cons {c : Word N → ℕ} {j : Fin N} {u : Word N} :
    j :: u ∈ skelTree c ↔ (j : ℕ) < skeletonDegree c ∧ u ∈ skelTree (bushAt c (j : ℕ)) := by
  show (([j] : Word N) ++ u) ∈ sample (skelField c) ↔ _
  rw [append_mem_sample_iff, singleton_mem_sample_iff]
  exact Iff.rfl

/-- The root is a skeleton vertex exactly when the sample survives. -/
@[simp] lemma nil_mem_skelTree (c : Word N → ℕ) : ([] : Word N) ∈ skelTree c :=
  nil_mem_sample _

/-! ### Measurability of the skeleton -/

/-- Following a fixed address is measurable. -/
lemma measurable_skelSub (u : Word N) : Measurable (fun c : Word N → ℕ ↦ skelSub c u) := by
  induction u with
  | nil => exact measurable_id
  | cons j u ih =>
      have h : (fun c : Word N → ℕ ↦ skelSub c (j :: u))
          = (fun d : Word N → ℕ ↦ skelSub d u) ∘ (fun c : Word N → ℕ ↦ bushAt c j) := rfl
      rw [h]
      exact ih.comp (measurable_bushAt (j : ℕ))

/-- **The offspring field of the skeleton is measurable.** -/
lemma measurable_skelField : Measurable (skelField : (Word N → ℕ) → Word N → ℕ) :=
  measurable_pi_lambda _ fun u ↦ measurable_skeletonDegree.comp (measurable_skelSub u)

/-- **The skeleton is a random tree.** -/
lemma measurable_skelTree : Measurable (skelTree : (Word N → ℕ) → Subtree N) :=
  measurable_sample.comp measurable_skelField

/-- **The law of the skeleton**: the law of the re-addressed skeleton of a sample
conditioned to survive. -/
noncomputable def skeletonTreeLaw (θ : Offspring J) : Measure (Subtree N) :=
  (survivalMeasure θ).map skelTree

/-! ### The survival event and the conditioned law -/

/-- The mass of the survival event splits off the conditioned law. -/
lemma sampleMeasure_survives_inter (θ : Offspring J) (hJN : J ≤ N) (hq : θ.extinction < 1)
    (A : Set (Word N → ℕ)) :
    sampleMeasure (N := N) θ ({c : Word N → ℕ | Survives c} ∩ A)
      = ENNReal.ofReal (1 - θ.extinction) * survivalMeasure θ A := by
  have hne : ENNReal.ofReal (1 - θ.extinction) ≠ 0 := by
    simp only [ne_eq, ENNReal.ofReal_eq_zero, not_le]
    linarith
  rw [survivalMeasure_apply, sampleMeasure_survives θ hJN, ← mul_assoc,
    ENNReal.mul_inv_cancel hne ENNReal.ofReal_ne_top, one_mul]

/-! ### The reduced law along an address -/

namespace Offspring

end Offspring

/-- Naming a skeleton vertex is a measurable event. -/
lemma measurableSet_mem_skelTree (u : Word N) :
    MeasurableSet {c : Word N → ℕ | u ∈ skelTree c} :=
  measurable_skelField (measurableSet_mem_sample u)

/-! ### The vertex events of the two laws -/

namespace Offspring

/-- The mass an offspring law puts above `m`: the probability that a vertex has more
than `m` children. -/
noncomputable def tail (θ : Offspring J) (m : ℕ) : ℝ :=
  ∑ k ∈ Finset.range (J + 1), if m < k then θ k else 0

end Offspring

/-- The root factor of the splitting for a tail event: the offspring count at the root
exceeds `m` with probability the tail weight. -/
lemma infinitePi_root_gt (θ : Offspring J) (m : ℕ) :
    Measure.infinitePi (fun _ : Branch N none ↦ θ.law) {u : Branch N none → ℕ | m < u rootIdx}
      = ENNReal.ofReal (θ.tail m) := by
  have hroot : ∀ k : ℕ, MeasurableSet {u : Branch N none → ℕ | u rootIdx = k} := by
    intro k
    exact measurableSet_rootIdx_preimage {k}
  have hgt : MeasurableSet {u : Branch N none → ℕ | m < u rootIdx} := by
    exact measurableSet_rootIdx_preimage {k : ℕ | m < k}
  have hmeas : ∀ k : ℕ, MeasurableSet
      ({u : Branch N none → ℕ | u rootIdx = k} ∩ {u : Branch N none → ℕ | m < u rootIdx}) :=
    fun k ↦ (hroot k).inter hgt
  have hdisj : Pairwise (Function.onFun Disjoint
      fun k : ℕ ↦ ({u : Branch N none → ℕ | u rootIdx = k}
        ∩ {u : Branch N none → ℕ | m < u rootIdx})) := by
    intro k l hkl
    refine Set.disjoint_left.mpr fun u hu hu' ↦ ?_
    exact hkl (hu.1.symm.trans hu'.1)
  have hdecomp : {u : Branch N none → ℕ | m < u rootIdx}
      = ⋃ k : ℕ, ({u : Branch N none → ℕ | u rootIdx = k}
        ∩ {u : Branch N none → ℕ | m < u rootIdx}) := by
    ext u
    simp only [Set.mem_setOf_eq, Set.mem_iUnion, Set.mem_inter_iff]
    exact ⟨fun h ↦ ⟨u rootIdx, rfl, h⟩, fun ⟨_, _, h⟩ ↦ h⟩
  have hval : ∀ k : ℕ, Measure.infinitePi (fun _ : Branch N none ↦ θ.law)
      ({u : Branch N none → ℕ | u rootIdx = k} ∩ {u : Branch N none → ℕ | m < u rootIdx})
      = ENNReal.ofReal (if m < k then θ k else 0) := by
    intro k
    by_cases hk : m < k
    · have hset : ({u : Branch N none → ℕ | u rootIdx = k}
          ∩ {u : Branch N none → ℕ | m < u rootIdx})
          = {u : Branch N none → ℕ | u rootIdx = k} := by
        refine Set.inter_eq_left.mpr fun u hu ↦ ?_
        rw [Set.mem_setOf_eq, show u rootIdx = k from hu]
        exact hk
      rw [hset, infinitePi_root_apply θ k, if_pos hk]
    · have hset : ({u : Branch N none → ℕ | u rootIdx = k}
          ∩ {u : Branch N none → ℕ | m < u rootIdx}) = (∅ : Set (Branch N none → ℕ)) := by
        ext u
        simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
        rintro ⟨hu, hlt⟩
        exact hk (hu ▸ hlt)
      rw [hset, measure_empty, if_neg hk, ENNReal.ofReal_zero]
  have hvanish : ∀ k ∉ Finset.range (J + 1),
      Measure.infinitePi (fun _ : Branch N none ↦ θ.law)
        ({u : Branch N none → ℕ | u rootIdx = k} ∩ {u : Branch N none → ℕ | m < u rootIdx})
        = 0 := by
    intro k hk
    rw [Finset.mem_range] at hk
    rw [hval k]
    by_cases hmk : m < k
    · rw [if_pos hmk, θ.vanishing k (by omega), ENNReal.ofReal_zero]
    · rw [if_neg hmk, ENNReal.ofReal_zero]
  have hnn : ∀ k ∈ Finset.range (J + 1), (0 : ℝ) ≤ if m < k then θ k else 0 := by
    intro k _
    split
    · exact θ.nonneg k
    · exact le_rfl
  rw [hdecomp, measure_iUnion hdisj hmeas, tsum_eq_sum hvanish,
    Finset.sum_congr rfl fun k _ ↦ hval k, ← ENNReal.ofReal_sum_of_nonneg hnn, Offspring.tail]

/-! ### The rank of a surviving child -/

/-- The rank of a letter among a set of letters: the number of elements of `S` strictly
below `i`.  Along the surviving children this is the address the child receives in the
re-addressed skeleton. -/
def rankOf (S : Finset (Fin N)) (i : Fin N) : ℕ := (S.filter (· < i)).card

/-- **The enumeration of `S` in increasing order inverts the rank.** -/
lemma rankOf_orderEmbOfFin (S : Finset (Fin N)) {k : ℕ} (h : S.card = k) (m : Fin k) :
    rankOf S (S.orderEmbOfFin h m) = (m : ℕ) := by
  have himg : S.filter (· < S.orderEmbOfFin h m)
      = (Finset.univ.filter fun m' : Fin k ↦ m' < m).image (S.orderEmbOfFin h) := by
    ext x
    simp only [Finset.mem_filter, Finset.mem_image, Finset.mem_univ, true_and]
    constructor
    · rintro ⟨hxS, hlt⟩
      have hx : x ∈ Set.range (S.orderEmbOfFin h) := by
        rw [Finset.range_orderEmbOfFin]
        exact hxS
      obtain ⟨m', rfl⟩ := hx
      exact ⟨m', (OrderEmbedding.lt_iff_lt _).mp hlt, rfl⟩
    · rintro ⟨m', hm', rfl⟩
      exact ⟨Finset.orderEmbOfFin_mem _ _ _, (OrderEmbedding.lt_iff_lt _).mpr hm'⟩
  have hIio : (Finset.univ.filter fun m' : Fin k ↦ m' < m) = Finset.Iio m := by
    ext m'
    simp
  rw [rankOf, himg, Finset.card_image_of_injective _ (S.orderEmbOfFin h).injective, hIio,
    Fin.card_Iio]

/-- **Reindexing a product over a set of letters by the rank.**  The ranks of the
elements of `S` run through `0,…,|S|-1`. -/
lemma prod_rankOf {M : Type*} [CommMonoid M] (S : Finset (Fin N)) (f : ℕ → M) :
    ∏ i ∈ S, f (rankOf S i) = ∏ m ∈ Finset.range S.card, f m := by
  calc ∏ i ∈ S, f (rankOf S i)
      = ∏ i ∈ Finset.univ.map (S.orderEmbOfFin rfl).toEmbedding, f (rankOf S i) := by
        rw [Finset.map_orderEmbOfFin_univ]
    _ = ∏ m : Fin S.card, f (rankOf S (S.orderEmbOfFin rfl m)) := Finset.prod_map _ _ _
    _ = ∏ m : Fin S.card, f (m : ℕ) :=
        Finset.prod_congr rfl fun m _ ↦ by rw [rankOf_orderEmbOfFin]
    _ = ∏ m ∈ Finset.range S.card, f m := Fin.prod_univ_eq_prod_range _ _

/-- An element of `S` has rank below the cardinality. -/
lemma rankOf_lt_card {S : Finset (Fin N)} {i : Fin N} (hi : i ∈ S) : rankOf S i < S.card := by
  rw [rankOf]
  refine Finset.card_lt_card ⟨Finset.filter_subset _ _, ?_⟩
  intro hsub
  have hmem := hsub hi
  rw [Finset.mem_filter] at hmem
  exact absurd hmem.2 (lt_irrefl i)

/-- The rank enumerates the surviving children: below the skeleton degree the `m`-th
surviving subtree is the shift to the letter of rank `m`. -/
lemma bushOf_rankOf {S : Finset (Fin N)} {i : Fin N} (hi : i ∈ S) (c : Word N → ℕ) :
    bushOf S (rankOf S i) c = fun w ↦ c (i :: w) := by
  have hlt : rankOf S i < S.card := rankOf_lt_card hi
  have hemb : S.orderEmbOfFin rfl ⟨rankOf S i, hlt⟩ = i := by
    have hmem : i ∈ Set.range (S.orderEmbOfFin (rfl : S.card = S.card)) := by
      rw [Finset.range_orderEmbOfFin]
      exact hi
    obtain ⟨m, hm⟩ := hmem
    have hrank : rankOf S i = (m : ℕ) := by
      rw [← hm, rankOf_orderEmbOfFin]
    have hidx : (⟨rankOf S i, hlt⟩ : Fin S.card) = m := Fin.ext hrank
    rw [hidx, hm]
  rw [bushOf, dif_pos hlt, hemb]

/-- **The rank-indexed constraints on the surviving subtrees**, read letter by letter.
Constraining the `m`-th surviving subtree for every `m` below the number of survivors is
constraining the subtree under each surviving letter by the set of its rank. -/
lemma forall_bushOf_iff (S : Finset (Fin N)) (A : ℕ → Set (Word N → ℕ)) (c : Word N → ℕ) :
    (∀ m : ℕ, m < S.card → bushOf S m c ∈ A m)
      ↔ ∀ i ∈ S, (fun w : Word N ↦ c (i :: w)) ∈ A (rankOf S i) := by
  constructor
  · intro h i hi
    have hval := h (rankOf S i) (rankOf_lt_card hi)
    rwa [bushOf_rankOf hi c] at hval
  · intro h m hm
    have hi : S.orderEmbOfFin rfl ⟨m, hm⟩ ∈ S := Finset.orderEmbOfFin_mem _ _ _
    have hrank : rankOf S (S.orderEmbOfFin rfl ⟨m, hm⟩) = m :=
      rankOf_orderEmbOfFin S rfl ⟨m, hm⟩
    have hval := h _ hi
    rw [hrank] at hval
    rw [bushOf, dif_pos hm]
    exact hval

/-! ### Constraining every surviving subtree -/

/-- **The product over the children of a root with `j` children** of a factor that is
`X` of the rank at a surviving child, `B` at a dying one and `1` at a letter naming no
child.  The ranks run through `0,…,|S|-1`. -/
lemma prod_ite_survivors_family {j : ℕ} (hj : j ≤ N) {S : Finset (Fin N)}
    (hS : S ⊆ childSet N j) (X : ℕ → ℝ≥0∞) (B : ℝ≥0∞) :
    ∏ i : Fin N, (if i ∈ S then X (rankOf S i) else if (i : ℕ) < j then B else 1)
      = (∏ m ∈ Finset.range S.card, X m) * B ^ (j - S.card) := by
  classical
  set f : Fin N → ℝ≥0∞ :=
    fun i ↦ if i ∈ S then X (rankOf S i) else if (i : ℕ) < j then B else 1 with hf
  have houter : ∏ i ∈ Finset.univ \ childSet N j, f i = 1 := by
    refine Finset.prod_eq_one fun i hi ↦ ?_
    rw [Finset.mem_sdiff, mem_childSet] at hi
    have hiS : i ∉ S := fun hc ↦ hi.2 (mem_childSet.mp (hS hc))
    rw [hf]
    simp only
    rw [if_neg hiS, if_neg hi.2]
  have hdying : ∏ i ∈ childSet N j \ S, f i = B ^ (j - S.card) := by
    have hfac : ∀ i ∈ childSet N j \ S, f i = B := by
      intro i hi
      rw [Finset.mem_sdiff, mem_childSet] at hi
      rw [hf]
      simp only
      rw [if_neg hi.2, if_pos hi.1]
    rw [Finset.prod_congr rfl hfac, Finset.prod_const, Finset.card_sdiff_of_subset hS,
      card_childSet hj]
  have hsurv : ∏ i ∈ S, f i = ∏ m ∈ Finset.range S.card, X m := by
    have hfac : ∀ i ∈ S, f i = X (rankOf S i) := by
      intro i hi
      rw [hf]
      simp only
      rw [if_pos hi]
    rw [Finset.prod_congr rfl hfac, prod_rankOf]
  rw [← Finset.prod_sdiff (Finset.subset_univ (childSet N j)), houter, one_mul,
    ← Finset.prod_sdiff hS, hdying, hsurv]
  ring

/-- The product event constraining every surviving subtree: the root has `j` children,
those named by `S` found infinite subtrees, the remaining children die, and the subtree
under a surviving letter lies in the set indexed by its rank. -/
def bushesBox (j : ℕ) (S : Finset (Fin N)) (A : ℕ → Set (Word N → ℕ)) :
    (i : Option (Fin N)) → Set (Branch N i → ℕ)
  | none => {u | u rootIdx = j}
  | some i =>
      if i ∈ S then {c : Word N → ℕ | Survives c} ∩ A (rankOf S i)
      else if (i : ℕ) < j then {c : Word N → ℕ | ¬ Survives c} else Set.univ

@[simp] lemma bushesBox_none (j : ℕ) (S : Finset (Fin N)) (A : ℕ → Set (Word N → ℕ)) :
    bushesBox j S A none = {u : Branch N none → ℕ | u rootIdx = j} := rfl

@[simp] lemma bushesBox_some (j : ℕ) (S : Finset (Fin N)) (A : ℕ → Set (Word N → ℕ))
    (i : Fin N) :
    bushesBox j S A (some i)
      = if i ∈ S then {c : Word N → ℕ | Survives c} ∩ A (rankOf S i)
        else if (i : ℕ) < j then {c : Word N → ℕ | ¬ Survives c} else Set.univ := rfl

lemma measurableSet_bushesBox (j : ℕ) (S : Finset (Fin N)) {A : ℕ → Set (Word N → ℕ)}
    (hA : ∀ m, MeasurableSet (A m)) (i : Option (Fin N)) :
    MeasurableSet (bushesBox (N := N) j S A i) := by
  cases i with
  | none =>
      exact measurableSet_rootIdx_preimage {j}
  | some i =>
      rw [bushesBox_some]
      split
      · exact measurableSet_survives.inter (hA _)
      · split
        · exact measurableSet_survives.compl
        · exact MeasurableSet.univ

/-- The extra factors constraining the surviving subtrees, as a product event. -/
def bushesOnly (S : Finset (Fin N)) (A : ℕ → Set (Word N → ℕ)) :
    (i : Option (Fin N)) → Set (Branch N i → ℕ)
  | none => Set.univ
  | some i => if i ∈ S then A (rankOf S i) else Set.univ

/-- The two product events cut out the one constraining every surviving subtree. -/
lemma bushesBox_eq_inter (j : ℕ) (S : Finset (Fin N)) (A : ℕ → Set (Word N → ℕ))
    (i : Option (Fin N)) :
    bushesBox j S A i = skelBox j S i ∩ bushesOnly S A i := by
  cases i with
  | none =>
      ext u
      simp [bushesBox, skelBox, bushesOnly]
  | some i =>
      ext c
      by_cases hi : i ∈ S
      · simp [bushesBox, skelBox, bushesOnly, hi]
      · simp [bushesBox, skelBox, bushesOnly, hi]

/-- The extra factors, read through the splitting. -/
lemma split_preimage_bushesOnly (S : Finset (Fin N)) (A : ℕ → Set (Word N → ℕ)) :
    split ⁻¹' Set.univ.pi (bushesOnly (N := N) S A)
      = {c : Word N → ℕ | ∀ i ∈ S, (fun w : Word N ↦ c (i :: w)) ∈ A (rankOf S i)} := by
  ext c
  simp only [Set.mem_preimage, Set.mem_pi, Set.mem_univ, forall_const, Set.mem_setOf_eq]
  constructor
  · intro h i hi
    have hval := h (some i)
    rw [show bushesOnly (N := N) S A (some i) = if i ∈ S then A (rankOf S i) else Set.univ from rfl,
      if_pos hi] at hval
    exact hval
  · intro h i
    cases i with
    | none => exact Set.mem_univ _
    | some i =>
        show split c (some i) ∈ (if i ∈ S then A (rankOf S i) else Set.univ)
        by_cases hi : i ∈ S
        · rw [if_pos hi]
          exact h i hi
        · rw [if_neg hi]
          exact Set.mem_univ _

/-- **The product event constrains every surviving subtree.** -/
lemma split_preimage_bushesBox {j : ℕ} {S : Finset (Fin N)} (hS : S ⊆ childSet N j)
    (A : ℕ → Set (Word N → ℕ)) :
    split ⁻¹' Set.univ.pi (bushesBox (N := N) j S A)
      = ({c : Word N → ℕ | c [] = j} ∩ {c : Word N → ℕ | survivors c = S})
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < S.card → bushOf S m c ∈ A m} := by
  have hbox : Set.univ.pi (bushesBox (N := N) j S A)
      = Set.univ.pi (skelBox (N := N) j S) ∩ Set.univ.pi (bushesOnly (N := N) S A) := by
    rw [← Set.pi_inter_distrib]
    exact Set.pi_congr rfl fun i _ ↦ bushesBox_eq_inter j S A i
  rw [hbox, Set.preimage_inter, split_preimage_skelBox j S hS, split_preimage_bushesOnly]
  ext c
  simp only [Set.mem_inter_iff, Set.mem_setOf_eq, forall_bushOf_iff S A c]

namespace Offspring

/-- The mass an offspring law puts on the arities at least `n`. -/
noncomputable def tailGe (θ : Offspring J) (n : ℕ) : ℝ :=
  ∑ k ∈ Finset.range (J + 1), if n ≤ k then θ k else 0

/-- No demand at all is the whole mass. -/
@[simp] lemma tailGe_zero (θ : Offspring J) : θ.tailGe 0 = 1 := by
  rw [tailGe, Finset.sum_congr rfl fun k _ ↦ if_pos (Nat.zero_le k)]
  exact θ.total

/-- The two tails agree off zero. -/
lemma tailGe_succ (θ : Offspring J) (m : ℕ) : θ.tailGe (m + 1) = θ.tail m := by
  refine Finset.sum_congr rfl fun k _ ↦ ?_
  exact if_congr Nat.lt_iff_add_one_le.symm rfl rfl

end Offspring

/-! ### The law of all the surviving subtrees -/

/-- Constraining every surviving subtree of a prescribed pattern is a measurable
event. -/
lemma measurableSet_forall_bushOf (S : Finset (Fin N)) {A : ℕ → Set (Word N → ℕ)}
    (hA : ∀ m, MeasurableSet (A m)) :
    MeasurableSet {c : Word N → ℕ | ∀ m : ℕ, m < S.card → bushOf S m c ∈ A m} := by
  have h : {c : Word N → ℕ | ∀ m : ℕ, m < S.card → bushOf S m c ∈ A m}
      = ⋂ m : ℕ, ⋂ _ : m < S.card, (fun c : Word N → ℕ ↦ bushOf S m c) ⁻¹' (A m) := by
    ext c
    simp only [Set.mem_setOf_eq, Set.mem_iInter, Set.mem_preimage]
  rw [h]
  exact MeasurableSet.iInter fun m ↦
    MeasurableSet.iInter fun _ ↦ measurable_bushOf S m (hA m)

/-- Constraining the first `k` surviving subtrees is a measurable event. -/
lemma measurableSet_forall_bushAt (k : ℕ) {A : ℕ → Set (Word N → ℕ)}
    (hA : ∀ m, MeasurableSet (A m)) :
    MeasurableSet {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m} := by
  have h : {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m}
      = ⋂ m : ℕ, ⋂ _ : m < k, (fun c : Word N → ℕ ↦ bushAt c m) ⁻¹' (A m) := by
    ext c
    simp only [Set.mem_setOf_eq, Set.mem_iInter, Set.mem_preimage]
  rw [h]
  exact MeasurableSet.iInter fun m ↦ MeasurableSet.iInter fun _ ↦ measurable_bushAt m (hA m)

/-- **The mass of a survival pattern with every surviving subtree constrained.**  The
splitting makes the subtrees independent, so each contributes the conditioned mass of the
set of its rank and the pattern contributes the mass of
`sampleMeasure_root_survivors`. -/
theorem sampleMeasure_root_survivors_bushes (θ : Offspring J) (hJN : J ≤ N)
    (hq : θ.extinction < 1) {j : ℕ} (hj : j ≤ N) {S : Finset (Fin N)} (hS : S ⊆ childSet N j)
    {A : ℕ → Set (Word N → ℕ)} (hA : ∀ m, MeasurableSet (A m)) :
    sampleMeasure (N := N) θ
        (({c : Word N → ℕ | c [] = j} ∩ {c : Word N → ℕ | survivors c = S})
          ∩ {c : Word N → ℕ | ∀ m : ℕ, m < S.card → bushOf S m c ∈ A m})
      = ENNReal.ofReal (θ j) * ENNReal.ofReal (1 - θ.extinction) ^ S.card
          * ENNReal.ofReal θ.extinction ^ (j - S.card)
          * ∏ m ∈ Finset.range S.card, survivalMeasure θ (A m) := by
  have hprod : ∏ i : Fin N, Measure.infinitePi (fun _ : Branch N (some i) ↦ θ.law)
        (bushesBox (N := N) j S A (some i))
      = ENNReal.ofReal (1 - θ.extinction) ^ S.card
          * ENNReal.ofReal θ.extinction ^ (j - S.card)
          * ∏ m ∈ Finset.range S.card, survivalMeasure θ (A m) := by
    have hfac : ∀ i : Fin N, Measure.infinitePi (fun _ : Branch N (some i) ↦ θ.law)
        (bushesBox (N := N) j S A (some i))
        = (if i ∈ S then
              sampleMeasure (N := N) θ ({c : Word N → ℕ | Survives c} ∩ A (rankOf S i))
            else if (i : ℕ) < j then ENNReal.ofReal θ.extinction else 1) := by
      intro i
      rw [bushesBox_some]
      by_cases hiS : i ∈ S
      · rw [if_pos hiS, if_pos hiS]
        exact infinitePi_branch_some θ i _
      · rw [if_neg hiS, if_neg hiS]
        by_cases hij : (i : ℕ) < j
        · rw [if_pos hij, if_pos hij]
          exact (infinitePi_branch_some θ i _).trans (sampleMeasure_not_survives θ hJN)
        · rw [if_neg hij, if_neg hij]
          exact (infinitePi_branch_some θ i Set.univ).trans measure_univ
    have hsplit : ∀ m ∈ Finset.range S.card,
        sampleMeasure (N := N) θ ({c : Word N → ℕ | Survives c} ∩ A m)
          = ENNReal.ofReal (1 - θ.extinction) * survivalMeasure θ (A m) :=
      fun m _ ↦ sampleMeasure_survives_inter θ hJN hq (A m)
    rw [Finset.prod_congr rfl fun i _ ↦ hfac i,
      prod_ite_survivors_family hj hS
        (fun m ↦ sampleMeasure (N := N) θ ({c : Word N → ℕ | Survives c} ∩ A m))
        (ENNReal.ofReal θ.extinction),
      Finset.prod_congr rfl hsplit, Finset.prod_mul_distrib, Finset.prod_const,
      Finset.card_range]
    ring
  rw [← split_preimage_bushesBox hS A, ← Measure.map_apply measurable_split
      (MeasurableSet.univ_pi (measurableSet_bushesBox j S hA)), map_split, ← Finset.coe_univ,
    Measure.infinitePi_pi _ (fun i _ ↦ measurableSet_bushesBox j S hA i), Fintype.prod_option,
    bushesBox_none, infinitePi_root_apply θ j, hprod]
  ring

/-- **The one-root count with every surviving subtree constrained.** -/
theorem sampleMeasure_root_skeletonDegree_bushes (θ : Offspring J) (hJN : J ≤ N)
    (hq : θ.extinction < 1) {j : ℕ} (hj : j ≤ N) (k : ℕ) {A : ℕ → Set (Word N → ℕ)}
    (hA : ∀ m, MeasurableSet (A m)) :
    sampleMeasure (N := N) θ
        (({c : Word N → ℕ | c [] = j} ∩ {c : Word N → ℕ | skeletonDegree c = k})
          ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})
      = ENNReal.ofReal
          (θ j * (j.choose k : ℝ) * (1 - θ.extinction) ^ k * θ.extinction ^ (j - k))
        * ∏ m ∈ Finset.range k, survivalMeasure θ (A m) := by
  classical
  have h := measure_root_skeletonDegree_eq_sum (sampleMeasure (N := N) θ) j k
    (X := {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})
    (fun S ↦ {c : Word N → ℕ | ∀ m : ℕ, m < S.card → bushOf S m c ∈ A m})
    (fun S ↦ measurableSet_forall_bushOf S hA) (fun c _ hk ↦ by subst hk; exact Iff.rfl)
  beta_reduce at h
  have hterm : ∀ S ∈ (childSet N j).powersetCard k,
      sampleMeasure (N := N) θ
          (({c : Word N → ℕ | c [] = j} ∩ {c : Word N → ℕ | survivors c = S})
            ∩ {c : Word N → ℕ | ∀ m : ℕ, m < S.card → bushOf S m c ∈ A m})
        = ENNReal.ofReal (θ j) * ENNReal.ofReal (1 - θ.extinction) ^ k
            * ENNReal.ofReal θ.extinction ^ (j - k)
            * ∏ m ∈ Finset.range k, survivalMeasure θ (A m) := by
    intro S hSmem
    rw [Finset.mem_powersetCard] at hSmem
    rw [sampleMeasure_root_survivors_bushes θ hJN hq hj hSmem.1 hA, hSmem.2]
  rw [h, Finset.sum_congr rfl hterm, ← Finset.sum_mul, sum_powersetCard_pattern θ hj k]

/-- **The count with every surviving subtree constrained**, summed over the offspring
count at the root. -/
theorem sampleMeasure_skeletonDegree_bushes (θ : Offspring J) (hJN : J ≤ N)
    (hq : θ.extinction < 1) (k : ℕ) {A : ℕ → Set (Word N → ℕ)}
    (hA : ∀ m, MeasurableSet (A m)) :
    sampleMeasure (N := N) θ
        ({c : Word N → ℕ | skeletonDegree c = k}
          ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})
      = ENNReal.ofReal (θ.surviveWeight k) * ∏ m ∈ Finset.range k, survivalMeasure θ (A m) := by
  have hbushmeas : MeasurableSet {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m} :=
    measurableSet_forall_bushAt k hA
  have hmeas : ∀ n : ℕ, MeasurableSet
      ((({c : Word N → ℕ | c [] = n} ∩ {c : Word N → ℕ | skeletonDegree c = k})
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})) :=
    fun n ↦ ((measurableSet_root_eq n).inter (measurableSet_skeletonDegree_eq k)).inter hbushmeas
  have hdisj : Pairwise (Function.onFun Disjoint
      fun n : ℕ ↦ (({c : Word N → ℕ | c [] = n} ∩ {c : Word N → ℕ | skeletonDegree c = k})
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})) := by
    intro n l hnl
    refine Set.disjoint_left.mpr fun c hc hc' ↦ ?_
    exact hnl (hc.1.1.symm.trans hc'.1.1)
  have hdecomp : ({c : Word N → ℕ | skeletonDegree c = k}
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})
      = ⋃ n : ℕ, (({c : Word N → ℕ | c [] = n} ∩ {c : Word N → ℕ | skeletonDegree c = k})
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m}) := by
    ext c
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_iUnion]
    constructor
    · rintro ⟨hk, hbush⟩
      exact ⟨c [], ⟨rfl, hk⟩, hbush⟩
    · rintro ⟨n, ⟨-, hk⟩, hbush⟩
      exact ⟨hk, hbush⟩
  have hvanish : ∀ n ∉ Finset.range (J + 1),
      sampleMeasure (N := N) θ
        ((({c : Word N → ℕ | c [] = n} ∩ {c : Word N → ℕ | skeletonDegree c = k})
          ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})) = 0 := by
    intro n hn
    rw [Finset.mem_range] at hn
    refine nonpos_iff_eq_zero.mp ?_
    calc sampleMeasure (N := N) θ
          ((({c : Word N → ℕ | c [] = n} ∩ {c : Word N → ℕ | skeletonDegree c = k})
            ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m}))
        ≤ sampleMeasure (N := N) θ {c : Word N → ℕ | c [] = n} :=
          measure_mono (Set.Subset.trans Set.inter_subset_left Set.inter_subset_left)
      _ = ENNReal.ofReal (θ n) := sampleMeasure_coord θ [] n
      _ = 0 := by rw [θ.vanishing n (by omega), ENNReal.ofReal_zero]
  have hnn : ∀ n ∈ Finset.range (J + 1),
      (0 : ℝ) ≤ θ n * (n.choose k : ℝ) * (1 - θ.extinction) ^ k * θ.extinction ^ (n - k) := by
    intro n _
    have h1 : (0 : ℝ) ≤ 1 - θ.extinction := by linarith [θ.extinction_le_one]
    exact mul_nonneg (mul_nonneg (mul_nonneg (θ.nonneg n) (Nat.cast_nonneg _))
      (pow_nonneg h1 k)) (pow_nonneg θ.extinction_nonneg _)
  rw [hdecomp, measure_iUnion hdisj hmeas, tsum_eq_sum hvanish, Offspring.surviveWeight,
    ENNReal.ofReal_sum_of_nonneg hnn, Finset.sum_mul]
  refine Finset.sum_congr rfl fun n hn ↦ ?_
  exact sampleMeasure_root_skeletonDegree_bushes θ hJN hq
    (le_trans (Nat.lt_succ_iff.mp (Finset.mem_range.mp hn)) hJN) k hA

/-- **The reduced law at the root with every surviving subtree constrained.**
Conditioned on survival, the root has `k` skeleton children with probability `θ̃_k`, and
the `k` subtrees are independent copies of the conditioned sample. -/
theorem survivalMeasure_skeletonDegree_bushes (θ : Offspring J) (hJN : J ≤ N)
    (hq : θ.extinction < 1) (k : ℕ) {A : ℕ → Set (Word N → ℕ)}
    (hA : ∀ m, MeasurableSet (A m)) :
    survivalMeasure (N := N) θ
        ({c : Word N → ℕ | skeletonDegree c = k}
          ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})
      = ENNReal.ofReal (θ.skeletonWeight k)
          * ∏ m ∈ Finset.range k, survivalMeasure θ (A m) := by
  rcases eq_or_ne k 0 with rfl | hk
  · have hset : ({c : Word N → ℕ | skeletonDegree c = 0}
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < 0 → bushAt c m ∈ A m})
        = {c : Word N → ℕ | skeletonDegree c = 0} := by
      ext c
      simp
    rw [hset, survivalMeasure_skeletonDegree θ hJN hq 0, Finset.range_zero, Finset.prod_empty,
      mul_one]
  · rw [survivalMeasure_apply]
    have hinter : {c : Word N → ℕ | Survives c}
          ∩ ({c : Word N → ℕ | skeletonDegree c = k}
            ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})
        = {c : Word N → ℕ | skeletonDegree c = k}
          ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m} := by
      refine Set.inter_eq_right.mpr fun c hc ↦ ?_
      refine survives_iff_skeletonDegree_ne_zero.mpr ?_
      rw [show skeletonDegree c = k from hc.1]
      exact hk
    rw [hinter, sampleMeasure_skeletonDegree_bushes θ hJN hq k hA, sampleMeasure_survives θ hJN,
      Offspring.skeletonWeight_of_ne_zero θ hk, ENNReal.ofReal_div_of_pos (by linarith),
      ENNReal.div_eq_inv_mul, mul_assoc]

/-- **The branching property of the skeleton with every subtree constrained.**
Conditioned on survival, the root has at least `n` skeleton children with probability
`∑_{k≥n} θ̃_k`, and the subtrees are independent copies of the conditioned sample: the
sets above `n` impose nothing, so only the first `n` factors survive. -/
theorem survivalMeasure_bushes (θ : Offspring J) (hJN : J ≤ N) (hq : θ.extinction < 1)
    (n : ℕ) {A : ℕ → Set (Word N → ℕ)} (hA : ∀ m, MeasurableSet (A m))
    (hAtop : ∀ m : ℕ, n ≤ m → A m = Set.univ) :
    survivalMeasure (N := N) θ
        ({c : Word N → ℕ | n ≤ skeletonDegree c}
          ∩ {c : Word N → ℕ | ∀ m : ℕ, m < skeletonDegree c → bushAt c m ∈ A m})
      = ENNReal.ofReal ((θ.reduced hq).tailGe n)
          * ∏ m ∈ Finset.range n, survivalMeasure θ (A m) := by
  have _ := isProbabilityMeasure_survivalMeasure θ hJN hq
  have hge : MeasurableSet {c : Word N → ℕ | n ≤ skeletonDegree c} :=
    measurable_skeletonDegree MeasurableSet.of_discrete
  have hmeas : ∀ k : ℕ, MeasurableSet
      (({c : Word N → ℕ | n ≤ skeletonDegree c} ∩ {c : Word N → ℕ | skeletonDegree c = k})
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m}) :=
    fun k ↦ (hge.inter (measurableSet_skeletonDegree_eq k)).inter
      (measurableSet_forall_bushAt k hA)
  have hdisj : Pairwise (Function.onFun Disjoint
      fun k : ℕ ↦ (({c : Word N → ℕ | n ≤ skeletonDegree c}
        ∩ {c : Word N → ℕ | skeletonDegree c = k})
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})) := by
    intro k l hkl
    refine Set.disjoint_left.mpr fun c hc hc' ↦ ?_
    exact hkl (hc.1.2.symm.trans hc'.1.2)
  have hdecomp : ({c : Word N → ℕ | n ≤ skeletonDegree c}
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < skeletonDegree c → bushAt c m ∈ A m})
      = ⋃ k : ℕ, (({c : Word N → ℕ | n ≤ skeletonDegree c}
        ∩ {c : Word N → ℕ | skeletonDegree c = k})
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m}) := by
    ext c
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_iUnion]
    constructor
    · rintro ⟨hgec, hbush⟩
      exact ⟨skeletonDegree c, ⟨hgec, rfl⟩, hbush⟩
    · rintro ⟨k, ⟨hgec, hd⟩, hbush⟩
      exact ⟨hgec, fun m hm ↦ hbush m (hd ▸ hm)⟩
  have hunit : ∀ m : ℕ, n ≤ m → survivalMeasure (N := N) θ (A m) = 1 := by
    intro m hm
    rw [hAtop m hm, measure_univ]
  have hprodeq : ∀ k : ℕ, n ≤ k →
      ∏ m ∈ Finset.range k, survivalMeasure (N := N) θ (A m)
        = ∏ m ∈ Finset.range n, survivalMeasure θ (A m) := by
    intro k hk
    refine (Finset.prod_subset (Finset.range_subset_range.mpr hk) fun m hm hmn ↦ ?_).symm
    rw [Finset.mem_range] at hm
    rw [Finset.mem_range, not_lt] at hmn
    exact hunit m hmn
  have hval : ∀ k : ℕ, survivalMeasure (N := N) θ
      (({c : Word N → ℕ | n ≤ skeletonDegree c} ∩ {c : Word N → ℕ | skeletonDegree c = k})
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})
      = ENNReal.ofReal (if n ≤ k then θ.skeletonWeight k else 0)
        * ∏ m ∈ Finset.range n, survivalMeasure θ (A m) := by
    intro k
    by_cases hk : n ≤ k
    · have hset : (({c : Word N → ℕ | n ≤ skeletonDegree c}
          ∩ {c : Word N → ℕ | skeletonDegree c = k})
          ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})
          = {c : Word N → ℕ | skeletonDegree c = k}
            ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m} := by
        ext c
        simp only [Set.mem_inter_iff, Set.mem_setOf_eq]
        constructor
        · rintro ⟨⟨-, hd⟩, hbush⟩
          exact ⟨hd, hbush⟩
        · rintro ⟨hd, hbush⟩
          exact ⟨⟨by rw [hd]; exact hk, hd⟩, hbush⟩
      rw [hset, survivalMeasure_skeletonDegree_bushes θ hJN hq k hA, if_pos hk, hprodeq k hk]
    · have hset : (({c : Word N → ℕ | n ≤ skeletonDegree c}
          ∩ {c : Word N → ℕ | skeletonDegree c = k})
          ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m})
          = (∅ : Set (Word N → ℕ)) := by
        ext c
        simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
        rintro ⟨⟨hgec, hd⟩, -⟩
        exact hk (hd ▸ hgec)
      rw [hset, measure_empty, if_neg hk, ENNReal.ofReal_zero, zero_mul]
  have hvanish : ∀ k ∉ Finset.range (J + 1), survivalMeasure (N := N) θ
      (({c : Word N → ℕ | n ≤ skeletonDegree c} ∩ {c : Word N → ℕ | skeletonDegree c = k})
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < k → bushAt c m ∈ A m}) = 0 := by
    intro k hk
    rw [Finset.mem_range] at hk
    rw [hval k]
    by_cases hnk : n ≤ k
    · rw [if_pos hnk, θ.skeletonWeight_vanishing (by omega), ENNReal.ofReal_zero, zero_mul]
    · rw [if_neg hnk, ENNReal.ofReal_zero, zero_mul]
  have hnn : ∀ k ∈ Finset.range (J + 1),
      (0 : ℝ) ≤ if n ≤ k then θ.skeletonWeight k else 0 := by
    intro k _
    split
    · exact θ.skeletonWeight_nonneg hq k
    · exact le_rfl
  rw [hdecomp, measure_iUnion hdisj hmeas, tsum_eq_sum hvanish,
    Finset.sum_congr rfl fun k _ ↦ hval k, ← Finset.sum_mul, ← ENNReal.ofReal_sum_of_nonneg hnn,
    Offspring.tailGe]
  rfl

/-! ### One surviving subtree, as an instance of the family -/

/-- The family of constraints with `A` at the `m`-th subtree and none elsewhere. -/
private def oneAt (m : ℕ) (A : Set (Word N → ℕ)) (i : ℕ) : Set (Word N → ℕ) :=
  if i = m then A else Set.univ

private lemma oneAt_self (m : ℕ) (A : Set (Word N → ℕ)) : oneAt m A m = A := if_pos rfl

private lemma oneAt_of_ne {m i : ℕ} (hi : i ≠ m) (A : Set (Word N → ℕ)) :
    oneAt m A i = Set.univ := if_neg hi

private lemma measurableSet_oneAt (m : ℕ) {A : Set (Word N → ℕ)} (hA : MeasurableSet A)
    (i : ℕ) : MeasurableSet (oneAt m A i) := by
  rcases eq_or_ne i m with rfl | hi
  · rw [oneAt_self]
    exact hA
  · rw [oneAt_of_ne hi]
    exact MeasurableSet.univ

/-- Constraining the family at every index below `n` constrains the `m`-th subtree
alone. -/
private lemma forall_oneAt_iff {m n : ℕ} (hm : m < n) (A : Set (Word N → ℕ))
    (f : ℕ → Word N → ℕ) :
    (∀ i : ℕ, i < n → f i ∈ oneAt m A i) ↔ f m ∈ A := by
  constructor
  · intro h
    have h' := h m hm
    rwa [oneAt_self] at h'
  · intro h i _
    rcases eq_or_ne i m with rfl | hi
    · rw [oneAt_self]
      exact h
    · rw [oneAt_of_ne hi]
      exact Set.mem_univ _

/-- The product of the conditioned masses over the family is the mass of the one
constraint. -/
private lemma prod_oneAt (θ : Offspring J) (hJN : J ≤ N) (hq : θ.extinction < 1)
    {m n : ℕ} (hm : m < n) (A : Set (Word N → ℕ)) :
    ∏ i ∈ Finset.range n, survivalMeasure (N := N) θ (oneAt m A i) = survivalMeasure θ A := by
  have _ := isProbabilityMeasure_survivalMeasure θ hJN hq
  rw [Finset.prod_eq_single m (fun i _ hi ↦ by rw [oneAt_of_ne hi, measure_univ])
    (fun h ↦ absurd (Finset.mem_range.mpr hm) h), oneAt_self]

/-- The tail of the skeleton law is the tail of the reduced law, shifted by one. -/
private lemma skeletonTail_eq_tailGe (θ : Offspring J) (hq : θ.extinction < 1) (m : ℕ) :
    θ.skeletonTail m = (θ.reduced hq).tailGe (m + 1) := by
  refine Finset.sum_congr rfl fun k _ ↦ ?_
  exact if_congr Nat.lt_iff_add_one_le rfl rfl

/-- **The mass of a survival pattern with one subtree constrained.**  The root has `j`
children of which exactly those named by `S` survive, and the `m`-th of the survivors
lies in `A`. -/
theorem sampleMeasure_root_survivors_bush (θ : Offspring J) (hJN : J ≤ N)
    (hq : θ.extinction < 1) {j : ℕ} (hj : j ≤ N) {S : Finset (Fin N)} (hS : S ⊆ childSet N j)
    {m : ℕ} (hm : m < S.card) {A : Set (Word N → ℕ)} (hA : MeasurableSet A) :
    sampleMeasure (N := N) θ
        (({c : Word N → ℕ | c [] = j} ∩ {c : Word N → ℕ | survivors c = S})
          ∩ {c : Word N → ℕ | bushOf S m c ∈ A})
      = ENNReal.ofReal (θ j) * ENNReal.ofReal (1 - θ.extinction) ^ S.card
          * ENNReal.ofReal θ.extinction ^ (j - S.card) * survivalMeasure θ A := by
  have hset : {c : Word N → ℕ | bushOf S m c ∈ A}
      = {c : Word N → ℕ | ∀ i : ℕ, i < S.card → bushOf S i c ∈ oneAt m A i} := by
    ext c
    exact (forall_oneAt_iff hm A (fun i ↦ bushOf S i c)).symm
  rw [hset, sampleMeasure_root_survivors_bushes θ hJN hq hj hS (measurableSet_oneAt m hA),
    prod_oneAt θ hJN hq hm A]

/-- **The count with one subtree constrained**: the root has `j` children of which `k`
survive and the `m`-th surviving subtree lies in `A`. -/
theorem sampleMeasure_root_skeletonDegree_bush (θ : Offspring J) (hJN : J ≤ N)
    (hq : θ.extinction < 1) {j : ℕ} (hj : j ≤ N) {m k : ℕ} (hm : m < k)
    {A : Set (Word N → ℕ)} (hA : MeasurableSet A) :
    sampleMeasure (N := N) θ
        (({c : Word N → ℕ | c [] = j} ∩ {c : Word N → ℕ | skeletonDegree c = k})
          ∩ {c : Word N → ℕ | bushAt c m ∈ A})
      = ENNReal.ofReal
          (θ j * (j.choose k : ℝ) * (1 - θ.extinction) ^ k * θ.extinction ^ (j - k))
        * survivalMeasure θ A := by
  have hset : {c : Word N → ℕ | bushAt c m ∈ A}
      = {c : Word N → ℕ | ∀ i : ℕ, i < k → bushAt c i ∈ oneAt m A i} := by
    ext c
    exact (forall_oneAt_iff hm A (bushAt c)).symm
  rw [hset, sampleMeasure_root_skeletonDegree_bushes θ hJN hq hj k (measurableSet_oneAt m hA),
    prod_oneAt θ hJN hq hm A]

/-- **The count with one subtree constrained**, summed over the offspring count at the
root: the root has `k` surviving children and the `m`-th of them lies in `A` with
probability `θ̂_k` times the conditioned mass of `A`. -/
theorem sampleMeasure_skeletonDegree_bush (θ : Offspring J) (hJN : J ≤ N)
    (hq : θ.extinction < 1) {m k : ℕ} (hm : m < k) {A : Set (Word N → ℕ)}
    (hA : MeasurableSet A) :
    sampleMeasure (N := N) θ
        ({c : Word N → ℕ | skeletonDegree c = k} ∩ {c : Word N → ℕ | bushAt c m ∈ A})
      = ENNReal.ofReal (θ.surviveWeight k) * survivalMeasure θ A := by
  have hset : {c : Word N → ℕ | bushAt c m ∈ A}
      = {c : Word N → ℕ | ∀ i : ℕ, i < k → bushAt c i ∈ oneAt m A i} := by
    ext c
    exact (forall_oneAt_iff hm A (bushAt c)).symm
  rw [hset, sampleMeasure_skeletonDegree_bushes θ hJN hq k (measurableSet_oneAt m hA),
    prod_oneAt θ hJN hq hm A]

/-- **The branching property of the skeleton, one subtree at a time**: conditioned on
survival, the root has `k` skeleton children with probability `θ̃_k`, and the `m`-th of
them is an independent copy of the conditioned law. -/
theorem survivalMeasure_skeletonDegree_bush (θ : Offspring J) (hJN : J ≤ N)
    (hq : θ.extinction < 1) {m k : ℕ} (hm : m < k) {A : Set (Word N → ℕ)}
    (hA : MeasurableSet A) :
    survivalMeasure (N := N) θ
        ({c : Word N → ℕ | skeletonDegree c = k} ∩ {c : Word N → ℕ | bushAt c m ∈ A})
      = ENNReal.ofReal (θ.skeletonWeight k) * survivalMeasure θ A := by
  have hset : {c : Word N → ℕ | bushAt c m ∈ A}
      = {c : Word N → ℕ | ∀ i : ℕ, i < k → bushAt c i ∈ oneAt m A i} := by
    ext c
    exact (forall_oneAt_iff hm A (bushAt c)).symm
  rw [hset, survivalMeasure_skeletonDegree_bushes θ hJN hq k (measurableSet_oneAt m hA),
    prod_oneAt θ hJN hq hm A]

/-- **The `m`-th surviving subtree**, summed over the skeleton degree: conditioned on
survival, the root has more than `m` skeleton children with probability the skeleton
tail, and the `m`-th of them is an independent copy of the conditioned law. -/
theorem survivalMeasure_bushAt (θ : Offspring J) (hJN : J ≤ N) (hq : θ.extinction < 1)
    (m : ℕ) {A : Set (Word N → ℕ)} (hA : MeasurableSet A) :
    survivalMeasure (N := N) θ
        ({c : Word N → ℕ | m < skeletonDegree c} ∩ {c : Word N → ℕ | bushAt c m ∈ A})
      = ENNReal.ofReal (θ.skeletonTail m) * survivalMeasure θ A := by
  have hset : ({c : Word N → ℕ | m < skeletonDegree c} ∩ {c : Word N → ℕ | bushAt c m ∈ A})
      = ({c : Word N → ℕ | m + 1 ≤ skeletonDegree c}
          ∩ {c : Word N → ℕ | ∀ i : ℕ, i < skeletonDegree c → bushAt c i ∈ oneAt m A i}) := by
    ext c
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq]
    constructor
    · rintro ⟨hlt, hA'⟩
      exact ⟨hlt, (forall_oneAt_iff hlt A (bushAt c)).mpr hA'⟩
    · rintro ⟨hle, h⟩
      exact ⟨hle, (forall_oneAt_iff hle A (bushAt c)).mp h⟩
  rw [hset, survivalMeasure_bushes θ hJN hq (m + 1) (measurableSet_oneAt m hA)
      (fun i hi ↦ oneAt_of_ne (by omega) A),
    prod_oneAt θ hJN hq (Nat.lt_succ_self m) A, skeletonTail_eq_tailGe θ hq m]

/-! ### Finite prefix-closed sets of words -/

/-- A set of words is prefix-closed when it contains every prefix of each of its
elements.  These are the sets a subtree can contain, and the events `{T | F ⊆ T}` they
name are the π-system the two laws are compared on. -/
def PrefixClosed (F : Set (Word N)) : Prop := ∀ ⦃v⦄, v ∈ F → ∀ ⦃u⦄, u <+: v → u ∈ F

/-- The residual set at the letter of index `m`: the words `u` with the `m`-th letter
prepended lying in `F`.  Empty once `m` names no letter. -/
def wordSub (F : Set (Word N)) (m : ℕ) : Set (Word N) :=
  {u : Word N | ∃ i : Fin N, (i : ℕ) = m ∧ i :: u ∈ F}

/-- The residual set at an actual letter. -/
lemma mem_wordSub {F : Set (Word N)} {i : Fin N} {u : Word N} :
    u ∈ wordSub F (i : ℕ) ↔ i :: u ∈ F := by
  constructor
  · rintro ⟨i', hi', hmem⟩
    rwa [Fin.ext hi'] at hmem
  · intro h
    exact ⟨i, rfl, h⟩

/-- Residual sets inherit prefix closure. -/
lemma PrefixClosed.wordSub {F : Set (Word N)} (hF : PrefixClosed F) (m : ℕ) :
    PrefixClosed (BranchingProcess.wordSub F m) := by
  rintro u ⟨i, hi, hmem⟩ u' hu'
  exact ⟨i, hi, hF hmem (List.cons_prefix_cons.mpr ⟨rfl, hu'⟩)⟩

/-- Residual sets are one generation shorter. -/
lemma length_le_of_mem_wordSub {F : Set (Word N)} {n m : ℕ} (hn : ∀ v ∈ F, v.length ≤ n + 1)
    {u : Word N} (hu : u ∈ wordSub F m) : u.length ≤ n := by
  obtain ⟨i, -, hmem⟩ := hu
  have h := hn _ hmem
  simp only [List.length_cons] at h
  omega

open scoped Classical in
/-- The offspring count a prefix-closed set demands at the root: one more than the
largest letter it uses there. -/
noncomputable def rootDeg (F : Set (Word N)) : ℕ :=
  (Finset.univ.filter fun i : Fin N ↦ [i] ∈ F).sup fun i ↦ (i : ℕ) + 1

/-- A letter used at the root lies below the demanded count. -/
lemma lt_rootDeg {F : Set (Word N)} {i : Fin N} (hi : [i] ∈ F) : (i : ℕ) < rootDeg F := by
  classical
  exact Finset.le_sup (f := fun i : Fin N ↦ (i : ℕ) + 1) (Finset.mem_filter.mpr ⟨Finset.mem_univ i, hi⟩)

/-- The demanded count is what makes every letter used at the root available. -/
lemma rootDeg_le_iff {F : Set (Word N)} {k : ℕ} :
    rootDeg F ≤ k ↔ ∀ i : Fin N, [i] ∈ F → (i : ℕ) < k := by
  classical
  rw [rootDeg, Finset.sup_le_iff]
  constructor
  · intro h i hi
    exact h i (Finset.mem_filter.mpr ⟨Finset.mem_univ i, hi⟩)
  · intro h i hi
    exact h i (Finset.mem_filter.mp hi).2

/-- The alphabet carries the demand at the root. -/
lemma rootDeg_le_card (F : Set (Word N)) : rootDeg F ≤ N := by
  classical
  refine Finset.sup_le fun i _ ↦ ?_
  exact i.2

/-- Above the demanded count the residual sets are empty. -/
lemma wordSub_eq_empty {F : Set (Word N)} (hF : PrefixClosed F) {m : ℕ} (hm : rootDeg F ≤ m) :
    wordSub F m = (∅ : Set (Word N)) := by
  ext u
  simp only [Set.mem_empty_iff_false, iff_false]
  rintro ⟨i, hi, hmem⟩
  have hroot : [i] ∈ F := hF hmem (List.cons_prefix_cons.mpr ⟨rfl, List.nil_prefix⟩)
  have := lt_rootDeg hroot
  omega

/-- **The one-step criterion for containment in the skeleton.** -/
lemma subset_skelTree_iff {F : Set (Word N)} (hF : PrefixClosed F) (c : Word N → ℕ) :
    F ⊆ (skelTree c : Set (Word N)) ↔ rootDeg F ≤ skeletonDegree c
      ∧ ∀ m : ℕ, m < skeletonDegree c →
          wordSub F m ⊆ (skelTree (bushAt c m) : Set (Word N)) := by
  constructor
  · intro h
    refine ⟨rootDeg_le_iff.mpr fun i hi ↦ (mem_skelTree_cons.mp (h hi)).1, ?_⟩
    rintro m - u ⟨i, rfl, hmem⟩
    exact (mem_skelTree_cons.mp (h hmem)).2
  · rintro ⟨hdeg, hsub⟩ v hv
    cases v with
    | nil => exact nil_mem_skelTree c
    | cons i u =>
        have hroot : [i] ∈ F := hF hv (List.cons_prefix_cons.mpr ⟨rfl, List.nil_prefix⟩)
        have hlt : (i : ℕ) < skeletonDegree c := lt_of_lt_of_le (lt_rootDeg hroot) hdeg
        exact mem_skelTree_cons.mpr ⟨hlt, hsub (i : ℕ) hlt (mem_wordSub.mpr hv)⟩

/-- **The one-step criterion for containment in a sample.** -/
lemma subset_sample_iff {F : Set (Word N)} (hF : PrefixClosed F) (c : Word N → ℕ) :
    F ⊆ (sample c : Set (Word N)) ↔ rootDeg F ≤ c []
      ∧ ∀ i : Fin N, wordSub F (i : ℕ) ⊆ (sample (fun w : Word N ↦ c (i :: w)) : Set (Word N)) := by
  constructor
  · intro h
    constructor
    · refine rootDeg_le_iff.mpr fun i hi ↦ ?_
      exact singleton_mem_sample_iff.mp (h hi)
    · intro i u hu
      have hmem : i :: u ∈ (sample c : Set (Word N)) := h (mem_wordSub.mp hu)
      have hsplit : (([i] : Word N) ++ u) ∈ sample c := hmem
      exact ((append_mem_sample_iff c [i] u).mp hsplit).2
  · rintro ⟨hdeg, hsub⟩ v hv
    cases v with
    | nil => exact nil_mem_sample c
    | cons i u =>
        have hroot : [i] ∈ F := hF hv (List.cons_prefix_cons.mpr ⟨rfl, List.nil_prefix⟩)
        have hlt : (i : ℕ) < c [] := lt_of_lt_of_le (lt_rootDeg hroot) hdeg
        show (([i] : Word N) ++ u) ∈ sample c
        exact (append_mem_sample_iff c [i] u).mpr
          ⟨singleton_mem_sample_iff.mpr hlt, hsub i (mem_wordSub.mpr hv)⟩

/-- Containment in the skeleton is a measurable event: a countable intersection of the
address events, `Word N` being countable. -/
lemma measurableSet_subset_skelTree (G : Set (Word N)) :
    MeasurableSet {c : Word N → ℕ | G ⊆ (skelTree c : Set (Word N))} := by
  have h : {c : Word N → ℕ | G ⊆ (skelTree c : Set (Word N))}
      = ⋂ v ∈ G, {c : Word N → ℕ | v ∈ skelTree c} := by
    ext c
    simp only [Set.mem_setOf_eq, Set.mem_iInter, Set.subset_def, SetLike.mem_coe]
  rw [h]
  exact MeasurableSet.biInter (Set.to_countable G) fun v _ ↦ measurableSet_mem_skelTree v

/-- Containment in the sample is a measurable event. -/
lemma measurableSet_subset_sample (G : Set (Word N)) :
    MeasurableSet {c : Word N → ℕ | G ⊆ (sample c : Set (Word N))} := by
  have h : {c : Word N → ℕ | G ⊆ (sample c : Set (Word N))}
      = ⋂ v ∈ G, {c : Word N → ℕ | v ∈ sample c} := by
    ext c
    simp only [Set.mem_setOf_eq, Set.mem_iInter, Set.subset_def, SetLike.mem_coe]
  rw [h]
  exact MeasurableSet.biInter (Set.to_countable G) fun v _ ↦ measurableSet_mem_sample v

/-- Containment is a measurable event on subtrees. -/
lemma measurableSet_subset_subtree (G : Set (Word N)) :
    MeasurableSet {T : Subtree N | G ⊆ (T : Set (Word N))} := by
  have h : {T : Subtree N | G ⊆ (T : Set (Word N))} = ⋂ v ∈ G, {T : Subtree N | v ∈ T} := by
    ext T
    simp only [Set.mem_setOf_eq, Set.mem_iInter, Set.subset_def, SetLike.mem_coe]
  rw [h]
  exact MeasurableSet.biInter (Set.to_countable G) fun v _ ↦ measurableSet_mem_subtree v

/-! ### The two recursions -/

/-- The root factor of the splitting for a demand at the root. -/
lemma infinitePi_root_ge (θ : Offspring J) (n : ℕ) :
    Measure.infinitePi (fun _ : Branch N none ↦ θ.law) {u : Branch N none → ℕ | n ≤ u rootIdx}
      = ENNReal.ofReal (θ.tailGe n) := by
  cases n with
  | zero =>
      have hset : {u : Branch N none → ℕ | 0 ≤ u rootIdx} = Set.univ := by
        ext u
        simp
      rw [hset, measure_univ, Offspring.tailGe_zero, ENNReal.ofReal_one]
  | succ m =>
      have hset : {u : Branch N none → ℕ | m + 1 ≤ u rootIdx}
          = {u : Branch N none → ℕ | m < u rootIdx} := by
        ext u
        simp only [Set.mem_setOf_eq]
        omega
      rw [hset, infinitePi_root_gt θ m, Offspring.tailGe_succ]

/-- The product event for containment: the root has enough children and each subtree
contains the corresponding residual set. -/
def subsetBox (F : Set (Word N)) : (i : Option (Fin N)) → Set (Branch N i → ℕ)
  | none => {u : Branch N none → ℕ | rootDeg F ≤ u rootIdx}
  | some i => {d : Word N → ℕ | wordSub F (i : ℕ) ⊆ (sample d : Set (Word N))}

lemma measurableSet_subsetBox (F : Set (Word N)) (i : Option (Fin N)) :
    MeasurableSet (subsetBox (N := N) F i) := by
  cases i with
  | none =>
      exact measurableSet_rootIdx_preimage {k : ℕ | rootDeg F ≤ k}
  | some i => exact measurableSet_subset_sample (wordSub F (i : ℕ))

/-- **The product event is containment.** -/
lemma split_preimage_subsetBox {F : Set (Word N)} (hF : PrefixClosed F) :
    split ⁻¹' Set.univ.pi (subsetBox (N := N) F)
      = {c : Word N → ℕ | F ⊆ (sample c : Set (Word N))} := by
  ext c
  rw [Set.mem_preimage, Set.mem_setOf_eq, subset_sample_iff hF]
  simp only [Set.mem_pi, Set.mem_univ, forall_const]
  constructor
  · intro h
    exact ⟨h none, fun i ↦ h (some i)⟩
  · rintro ⟨hroot, hsub⟩ i
    cases i with
    | none => exact hroot
    | some i => exact hsub i

/-- **The recursion for a sample.**  The root must carry the demand of `F`, and the
subtrees must carry the residual sets, independently. -/
theorem sampleMeasure_subset_sample_step (θ : Offspring J) {F : Set (Word N)}
    (hF : PrefixClosed F) :
    sampleMeasure (N := N) θ {c : Word N → ℕ | F ⊆ (sample c : Set (Word N))}
      = ENNReal.ofReal (θ.tailGe (rootDeg F))
        * ∏ i : Fin N, sampleMeasure (N := N) θ
            {d : Word N → ℕ | wordSub F (i : ℕ) ⊆ (sample d : Set (Word N))} := by
  rw [← split_preimage_subsetBox hF, ← Measure.map_apply measurable_split
      (MeasurableSet.univ_pi (measurableSet_subsetBox F)), map_split, ← Finset.coe_univ,
    Measure.infinitePi_pi _ (fun i _ ↦ measurableSet_subsetBox F i), Fintype.prod_option,
    show subsetBox (N := N) F none = {u : Branch N none → ℕ | rootDeg F ≤ u rootIdx} from rfl,
    infinitePi_root_ge θ (rootDeg F)]
  congr 1

/-- **The recursion for the skeleton.**  Conditioned on survival, the root must have
enough skeleton children to carry the demand of `F`, and the surviving subtrees must carry
the residual sets, independently. -/
theorem survivalMeasure_subset_skelTree_step (θ : Offspring J) (hJN : J ≤ N)
    (hq : θ.extinction < 1) {F : Set (Word N)} (hF : PrefixClosed F) :
    survivalMeasure (N := N) θ {c : Word N → ℕ | F ⊆ (skelTree c : Set (Word N))}
      = ENNReal.ofReal ((θ.reduced hq).tailGe (rootDeg F))
        * ∏ m ∈ Finset.range (rootDeg F), survivalMeasure (N := N) θ
            {d : Word N → ℕ | wordSub F m ⊆ (skelTree d : Set (Word N))} := by
  have hA : ∀ m : ℕ,
      MeasurableSet {d : Word N → ℕ | wordSub F m ⊆ (skelTree d : Set (Word N))} :=
    fun m ↦ measurableSet_subset_skelTree (wordSub F m)
  have hAtop : ∀ m : ℕ, rootDeg F ≤ m →
      {d : Word N → ℕ | wordSub F m ⊆ (skelTree d : Set (Word N))} = Set.univ := by
    intro m hm
    rw [wordSub_eq_empty hF hm]
    ext d
    simp
  have hset : {c : Word N → ℕ | F ⊆ (skelTree c : Set (Word N))}
      = {c : Word N → ℕ | rootDeg F ≤ skeletonDegree c}
        ∩ {c : Word N → ℕ | ∀ m : ℕ, m < skeletonDegree c →
            bushAt c m ∈ {d : Word N → ℕ | wordSub F m ⊆ (skelTree d : Set (Word N))}} := by
    ext c
    rw [Set.mem_setOf_eq, subset_skelTree_iff hF c]
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq]
  rw [hset, survivalMeasure_bushes θ hJN hq (rootDeg F) hA hAtop]

/-! ### The pushforward -/

/-- **The skeleton is a Galton-Watson tree with the reduced law, on every finite
prefix-closed set of words.**  Both sides satisfy the same recursion, the skeleton one by
`survivalMeasure_subset_skelTree_step` and the sample one by
`sampleMeasure_subset_sample_step`, so the induction on the height of `F` closes. -/
theorem survivalMeasure_subset_skelTree (θ : Offspring J) (hJN : J ≤ N)
    (hq : θ.extinction < 1) :
    ∀ (n : ℕ) (F : Set (Word N)), PrefixClosed F → (∀ v ∈ F, v.length ≤ n) →
      survivalMeasure (N := N) θ {c : Word N → ℕ | F ⊆ (skelTree c : Set (Word N))}
        = sampleMeasure (N := N) (θ.reduced hq)
            {c : Word N → ℕ | F ⊆ (sample c : Set (Word N))} := by
  have _ := isProbabilityMeasure_survivalMeasure θ hJN hq
  intro n
  induction n with
  | zero =>
      intro F _ hn
      have hnil : ∀ v ∈ F, v = ([] : Word N) := by
        intro v hv
        exact List.length_eq_zero_iff.mp (Nat.le_zero.mp (hn v hv))
      have h1 : {c : Word N → ℕ | F ⊆ (skelTree c : Set (Word N))} = Set.univ := by
        ext c
        simp only [Set.mem_setOf_eq, Set.mem_univ, iff_true]
        intro v hv
        rw [hnil v hv]
        exact nil_mem_skelTree c
      have h2 : {c : Word N → ℕ | F ⊆ (sample c : Set (Word N))} = Set.univ := by
        ext c
        simp only [Set.mem_setOf_eq, Set.mem_univ, iff_true]
        intro v hv
        rw [hnil v hv]
        exact nil_mem_sample c
      rw [h1, h2, measure_univ, measure_univ]
  | succ n ih =>
      intro F hF hn
      have hterm : ∀ m : ℕ,
          survivalMeasure (N := N) θ
              {d : Word N → ℕ | wordSub F m ⊆ (skelTree d : Set (Word N))}
            = sampleMeasure (N := N) (θ.reduced hq)
              {d : Word N → ℕ | wordSub F m ⊆ (sample d : Set (Word N))} :=
        fun m ↦ ih (wordSub F m) (hF.wordSub m) fun u hu ↦ length_le_of_mem_wordSub hn hu
      have hunit : ∀ m : ℕ, rootDeg F ≤ m →
          sampleMeasure (N := N) (θ.reduced hq)
            {d : Word N → ℕ | wordSub F m ⊆ (sample d : Set (Word N))} = 1 := by
        intro m hm
        rw [wordSub_eq_empty hF hm]
        have hset : {d : Word N → ℕ | (∅ : Set (Word N)) ⊆ (sample d : Set (Word N))}
            = Set.univ := by
          ext d
          simp
        rw [hset, measure_univ]
      rw [survivalMeasure_subset_skelTree_step θ hJN hq hF,
        sampleMeasure_subset_sample_step (θ.reduced hq) hF,
        Finset.prod_congr rfl fun m _ ↦ hterm m]
      congr 1
      rw [Fin.prod_univ_eq_prod_range (fun m ↦ sampleMeasure (N := N) (θ.reduced hq)
        {d : Word N → ℕ | wordSub F m ⊆ (sample d : Set (Word N))}) N]
      refine Finset.prod_subset (Finset.range_subset_range.mpr (rootDeg_le_card F)) ?_
      intro m _ hmn
      rw [Finset.mem_range, not_lt] at hmn
      exact hunit m hmn

/-- The set of prefixes of a word is finite. -/
lemma finite_prefixes (v : Word N) : {u : Word N | u <+: v}.Finite := by
  have h : {u : Word N | u <+: v} ⊆ (fun i ↦ v.take i) '' Set.Iic v.length := by
    intro u hu
    exact ⟨u.length, hu.length_le, (List.prefix_iff_eq_take.mp hu).symm⟩
  exact Set.Finite.subset ((Set.finite_Iic _).image _) h

/-- The set of prefixes of a word is prefix-closed. -/
lemma prefixClosed_prefixes (v : Word N) : PrefixClosed {u : Word N | u <+: v} :=
  fun _ hu _ hw ↦ hw.trans hu

/-- A vertex event is a containment event, subtrees being prefix-closed. -/
lemma mem_subtree_eq_subset (v : Word N) :
    {T : Subtree N | v ∈ T} = {T : Subtree N | {u : Word N | u <+: v} ⊆ (T : Set (Word N))} := by
  ext T
  simp only [Set.mem_setOf_eq]
  constructor
  · intro hv u hu
    exact Subtree.mem_of_prefix hu hv
  · intro h
    exact h (List.prefix_refl v)

/-- The containment events of the finite prefix-closed sets of words. -/
def containmentSets (N : ℕ) : Set (Set (Subtree N)) :=
  {s | ∃ F : Set (Word N), F.Finite ∧ PrefixClosed F ∧
    s = {T : Subtree N | F ⊆ (T : Set (Word N))}}

/-- **The containment events form a π-system**: the union of two finite prefix-closed
sets of words is finite and prefix-closed. -/
lemma isPiSystem_containmentSets : IsPiSystem (containmentSets N) := by
  rintro _ ⟨F, hFfin, hF, rfl⟩ _ ⟨G, hGfin, hG, rfl⟩ -
  refine ⟨F ∪ G, hFfin.union hGfin, ?_, ?_⟩
  · rintro v (hv | hv) u hu
    · exact Or.inl (hF hv hu)
    · exact Or.inr (hG hv hu)
  · ext T
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.union_subset_iff]

/-- **The containment events generate the measurable structure on subtrees.** -/
lemma generateFrom_containmentSets :
    (Subtree.instMeasurableSpace : MeasurableSpace (Subtree N))
      = MeasurableSpace.generateFrom (containmentSets N) := by
  refine le_antisymm ?_ ?_
  · refine MeasurableSpace.generateFrom_le ?_
    rintro _ ⟨v, rfl⟩
    rw [mem_subtree_eq_subset v]
    exact MeasurableSpace.measurableSet_generateFrom
      ⟨{u : Word N | u <+: v}, finite_prefixes v, prefixClosed_prefixes v, rfl⟩
  · refine MeasurableSpace.generateFrom_le ?_
    rintro _ ⟨F, -, -, rfl⟩
    exact measurableSet_subset_subtree F

/-- **The Harris recursion, `thm:harris`\labelcref{it:harris-skeleton} in full.**
Conditioned on survival, the re-addressed skeleton of the sample is a Galton-Watson tree
with the reduced law `eq:hs-transform`.  The containment events of the finite
prefix-closed sets of words form a π-system generating the measurable structure on
subtrees, and the two laws agree on it. -/
theorem skeletonTreeLaw_eq_treeLaw (θ : Offspring J) (hJN : J ≤ N) (hq : θ.extinction < 1) :
    skeletonTreeLaw (N := N) θ = treeLaw (N := N) (θ.reduced hq) := by
  have _ := isProbabilityMeasure_survivalMeasure θ hJN hq
  have hprob : IsProbabilityMeasure (skeletonTreeLaw (N := N) θ) := by
    rw [skeletonTreeLaw]
    exact Measure.isProbabilityMeasure_map measurable_skelTree.aemeasurable
  refine ext_of_generate_finite (containmentSets N) generateFrom_containmentSets
    isPiSystem_containmentSets ?_ ?_
  · rintro _ ⟨F, hFfin, hF, rfl⟩
    obtain ⟨n, hn⟩ : ∃ n : ℕ, ∀ v ∈ F, v.length ≤ n := by
      obtain ⟨n, hn⟩ := (hFfin.image fun v : Word N ↦ v.length).bddAbove
      exact ⟨n, fun v hv ↦ hn ⟨v, hv, rfl⟩⟩
    rw [skeletonTreeLaw, Measure.map_apply measurable_skelTree (measurableSet_subset_subtree F),
      treeLaw, Measure.map_apply measurable_sample (measurableSet_subset_subtree F)]
    exact survivalMeasure_subset_skelTree θ hJN hq n F hF hn
  · rw [measure_univ, measure_univ]

/-! ### The conjugate law of the bushes -/

namespace Offspring

variable (θ : Offspring J)

/-- **The conjugate law** `thm:harris`\labelcref{it:harris-bushes}: the offspring law
tilted by the extinction probability, `θ_j q^j / q`.  This is the law a subtree
conditioned to die branches with. -/
noncomputable def conjugateWeight (j : ℕ) : ℝ := θ j * θ.extinction ^ j / θ.extinction

lemma conjugateWeight_nonneg (j : ℕ) : 0 ≤ θ.conjugateWeight j :=
  div_nonneg (mul_nonneg (θ.nonneg j) (pow_nonneg θ.extinction_nonneg j)) θ.extinction_nonneg

lemma conjugateWeight_vanishing {j : ℕ} (hj : J < j) : θ.conjugateWeight j = 0 := by
  rw [conjugateWeight, θ.vanishing j hj, zero_mul, zero_div]

/-- **The conjugate weights sum to one**: the generating function is at its fixed point,
so the tilt is exactly normalised. -/
lemma sum_conjugateWeight (hq0 : 0 < θ.extinction) :
    ∑ j ∈ Finset.range (J + 1), θ.conjugateWeight j = 1 := by
  simp only [conjugateWeight]
  rw [show (∑ j ∈ Finset.range (J + 1), θ j * θ.extinction ^ j / θ.extinction)
      = (∑ j ∈ Finset.range (J + 1), θ j * θ.extinction ^ j) / θ.extinction from
    (Finset.sum_div _ _ _).symm]
  rw [show (∑ j ∈ Finset.range (J + 1), θ j * θ.extinction ^ j) = gen θ θ.extinction from rfl,
    θ.gen_extinction, div_self hq0.ne']

/-- **The conjugate law** as an offspring law in its own right, of the same support
bound `J`.  This is the law a bush branches with. -/
noncomputable def conjugate (hq0 : 0 < θ.extinction) : Offspring J where
  mass := θ.conjugateWeight
  nonneg := θ.conjugateWeight_nonneg
  vanishing := fun _ hj ↦ θ.conjugateWeight_vanishing hj
  total := θ.sum_conjugateWeight hq0

@[simp] lemma conjugate_apply (hq0 : 0 < θ.extinction) (j : ℕ) :
    θ.conjugate hq0 j = θ.conjugateWeight j := rfl

end Offspring

/-! ### The law of a bush -/

/-- The conditioning event has positive mass exactly for `q > 0`. -/
lemma sampleMeasure_notSurvives_ne_zero (θ : Offspring J) (hJN : J ≤ N)
    (hq0 : 0 < θ.extinction) :
    sampleMeasure (N := N) θ {c : Word N → ℕ | ¬ Survives c} ≠ 0 := by
  rw [sampleMeasure_not_survives θ hJN]
  simp only [ne_eq, ENNReal.ofReal_eq_zero, not_le]
  exact hq0

/-- **The bush law is a probability measure** once the tree dies with positive
probability. -/
theorem isProbabilityMeasure_bushMeasure (θ : Offspring J) (hJN : J ≤ N)
    (hq0 : 0 < θ.extinction) : IsProbabilityMeasure (bushMeasure (N := N) θ) :=
  ProbabilityTheory.cond_isProbabilityMeasure (sampleMeasure_notSurvives_ne_zero θ hJN hq0)

/-- The bush law, unfolded. -/
theorem bushMeasure_apply (θ : Offspring J) (t : Set (Word N → ℕ)) :
    bushMeasure (N := N) θ t
      = (sampleMeasure (N := N) θ {c : Word N → ℕ | ¬ Survives c})⁻¹
        * sampleMeasure (N := N) θ ({c : Word N → ℕ | ¬ Survives c} ∩ t) :=
  ProbabilityTheory.cond_apply measurableSet_survives.compl _ t

/-- The mass of the extinction event splits off the bush law. -/
lemma sampleMeasure_notSurvives_inter (θ : Offspring J) (hJN : J ≤ N) (hq0 : 0 < θ.extinction)
    (A : Set (Word N → ℕ)) :
    sampleMeasure (N := N) θ ({c : Word N → ℕ | ¬ Survives c} ∩ A)
      = ENNReal.ofReal θ.extinction * bushMeasure θ A := by
  have hne : ENNReal.ofReal θ.extinction ≠ 0 := by
    simp only [ne_eq, ENNReal.ofReal_eq_zero, not_le]
    exact hq0
  rw [bushMeasure_apply, sampleMeasure_not_survives θ hJN, ← mul_assoc,
    ENNReal.mul_inv_cancel hne ENNReal.ofReal_ne_top, one_mul]

/-- **The law of the bush of a sample conditioned to die.** -/
noncomputable def bushTreeLaw (θ : Offspring J) : Measure (Subtree N) :=
  (bushMeasure θ).map sample

/-! ### Constraining every dying subtree -/

/-- The rank of a letter among all letters is the letter itself. -/
lemma rankOf_univ (i : Fin N) : rankOf Finset.univ i = (i : ℕ) := by
  have h : (Finset.univ.filter fun i' : Fin N ↦ i' < i) = Finset.Iio i := by
    ext i'
    simp
  rw [rankOf, h, Fin.card_Iio]

/-- **The product over the children of a root with `j` children** when the letters
naming no child contribute nothing. -/
lemma prod_ite_childSet {M : Type*} [CommMonoid M] {j : ℕ} (X Y : Fin N → M)
    (hY : ∀ i : Fin N, ¬ (i : ℕ) < j → Y i = 1) :
    ∏ i : Fin N, (if (i : ℕ) < j then X i else Y i) = ∏ i ∈ childSet N j, X i := by
  classical
  have houter : ∏ i ∈ Finset.univ \ childSet N j,
      (if (i : ℕ) < j then X i else Y i) = 1 := by
    refine Finset.prod_eq_one fun i hi ↦ ?_
    rw [Finset.mem_sdiff, mem_childSet] at hi
    rw [if_neg hi.2]
    exact hY i hi.2
  have hinner : ∏ i ∈ childSet N j, (if (i : ℕ) < j then X i else Y i)
      = ∏ i ∈ childSet N j, X i :=
    Finset.prod_congr rfl fun i hi ↦ if_pos (mem_childSet.mp hi)
  rw [← Finset.prod_sdiff (Finset.subset_univ (childSet N j)), houter, hinner, one_mul]

/-- Reindexing a product over the letters naming a child by the number they name. -/
lemma prod_childSet {M : Type*} [CommMonoid M] {j : ℕ} (hj : j ≤ N) (f : ℕ → M) :
    ∏ i ∈ childSet N j, f (i : ℕ) = ∏ m ∈ Finset.range j, f m := by
  classical
  have himg : Finset.image (Fin.val) (childSet N j) = Finset.range j := by
    ext m
    simp only [Finset.mem_image, mem_childSet, Finset.mem_range]
    constructor
    · rintro ⟨i, hi, rfl⟩
      exact hi
    · intro hm
      exact ⟨⟨m, by omega⟩, hm, rfl⟩
  rw [← himg, Finset.prod_image fun a _ c _ h ↦ Fin.val_injective h]

/-- The product event constraining every dying subtree: the root has `j` children, all
of them die, and the subtree under a letter lies in the set indexed by that letter. -/
def dyingBox (j : ℕ) (A : ℕ → Set (Word N → ℕ)) :
    (i : Option (Fin N)) → Set (Branch N i → ℕ)
  | none => {u | u rootIdx = j}
  | some i =>
      (if (i : ℕ) < j then {c : Word N → ℕ | ¬ Survives c} else Set.univ) ∩ A (i : ℕ)

@[simp] lemma dyingBox_none (j : ℕ) (A : ℕ → Set (Word N → ℕ)) :
    dyingBox j A none = {u : Branch N none → ℕ | u rootIdx = j} := rfl

@[simp] lemma dyingBox_some (j : ℕ) (A : ℕ → Set (Word N → ℕ)) (i : Fin N) :
    dyingBox j A (some i)
      = (if (i : ℕ) < j then {c : Word N → ℕ | ¬ Survives c} else Set.univ) ∩ A (i : ℕ) := rfl

lemma measurableSet_dyingBox (j : ℕ) {A : ℕ → Set (Word N → ℕ)}
    (hA : ∀ m, MeasurableSet (A m)) (i : Option (Fin N)) :
    MeasurableSet (dyingBox (N := N) j A i) := by
  cases i with
  | none =>
      exact measurableSet_rootIdx_preimage {j}
  | some i =>
      rw [dyingBox_some]
      refine MeasurableSet.inter ?_ (hA _)
      split
      · exact measurableSet_survives.compl
      · exact MeasurableSet.univ

/-- The dying box splits into the empty survival pattern and the constraints. -/
lemma dyingBox_eq_inter (j : ℕ) (A : ℕ → Set (Word N → ℕ)) (i : Option (Fin N)) :
    dyingBox j A i = skelBox j ∅ i ∩ bushesOnly Finset.univ A i := by
  cases i with
  | none =>
      ext u
      simp [dyingBox, skelBox, bushesOnly]
  | some i =>
      ext c
      simp [dyingBox, skelBox, bushesOnly, rankOf_univ]

/-- **The product event constrains every dying subtree.** -/
lemma split_preimage_dyingBox (j : ℕ) (A : ℕ → Set (Word N → ℕ)) :
    split ⁻¹' Set.univ.pi (dyingBox (N := N) j A)
      = ({c : Word N → ℕ | c [] = j} ∩ {c : Word N → ℕ | survivors c = ∅})
        ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)} := by
  have hbox : Set.univ.pi (dyingBox (N := N) j A)
      = Set.univ.pi (skelBox (N := N) j ∅) ∩ Set.univ.pi (bushesOnly (N := N) Finset.univ A) := by
    rw [← Set.pi_inter_distrib]
    exact Set.pi_congr rfl fun i _ ↦ dyingBox_eq_inter j A i
  rw [hbox, Set.preimage_inter, split_preimage_skelBox j ∅ (Finset.empty_subset _),
    split_preimage_bushesOnly]
  ext c
  simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Finset.mem_univ, forall_const, rankOf_univ]

/-- **The mass of a dying root with every subtree constrained.**  The root has `j`
children, all of the subtrees die, and each lies in the set indexed by its letter: the
splitting makes them independent bushes. -/
theorem sampleMeasure_root_dying (θ : Offspring J) (hJN : J ≤ N) (hq0 : 0 < θ.extinction)
    {n j : ℕ} (hj : j ≤ N) (hnj : n ≤ j) {A : ℕ → Set (Word N → ℕ)}
    (hA : ∀ m, MeasurableSet (A m)) (hAtop : ∀ m : ℕ, n ≤ m → A m = Set.univ) :
    sampleMeasure (N := N) θ
        (({c : Word N → ℕ | c [] = j} ∩ {c : Word N → ℕ | survivors c = ∅})
          ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)})
      = ENNReal.ofReal (θ j) * ENNReal.ofReal θ.extinction ^ j
          * ∏ m ∈ Finset.range n, bushMeasure θ (A m) := by
  have _ := isProbabilityMeasure_bushMeasure θ hJN hq0
  have hprod : ∏ i : Fin N, Measure.infinitePi (fun _ : Branch N (some i) ↦ θ.law)
        (dyingBox (N := N) j A (some i))
      = ENNReal.ofReal θ.extinction ^ j * ∏ m ∈ Finset.range n, bushMeasure θ (A m) := by
    have hfac : ∀ i : Fin N, Measure.infinitePi (fun _ : Branch N (some i) ↦ θ.law)
        (dyingBox (N := N) j A (some i))
        = if (i : ℕ) < j then
            ENNReal.ofReal θ.extinction * bushMeasure (N := N) θ (A (i : ℕ)) else 1 := by
      intro i
      rw [dyingBox_some]
      by_cases hij : (i : ℕ) < j
      · rw [if_pos hij, if_pos hij]
        exact (infinitePi_branch_some θ i _).trans
          (sampleMeasure_notSurvives_inter θ hJN hq0 (A (i : ℕ)))
      · rw [if_neg hij, if_neg hij, Set.univ_inter, hAtop (i : ℕ) (by omega)]
        exact (infinitePi_branch_some θ i Set.univ).trans measure_univ
    rw [Finset.prod_congr rfl fun i _ ↦ hfac i,
      prod_ite_childSet
        (fun i : Fin N ↦ ENNReal.ofReal θ.extinction * bushMeasure (N := N) θ (A (i : ℕ)))
        (fun _ ↦ 1) (fun _ _ ↦ rfl),
      Finset.prod_mul_distrib, Finset.prod_const, card_childSet hj,
      prod_childSet hj fun m ↦ bushMeasure (N := N) θ (A m)]
    congr 1
    refine (Finset.prod_subset (Finset.range_subset_range.mpr hnj) ?_).symm
    intro m _ hmn
    rw [Finset.mem_range, not_lt] at hmn
    rw [hAtop m hmn, measure_univ]
  rw [← split_preimage_dyingBox j A, ← Measure.map_apply measurable_split
      (MeasurableSet.univ_pi (measurableSet_dyingBox j hA)), map_split, ← Finset.coe_univ,
    Measure.infinitePi_pi _ (fun i _ ↦ measurableSet_dyingBox j hA i), Fintype.prod_option,
    dyingBox_none, infinitePi_root_apply θ j, hprod]
  ring

/-- **The branching property of the bushes**, `thm:harris`\labelcref{it:harris-bushes}.
Conditioned on extinction, the root has at least `n` children with probability
`∑_{j≥n} θ̂_j`, and the subtrees are independent bushes: the sets above `n` impose
nothing, so only the first `n` factors survive. -/
theorem bushMeasure_dying (θ : Offspring J) (hJN : J ≤ N) (hq0 : 0 < θ.extinction) (n : ℕ)
    {A : ℕ → Set (Word N → ℕ)} (hA : ∀ m, MeasurableSet (A m))
    (hAtop : ∀ m : ℕ, n ≤ m → A m = Set.univ) :
    bushMeasure (N := N) θ
        ({c : Word N → ℕ | n ≤ c []}
          ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)})
      = ENNReal.ofReal ((θ.conjugate hq0).tailGe n)
          * ∏ m ∈ Finset.range n, bushMeasure θ (A m) := by
  have _ := isProbabilityMeasure_bushMeasure θ hJN hq0
  have hqne : ENNReal.ofReal θ.extinction ≠ 0 := by
    simp only [ne_eq, ENNReal.ofReal_eq_zero, not_le]
    exact hq0
  have hconstr : MeasurableSet
      {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)} := by
    have h : {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)}
        = ⋂ i : Fin N, (fun c : Word N → ℕ ↦ fun w : Word N ↦ c (i :: w)) ⁻¹' (A (i : ℕ)) := by
      ext c
      simp only [Set.mem_setOf_eq, Set.mem_iInter, Set.mem_preimage]
    rw [h]
    exact MeasurableSet.iInter fun i ↦ measurable_shift i (hA _)
  have hge : MeasurableSet {c : Word N → ℕ | n ≤ c []} := by
    have h : {c : Word N → ℕ | n ≤ c []} = (fun c : Word N → ℕ ↦ c []) ⁻¹' {k : ℕ | n ≤ k} := rfl
    rw [h]
    exact measurable_pi_apply ([] : Word N) MeasurableSet.of_discrete
  have hmeas : ∀ j : ℕ, MeasurableSet
      (({c : Word N → ℕ | n ≤ c []} ∩ {c : Word N → ℕ | c [] = j})
        ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)}) :=
    fun j ↦ (hge.inter (measurableSet_root_eq j)).inter hconstr
  have hdisj : Pairwise (Function.onFun Disjoint
      fun j : ℕ ↦ (({c : Word N → ℕ | n ≤ c []} ∩ {c : Word N → ℕ | c [] = j})
        ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)})) := by
    intro j l hjl
    refine Set.disjoint_left.mpr fun c hc hc' ↦ ?_
    exact hjl (hc.1.2.symm.trans hc'.1.2)
  have hdecomp : ({c : Word N → ℕ | n ≤ c []}
        ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)})
      = ⋃ j : ℕ, (({c : Word N → ℕ | n ≤ c []} ∩ {c : Word N → ℕ | c [] = j})
        ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)}) := by
    ext c
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_iUnion]
    constructor
    · rintro ⟨hgec, hconst⟩
      exact ⟨c [], ⟨hgec, rfl⟩, hconst⟩
    · rintro ⟨j, ⟨hgec, -⟩, hconst⟩
      exact ⟨hgec, hconst⟩
  have hval : ∀ j : ℕ, j ≤ N → bushMeasure (N := N) θ
      (({c : Word N → ℕ | n ≤ c []} ∩ {c : Word N → ℕ | c [] = j})
        ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)})
      = ENNReal.ofReal (if n ≤ j then θ.conjugateWeight j else 0)
        * ∏ m ∈ Finset.range n, bushMeasure θ (A m) := by
    intro j hjN
    by_cases hnj : n ≤ j
    · rw [bushMeasure_apply, sampleMeasure_not_survives θ hJN]
      have hset : {c : Word N → ℕ | ¬ Survives c}
            ∩ (({c : Word N → ℕ | n ≤ c []} ∩ {c : Word N → ℕ | c [] = j})
              ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)})
          = ({c : Word N → ℕ | c [] = j} ∩ {c : Word N → ℕ | survivors c = ∅})
            ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)} := by
        ext c
        simp only [Set.mem_inter_iff, Set.mem_setOf_eq, not_survives_iff_survivors_eq_empty]
        constructor
        · rintro ⟨hdead, ⟨-, hroot⟩, hconst⟩
          exact ⟨⟨hroot, hdead⟩, hconst⟩
        · rintro ⟨⟨hroot, hdead⟩, hconst⟩
          exact ⟨hdead, ⟨by rw [hroot]; exact hnj, hroot⟩, hconst⟩
      rw [hset, sampleMeasure_root_dying θ hJN hq0 hjN hnj hA hAtop, if_pos hnj,
        Offspring.conjugateWeight, ENNReal.ofReal_div_of_pos hq0,
        ENNReal.ofReal_mul (θ.nonneg j), ENNReal.ofReal_pow θ.extinction_nonneg,
        ENNReal.div_eq_inv_mul]
      ring
    · have hset : (({c : Word N → ℕ | n ≤ c []} ∩ {c : Word N → ℕ | c [] = j})
          ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)})
          = (∅ : Set (Word N → ℕ)) := by
        ext c
        simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
        rintro ⟨⟨hgec, hroot⟩, -⟩
        exact hnj (hroot ▸ hgec)
      rw [hset, measure_empty, if_neg hnj, ENNReal.ofReal_zero, zero_mul]
  have hvanish : ∀ j ∉ Finset.range (J + 1), bushMeasure (N := N) θ
      (({c : Word N → ℕ | n ≤ c []} ∩ {c : Word N → ℕ | c [] = j})
        ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)}) = 0 := by
    intro j hj
    rw [Finset.mem_range] at hj
    have hzero : sampleMeasure (N := N) θ
        ({c : Word N → ℕ | ¬ Survives c}
          ∩ (({c : Word N → ℕ | n ≤ c []} ∩ {c : Word N → ℕ | c [] = j})
            ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)})) = 0 := by
      refine nonpos_iff_eq_zero.mp ?_
      calc sampleMeasure (N := N) θ
            ({c : Word N → ℕ | ¬ Survives c}
              ∩ (({c : Word N → ℕ | n ≤ c []} ∩ {c : Word N → ℕ | c [] = j})
                ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w)) ∈ A (i : ℕ)}))
          ≤ sampleMeasure (N := N) θ {c : Word N → ℕ | c [] = j} :=
            measure_mono fun c hc ↦ hc.2.1.2
        _ = ENNReal.ofReal (θ j) := sampleMeasure_coord θ [] j
        _ = 0 := by rw [θ.vanishing j (by omega), ENNReal.ofReal_zero]
    rw [bushMeasure_apply, hzero, mul_zero]
  have hnn : ∀ j ∈ Finset.range (J + 1),
      (0 : ℝ) ≤ if n ≤ j then θ.conjugateWeight j else 0 := by
    intro j _
    split
    · exact θ.conjugateWeight_nonneg j
    · exact le_rfl
  rw [hdecomp, measure_iUnion hdisj hmeas, tsum_eq_sum hvanish,
    Finset.sum_congr rfl fun j hj ↦
      hval j (le_trans (Nat.lt_succ_iff.mp (Finset.mem_range.mp hj)) hJN),
    ← Finset.sum_mul, ← ENNReal.ofReal_sum_of_nonneg hnn, Offspring.tailGe]
  rfl

/-- **The recursion for a bush.**  Conditioned on extinction, the root must carry the
demand of `F`, and the dying subtrees must carry the residual sets, independently. -/
theorem bushMeasure_subset_sample_step (θ : Offspring J) (hJN : J ≤ N)
    (hq0 : 0 < θ.extinction) {F : Set (Word N)} (hF : PrefixClosed F) :
    bushMeasure (N := N) θ {c : Word N → ℕ | F ⊆ (sample c : Set (Word N))}
      = ENNReal.ofReal ((θ.conjugate hq0).tailGe (rootDeg F))
        * ∏ m ∈ Finset.range (rootDeg F), bushMeasure (N := N) θ
            {d : Word N → ℕ | wordSub F m ⊆ (sample d : Set (Word N))} := by
  have hA : ∀ m : ℕ,
      MeasurableSet {d : Word N → ℕ | wordSub F m ⊆ (sample d : Set (Word N))} :=
    fun m ↦ measurableSet_subset_sample (wordSub F m)
  have hAtop : ∀ m : ℕ, rootDeg F ≤ m →
      {d : Word N → ℕ | wordSub F m ⊆ (sample d : Set (Word N))} = Set.univ := by
    intro m hm
    rw [wordSub_eq_empty hF hm]
    ext d
    simp
  have hset : {c : Word N → ℕ | F ⊆ (sample c : Set (Word N))}
      = {c : Word N → ℕ | rootDeg F ≤ c []}
        ∩ {c : Word N → ℕ | ∀ i : Fin N, (fun w : Word N ↦ c (i :: w))
            ∈ {d : Word N → ℕ | wordSub F (i : ℕ) ⊆ (sample d : Set (Word N))}} := by
    ext c
    rw [Set.mem_setOf_eq, subset_sample_iff hF c]
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq]
  rw [hset, bushMeasure_dying θ hJN hq0 (rootDeg F) hA hAtop]

/-- **The bushes are Galton-Watson trees with the conjugate law, on every finite
prefix-closed set of words.** -/
theorem bushMeasure_subset_sample (θ : Offspring J) (hJN : J ≤ N) (hq0 : 0 < θ.extinction) :
    ∀ (n : ℕ) (F : Set (Word N)), PrefixClosed F → (∀ v ∈ F, v.length ≤ n) →
      bushMeasure (N := N) θ {c : Word N → ℕ | F ⊆ (sample c : Set (Word N))}
        = sampleMeasure (N := N) (θ.conjugate hq0)
            {c : Word N → ℕ | F ⊆ (sample c : Set (Word N))} := by
  have _ := isProbabilityMeasure_bushMeasure θ hJN hq0
  intro n
  induction n with
  | zero =>
      intro F _ hn
      have hnil : ∀ v ∈ F, v = ([] : Word N) := by
        intro v hv
        exact List.length_eq_zero_iff.mp (Nat.le_zero.mp (hn v hv))
      have h1 : {c : Word N → ℕ | F ⊆ (sample c : Set (Word N))} = Set.univ := by
        ext c
        simp only [Set.mem_setOf_eq, Set.mem_univ, iff_true]
        intro v hv
        rw [hnil v hv]
        exact nil_mem_sample c
      rw [h1, measure_univ, measure_univ]
  | succ n ih =>
      intro F hF hn
      have hterm : ∀ m : ℕ,
          bushMeasure (N := N) θ
              {d : Word N → ℕ | wordSub F m ⊆ (sample d : Set (Word N))}
            = sampleMeasure (N := N) (θ.conjugate hq0)
              {d : Word N → ℕ | wordSub F m ⊆ (sample d : Set (Word N))} :=
        fun m ↦ ih (wordSub F m) (hF.wordSub m) fun u hu ↦ length_le_of_mem_wordSub hn hu
      have hunit : ∀ m : ℕ, rootDeg F ≤ m →
          sampleMeasure (N := N) (θ.conjugate hq0)
            {d : Word N → ℕ | wordSub F m ⊆ (sample d : Set (Word N))} = 1 := by
        intro m hm
        rw [wordSub_eq_empty hF hm]
        have hset : {d : Word N → ℕ | (∅ : Set (Word N)) ⊆ (sample d : Set (Word N))}
            = Set.univ := by
          ext d
          simp
        rw [hset, measure_univ]
      rw [bushMeasure_subset_sample_step θ hJN hq0 hF,
        sampleMeasure_subset_sample_step (θ.conjugate hq0) hF,
        Finset.prod_congr rfl fun m _ ↦ hterm m]
      congr 1
      rw [Fin.prod_univ_eq_prod_range (fun m ↦ sampleMeasure (N := N) (θ.conjugate hq0)
        {d : Word N → ℕ | wordSub F m ⊆ (sample d : Set (Word N))}) N]
      refine Finset.prod_subset (Finset.range_subset_range.mpr (rootDeg_le_card F)) ?_
      intro m _ hmn
      rw [Finset.mem_range, not_lt] at hmn
      exact hunit m hmn

/-- **The bushes are Galton-Watson trees with the conjugate law**,
`thm:harris`\labelcref{it:harris-bushes} in full: conditioned on extinction, the sample
is a Galton-Watson tree with the conjugate law `θ_j q^j / q`.  Together with
`skeletonTreeLaw_eq_treeLaw` this is the Harris decomposition: the skeleton branches with
the reduced law, and what hangs off it branches with the conjugate law. -/
theorem bushTreeLaw_eq_treeLaw (θ : Offspring J) (hJN : J ≤ N) (hq0 : 0 < θ.extinction) :
    bushTreeLaw (N := N) θ = treeLaw (N := N) (θ.conjugate hq0) := by
  have _ := isProbabilityMeasure_bushMeasure θ hJN hq0
  have hprob : IsProbabilityMeasure (bushTreeLaw (N := N) θ) := by
    rw [bushTreeLaw]
    exact Measure.isProbabilityMeasure_map measurable_sample.aemeasurable
  refine ext_of_generate_finite (containmentSets N) generateFrom_containmentSets
    isPiSystem_containmentSets ?_ ?_
  · rintro _ ⟨F, hFfin, hF, rfl⟩
    obtain ⟨n, hn⟩ : ∃ n : ℕ, ∀ v ∈ F, v.length ≤ n := by
      obtain ⟨n, hn⟩ := (hFfin.image fun v : Word N ↦ v.length).bddAbove
      exact ⟨n, fun v hv ↦ hn ⟨v, hv, rfl⟩⟩
    rw [bushTreeLaw, Measure.map_apply measurable_sample (measurableSet_subset_subtree F),
      treeLaw, Measure.map_apply measurable_sample (measurableSet_subset_subtree F)]
    exact bushMeasure_subset_sample θ hJN hq0 n F hF hn
  · rw [measure_univ, measure_univ]

end BranchingProcess
