/-
The per-state one-step bound of the abstract Markov pipeline: for a
compatible pair of root states `(s,t)` and any uniform ceiling `Γ` on the
frozen-pattern square potentials at height `n`,

    Φ_{n+1}(s,t) ≤ η(s,t) + Γ + 2α · η(s,t) · Γ,

where `η(s,t) = Φ_α(P s → P t; R₀^{(2)})` is the kernel mismatch potential.
The chain: the root factor is exact (compatible frozen roots cost nothing),
the bad degree against the column mixture decomposes over the kernel with
mismatch patterns failing certainly, the mixture split factors off the
mismatch mass, and countable Jensen reduces the conditional part to the
frozen-pattern potentials, which `Γ` bounds uniformly.

The four-law directed contraction, which discharges `Γ` in terms of the
directed potential family at height `n`, is certified in
`FourLaw/Assembly.lean` and is consumed here only through the hypothesis
`hΓ`.  For the varying-offspring process the budgets `η(s,t)` are infinite
(see `Archive/CaretObstruction.lean`); its proof runs the exact
factorisation of `Process/Contraction.lean` instead.
-/
import GraphMarkovMatching.Process.TreePotential
import GraphMarkovMatching.Potential.Split

namespace GraphMarkovMatching

open GraphMarkovMatching.Support
open scoped ENNReal Classical

universe u
variable {S : Type u}

/-! ### Root patterns and the height-zero potential -/

variable (α : ℝ) (P : S → PMF (S × S)) (R₀ : S → S → Prop)

/-- The root pattern of a pair of labellings. -/
def rootPat (n : ℕ) (xp : FullLab S n × FullLab S n) : S × S :=
  (rootLab n xp.1, rootLab n xp.2)

/-- At height `0` a compatible pair has zero potential: all potential is
generated by the kernel. -/
lemma PhiM_zero {s t : S} (hst : R₀ s t) : PhiM α P R₀ s t 0 = 0 := by
  rw [PhiM, PhiD, muM_zero, muM_zero, tsum_pure_mul]
  have hq : q (PMF.pure (leaf t)) (fullSim R₀ 0) (leaf s) = 0 := by
    rw [q, qE_pure]
    have h : badInd (fullSim R₀ 0) (leaf s) (leaf t) = 0 := by
      rw [badInd, if_pos ((fullSim_leaf R₀ s t).mpr hst)]
    rw [h, ENNReal.toReal_zero]
  rw [hq, phiE_zero]

/-! ### The bad degree along the recursion -/

/-- The mixture form of the pair-level bad degree. -/
lemma qE_pairMix (n : ℕ) (t : S) (xp : FullLab S n × FullLab S n) :
    qE (pairMix P t n) (SquareRel (fullSim R₀ n)) xp
      = ∑' τ, (P t) τ
          * qE (prodPMF (muM P τ.1 n) (muM P τ.2 n)) (SquareRel (fullSim R₀ n)) xp :=
  qE_bind (P t) _ _ xp

/-- **Mismatch patterns fail certainly**: if the root patterns are not
square-compatible, the frozen-pattern bad degree is one. -/
lemma qE_eq_one_of_mismatch (n : ℕ) (τ : S × S) (xp : FullLab S n × FullLab S n)
    (hmis : ¬ SquareRel R₀ (rootPat n xp) τ) :
    qE (prodPMF (muM P τ.1 n) (muM P τ.2 n)) (SquareRel (fullSim R₀ n)) xp = 1 := by
  have hr : rE (prodPMF (muM P τ.1 n) (muM P τ.2 n)) (SquareRel (fullSim R₀ n)) xp = 0 := by
    rw [rE]
    refine ENNReal.tsum_eq_zero.mpr fun yp => ?_
    by_cases h : SquareRel (fullSim R₀ n) xp yp
    · rw [if_pos h]
      by_contra hc
      rw [prodPMF_apply] at hc
      obtain ⟨h1, h2⟩ := mul_ne_zero_iff.mp hc
      have e1 : rootLab n yp.1 = τ.1 := rootLab_of_ne_zero P n τ.1 yp.1 h1
      have e2 : rootLab n yp.2 = τ.2 := rootLab_of_ne_zero P n τ.2 yp.2 h2
      have hroot := squareRel_root R₀ n xp yp h
      rw [e1, e2] at hroot
      exact hmis hroot
    · rw [if_neg h]
  have := rE_add_qE (prodPMF (muM P τ.1 n) (muM P τ.2 n)) (SquareRel (fullSim R₀ n)) xp
  rw [hr, zero_add] at this
  exact this

/-! ### The pointwise split-and-Jensen bound -/

/-- The tilted kernel weights over compatible patterns. -/
noncomputable def tiltW (t : S) (σp : S × S) (τ : S × S) : ℝ≥0∞ :=
  (if SquareRel R₀ σp τ then (P t) τ else 0) * (rE (P t) (SquareRel R₀) σp)⁻¹

/-- The conditional part `J`: tilted mixture of frozen-pattern safe weights. -/
noncomputable def Jmix (t : S) (σp : S × S) (n : ℕ)
    (xp : FullLab S n × FullLab S n) : ℝ≥0∞ :=
  ∑' τ, tiltW P R₀ t σp τ
    * phiE α (q (prodPMF (muM P τ.1 n) (muM P τ.2 n)) (SquareRel (fullSim R₀ n)) xp)

/-- **The pointwise bound**: for every subtree pair `xp`, with `σp` its root
pattern,

    φ_α(q̄(xp)) ≤ φ_α(e_σ) + J(xp) + 2α · φ_α(e_σ) · J(xp),

where `e_σ` is the kernel mismatch degree of the pattern and `J` the tilted
conditional mixture. -/
lemma phiE_pairMix_le {α : ℝ} (hα : 1 ≤ α) (t : S) (n : ℕ)
    (xp : FullLab S n × FullLab S n) :
    phiE α (q (pairMix P t n) (SquareRel (fullSim R₀ n)) xp)
      ≤ phiE α (q (P t) (SquareRel R₀) (rootPat n xp))
        + Jmix α P R₀ t (rootPat n xp) n xp
        + ENNReal.ofReal (2 * α)
          * (phiE α (q (P t) (SquareRel R₀) (rootPat n xp))
              * Jmix α P R₀ t (rootPat n xp) n xp) := by
  set σp : S × S := rootPat n xp with hσp
  set Dr : ℝ≥0∞ := rE (P t) (SquareRel R₀) σp with hDr
  set E : ℝ≥0∞ := qE (P t) (SquareRel R₀) σp with hE
  by_cases hD : Dr = 0
  · -- total mismatch: the first summand is already `⊤`
    have hE1 : E = 1 := by
      have h := rE_add_qE (P t) (SquareRel R₀) σp
      rw [← hDr, ← hE, hD, zero_add] at h
      exact h
    have htop : phiE α (q (P t) (SquareRel R₀) σp) = ⊤ := by
      rw [q, ← hE, hE1, ENNReal.toReal_one, phiE_one]
    rw [htop]
    have : (⊤ : ℝ≥0∞) + Jmix α P R₀ t σp n xp
        + ENNReal.ofReal (2 * α) * (⊤ * Jmix α P R₀ t σp n xp) = ⊤ := by
      simp
    rw [this]
    exact le_top
  · -- the tilted weights form a probability vector
    have hD_top : Dr ≠ ⊤ := ne_top_of_le_ne_top ENNReal.one_ne_top rE_le_one
    have hw_sum : ∑' τ, tiltW P R₀ t σp τ = 1 := by
      calc ∑' τ, tiltW P R₀ t σp τ
          = ∑' τ, (if SquareRel R₀ σp τ then (P t) τ else 0) * Dr⁻¹ :=
            tsum_congr fun τ => rfl
        _ = (∑' τ, if SquareRel R₀ σp τ then (P t) τ else 0) * Dr⁻¹ :=
            ENNReal.tsum_mul_right
        _ = Dr * Dr⁻¹ := by
            rw [show (∑' τ, if SquareRel R₀ σp τ then (P t) τ else 0) = Dr from rfl]
        _ = 1 := ENNReal.mul_inv_cancel hD hD_top
    -- the frozen-pattern degrees
    set Q : S × S → ℝ :=
      fun τ => q (prodPMF (muM P τ.1 n) (muM P τ.2 n)) (SquareRel (fullSim R₀ n)) xp
      with hQ
    have hQ0 : ∀ τ, 0 ≤ Q τ := fun τ => q_nonneg
    have hQ1 : ∀ τ, Q τ ≤ 1 := fun τ => q_le_one
    set M : ℝ≥0∞ := ∑' τ, tiltW P R₀ t σp τ * ENNReal.ofReal (Q τ) with hM
    have hM1 : M ≤ 1 := by
      rw [hM, ← hw_sum]
      refine ENNReal.tsum_le_tsum fun τ => ?_
      calc tiltW P R₀ t σp τ * ENNReal.ofReal (Q τ)
          ≤ tiltW P R₀ t σp τ * 1 :=
            mul_le_mul_right (by simpa using ENNReal.ofReal_le_ofReal (hQ1 τ)) _
        _ = tiltW P R₀ t σp τ := mul_one _
    have hM_top : M ≠ ⊤ := ne_top_of_le_ne_top ENNReal.one_ne_top hM1
    -- the exact mixture decomposition of the pair-level bad degree
    have hdecomp : qE (pairMix P t n) (SquareRel (fullSim R₀ n)) xp = Dr * M + E := by
      rw [qE_pairMix]
      have hsplit : ∀ τ : S × S, (P t) τ
            * qE (prodPMF (muM P τ.1 n) (muM P τ.2 n)) (SquareRel (fullSim R₀ n)) xp
          = (if SquareRel R₀ σp τ then
              (P t) τ * qE (prodPMF (muM P τ.1 n) (muM P τ.2 n))
                (SquareRel (fullSim R₀ n)) xp else 0)
            + (if SquareRel R₀ σp τ then 0 else (P t) τ) := by
        intro τ
        by_cases h : SquareRel R₀ σp τ
        · rw [if_pos h, if_pos h, add_zero]
        · rw [if_neg h, if_neg h, zero_add,
            qE_eq_one_of_mismatch P R₀ n τ xp (by rw [← hσp]; exact h), mul_one]
      rw [tsum_congr hsplit, ENNReal.tsum_add]
      congr 1
      -- the compatible part is `Dr * M`; the mismatch part closed definitionally
      rw [hM, ← ENNReal.tsum_mul_left]
      refine tsum_congr fun τ => ?_
      have hoq : ENNReal.ofReal (Q τ)
          = qE (prodPMF (muM P τ.1 n) (muM P τ.2 n)) (SquareRel (fullSim R₀ n)) xp :=
        ENNReal.ofReal_toReal qE_ne_top
      have htw : tiltW P R₀ t σp τ
          = (if SquareRel R₀ σp τ then (P t) τ else 0) * Dr⁻¹ := rfl
      rw [hoq, htw]
      by_cases h : SquareRel R₀ σp τ
      · rw [if_pos h, if_pos h]
        rw [show Dr * ((P t) τ * Dr⁻¹
            * qE (prodPMF (muM P τ.1 n) (muM P τ.2 n)) (SquareRel (fullSim R₀ n)) xp)
          = (Dr * Dr⁻¹) * ((P t) τ
            * qE (prodPMF (muM P τ.1 n) (muM P τ.2 n)) (SquareRel (fullSim R₀ n)) xp)
          from by ring]
        rw [ENNReal.mul_inv_cancel hD hD_top, one_mul]
      · rw [if_neg h, if_neg h, zero_mul, zero_mul, mul_zero]
    -- pass to the reals and split
    have hd_e : Dr.toReal + E.toReal = 1 := by
      rw [hDr, hE]; exact toReal_rE_add_toReal_qE (P t) (SquareRel R₀) σp
    have hq_real : q (pairMix P t n) (SquareRel (fullSim R₀ n)) xp
        = E.toReal + (1 - E.toReal) * M.toReal := by
      rw [q, hdecomp, ENNReal.toReal_add
          (ENNReal.mul_ne_top hD_top hM_top) (qE_ne_top (μ := P t)),
        ENNReal.toReal_mul]
      have : Dr.toReal = 1 - E.toReal := by linarith
      rw [this]
      ring
    have hE0 : 0 ≤ E.toReal := ENNReal.toReal_nonneg
    have hEle : E ≤ 1 := qE_le_one
    have hE1' : E.toReal ≤ 1 := by
      have := ENNReal.toReal_mono ENNReal.one_ne_top hEle
      simpa using this
    have hM0 : 0 ≤ M.toReal := ENNReal.toReal_nonneg
    have hM1' : M.toReal ≤ 1 := by
      have := ENNReal.toReal_mono ENNReal.one_ne_top hM1
      simpa using this
    -- assemble: split, then Jensen, then monotone substitution
    have hsplit := phiE_split (α := α) (e := E.toReal) (qt := M.toReal) hα hE0 hE1' hM0 hM1'
    have hjensen : phiE α M.toReal ≤ Jmix α P R₀ t σp n xp := by
      have h := phiE_tsum_jensen (α := α) hα (tiltW P R₀ t σp) Q hw_sum hQ0 hQ1
      rw [← hM] at h
      exact h
    have he_eq : q (P t) (SquareRel R₀) σp = E.toReal := by rw [q, hE]
    rw [hq_real, he_eq]
    calc phiE α (E.toReal + (1 - E.toReal) * M.toReal)
        ≤ phiE α E.toReal + phiE α M.toReal
          + ENNReal.ofReal (2 * α) * (phiE α E.toReal * phiE α M.toReal) := hsplit
      _ ≤ phiE α E.toReal + Jmix α P R₀ t σp n xp
          + ENNReal.ofReal (2 * α) * (phiE α E.toReal * Jmix α P R₀ t σp n xp) := by
          gcongr

end GraphMarkovMatching
