/-
Polynomial dependence on the largest arity (`arbitrary_offspring_matching.tex`,
`sec:arity-dependence`): for a fixed atom set `𝒜` and a probability floor `c` on the core
arities, the canonical presentations (`sec:profile-depths`: one root child a leaf, the other
a balanced tree) with largest arity `N` satisfy `thm:markov-matching` at exponent `2` with
the threshold `c₁ N^{-2p}` and the failure coefficient `C₁ N^p`, where
`p = 2 log₂(16 B₀)` and `B₀ = max{1, #𝒜 c^{-2}}`.

* `balanced`, `canonicalProfile`: the balanced tree with `n` leaves and the canonical
  atomic profile `D_a = node leaf (balanced a)`, with its depth-one leaf and height at
  most `1 + ⌈log₂ a⌉` (`sec:profile-depths`);
* `IsCanonical`: the canonical presentations of `𝒜` with largest arity at most `N`;
* `Lfix`, `B0`, `pExp`, `arityC2`, `arityC1`, `arityc1`: the constants of
  `sec:arity-dependence`;
* `IsCanonical.ell_le`, `IsCanonical.Hret_le`, `IsCanonical.card_live_le`,
  `SH_le_of_le`, `GH_le_of_le`: the bounds `H ≤ 2L + 2 log₂ N`, `T ≤ N²`,
  `S_H ≤ 2^{2L+1} N²`, `G_H(16 B₀) ≤ (16 B₀)^{2L+1} N^p/(16 B₀ - 1)`;
* `Ereal_two_le`, `barrier_two_le`, `coefficient_le`, `arity_real_bounds`: the stopped
  bound `E(M) ≤ 32 B G_H(16 B₀)(ζ + M²)`, the barrier left side
  `≤ a M + C₂ N^p (ζ + M²)` at exponent `2`, and the closed real barrier at
  `M = C₁ N^p ζ` under `ζ ≤ c₁ N^{-2p}`;
* `arity_dependence_explicit`, `arity_dependence`, `arity_dependence_infinite`,
  `arity_dependence_eta`: the statement of `sec:arity-dependence` with the explicit
  constants, in existential form, on the infinite tree, and in the `η` form;
* `canonicalExpr`, `canonicalPresentation`, `isCanonical_canonicalPresentation`,
  `exists_canonical`: canonical presentations exist for every pair of laws with supports in
  `{2, …, N}` containing the core and shifted arities in the semigroup generated by `𝒜`.
-/
import GraphMarkovMatching.Stopped.Application
import GraphMarkovMatching.Stopped.Consequences
import Mathlib.Analysis.SpecialFunctions.Log.Base

namespace GraphMarkovMatching.Stopped

open GraphMarkovMatching GraphMarkovMatching.Support Model
open scoped ENNReal Classical

/-! ### The canonical atomic profiles (`sec:profile-depths`) -/

/-- The balanced full binary tree with `n` leaves, a leaf for `n ≤ 1`: the root subtrees
carry `⌈n/2⌉` and `⌊n/2⌋` leaves (`sec:profile-depths`). -/
def balanced (n : ℕ) : MTree :=
  if _ : n ≤ 1 then MTree.leaf
  else MTree.node (balanced ((n + 1) / 2)) (balanced (n / 2))
termination_by n
decreasing_by all_goals omega

/-- `balanced n` is a leaf for `n ≤ 1`. -/
lemma balanced_of_le {n : ℕ} (hn : n ≤ 1) : balanced n = MTree.leaf := by
  rw [balanced, dite_eq_left hn]

/-- `balanced n` splits the leaves for `n ≥ 2`. -/
lemma balanced_of_lt {n : ℕ} (hn : 1 < n) :
    balanced n = MTree.node (balanced ((n + 1) / 2)) (balanced (n / 2)) := by
  rw [balanced, dite_eq_right (by omega)]

/-- The balanced tree with `n ≥ 1` leaves has `n` leaves (`sec:profile-depths`). -/
lemma leaves_balanced (n : ℕ) : 1 ≤ n → (balanced n).leaves = n := by
  refine Nat.strong_induction_on n ?_
  intro n ih hn
  by_cases h1 : n ≤ 1
  · rw [balanced_of_le h1]
    show 1 = n
    omega
  · rw [balanced_of_lt (by omega)]
    show (balanced ((n + 1) / 2)).leaves + (balanced (n / 2)).leaves = n
    rw [ih _ (by omega) (by omega), ih _ (by omega) (by omega)]
    omega

/-- The balanced tree is graft-free. -/
lemma noGraft_balanced (n : ℕ) : (balanced n).NoGraft := by
  refine Nat.strong_induction_on n ?_
  intro n ih
  by_cases h1 : n ≤ 1
  · rw [balanced_of_le h1]
    trivial
  · rw [balanced_of_lt (by omega)]
    exact ⟨ih _ (by omega), ih _ (by omega)⟩

/-- The balanced tree with `n` leaves has height at most `⌈log₂ n⌉`
(`sec:profile-depths`). -/
lemma height_balanced (n : ℕ) : (balanced n).height ≤ Nat.clog 2 n := by
  refine Nat.strong_induction_on n ?_
  intro n ih
  by_cases h1 : n ≤ 1
  · rw [balanced_of_le h1]
    exact Nat.zero_le _
  · rw [balanced_of_lt (by omega)]
    show max (balanced ((n + 1) / 2)).height (balanced (n / 2)).height + 1 ≤ _
    have h2 := ih ((n + 1) / 2) (by omega)
    have h3 := ih (n / 2) (by omega)
    have h4 : Nat.clog 2 (n / 2) ≤ Nat.clog 2 ((n + 1) / 2) :=
      Nat.clog_mono_right 2 (by omega)
    rw [Nat.clog_of_two_le (by norm_num) (by omega)]
    have h5 : (n + 2 - 1) / 2 = (n + 1) / 2 := by omega
    rw [h5]
    omega

/-- The canonical atomic profile `D_a = node leaf (balanced a)` (`sec:profile-depths`): one
root child a leaf, the other a balanced tree with `a` leaves. -/
def canonicalProfile (a : ℕ) : MTree := MTree.node MTree.leaf (balanced a)

/-- `D_a` has `a + 1` leaves for `a ≥ 1`. -/
lemma leaves_canonicalProfile {a : ℕ} (ha : 1 ≤ a) : (canonicalProfile a).leaves = a + 1 := by
  show 1 + (balanced a).leaves = a + 1
  rw [leaves_balanced a ha]
  omega

/-- `D_a` has height at most `1 + ⌈log₂ a⌉` (`sec:profile-depths`). -/
lemma height_canonicalProfile (a : ℕ) : (canonicalProfile a).height ≤ Nat.clog 2 a + 1 := by
  show max MTree.leaf.height (balanced a).height + 1 ≤ _
  have := height_balanced a
  show max 0 _ + 1 ≤ _
  omega

/-- `D_a` is graft-free. -/
lemma noGraft_canonicalProfile (a : ℕ) : (canonicalProfile a).NoGraft :=
  ⟨trivial, noGraft_balanced a⟩

/-- `D_a` is a node. -/
lemma canonicalProfile_node (a : ℕ) : ∃ l r, canonicalProfile a = MTree.node l r :=
  ⟨_, _, rfl⟩

/-- `D_a` has a leaf at depth one (`sec:return-times`). -/
lemma one_mem_leafDepths_canonicalProfile (a : ℕ) : 1 ∈ (canonicalProfile a).leafDepths := by
  simp [canonicalProfile, MTree.leafDepths]

/-! ### The constants (`sec:arity-dependence`) -/

/-- `L = 1 + ⌈log₂ max 𝒜⌉`, the common height bound of the canonical profiles
(`sec:profile-depths`). -/
def Lfix (A : Finset ℕ) : ℕ := Nat.clog 2 (A.sup id) + 1

/-- `B₀ = max{1, #𝒜 c^{-2}}` (`sec:arity-dependence`). -/
noncomputable def B0 (A : Finset ℕ) (c : ℝ) : ℝ := max 1 (A.card * c ^ (-(2 : ℝ)))

/-- `p = 2 log₂(16 B₀)` (`sec:arity-dependence`). -/
noncomputable def pExp (A : Finset ℕ) (c : ℝ) : ℝ := 2 * Real.logb 2 (16 * B0 A c)

/-- `C₂ = 500 B₀² (16 B₀)^{2L+1}`, the coefficient of `N^p (ζ + M²)` in the barrier
(`sec:arity-dependence`). -/
noncomputable def arityC2 (A : Finset ℕ) (c : ℝ) : ℝ :=
  500 * B0 A c ^ 2 * (16 * B0 A c) ^ (2 * Lfix A + 1)

/-- `C₁ = 2 C₂/(1 - a)` with `a = 381/512` (`sec:arity-dependence`). -/
noncomputable def arityC1 (A : Finset ℕ) (c : ℝ) : ℝ := 1024 * arityC2 A c / 131

/-- `c₁ = 1/(C₁² 2^{4L+4})` (`sec:arity-dependence`). -/
noncomputable def arityc1 (A : Finset ℕ) (c : ℝ) : ℝ :=
  1 / (arityC1 A c ^ 2 * 2 ^ (4 * Lfix A + 4))

/-- `1 ≤ B₀`. -/
lemma one_le_B0 (A : Finset ℕ) (c : ℝ) : 1 ≤ B0 A c := le_max_left _ _

/-- `#𝒜 c^{-2} ≤ B₀`. -/
lemma card_mul_le_B0 (A : Finset ℕ) (c : ℝ) : A.card * c ^ (-(2 : ℝ)) ≤ B0 A c :=
  le_max_right _ _

/-- `8 ≤ p` (`sec:arity-dependence`). -/
lemma eight_le_pExp (A : Finset ℕ) (c : ℝ) : 8 ≤ pExp A c := by
  unfold pExp
  have h16 : (16 : ℝ) ≤ 16 * B0 A c := by linarith [one_le_B0 A c]
  have h1 : Real.logb 2 16 ≤ Real.logb 2 (16 * B0 A c) :=
    Real.logb_le_logb_of_le one_lt_two (by norm_num) h16
  have h2 : Real.logb 2 16 = 4 := by
    rw [show (16 : ℝ) = 2 ^ (4 : ℕ) by norm_num, Real.logb_pow, Real.logb_self_eq_one one_lt_two]
    norm_num
  linarith

/-- `500 ≤ C₂`. -/
lemma arityC2_ge (A : Finset ℕ) (c : ℝ) : 500 ≤ arityC2 A c := by
  unfold arityC2
  have hB := one_le_B0 A c
  have h1 : (1 : ℝ) ≤ B0 A c ^ 2 := one_le_pow₀ hB
  have h2 : (1 : ℝ) ≤ (16 * B0 A c) ^ (2 * Lfix A + 1) := one_le_pow₀ (by linarith)
  calc (500 : ℝ) = 500 * 1 * 1 := by ring
    _ ≤ 500 * B0 A c ^ 2 * (16 * B0 A c) ^ (2 * Lfix A + 1) := by gcongr

/-- `2 ≤ C₁`. -/
lemma two_le_arityC1 (A : Finset ℕ) (c : ℝ) : 2 ≤ arityC1 A c := by
  unfold arityC1
  linarith [arityC2_ge A c]

/-- `0 < C₁`. -/
lemma arityC1_pos (A : Finset ℕ) (c : ℝ) : 0 < arityC1 A c := by
  linarith [two_le_arityC1 A c]

/-- `0 < c₁`. -/
lemma arityc1_pos (A : Finset ℕ) (c : ℝ) : 0 < arityc1 A c := by
  unfold arityc1
  have := arityC1_pos A c
  positivity

/-- `c₁ ≤ 1/16`. -/
lemma arityc1_le (A : Finset ℕ) (c : ℝ) : arityc1 A c ≤ 1 / 16 := by
  unfold arityc1
  have h1 : (4 : ℝ) ≤ arityC1 A c ^ 2 := by nlinarith [two_le_arityC1 A c]
  have h2 : (16 : ℝ) ≤ 2 ^ (4 * Lfix A + 4) := by
    calc (16 : ℝ) = 2 ^ 4 := by norm_num
      _ ≤ 2 ^ (4 * Lfix A + 4) := pow_le_pow_right₀ (by norm_num) (by omega)
  rw [div_le_div_iff₀ (by positivity) (by norm_num)]
  nlinarith

/-- The Gauss sum `∑_{k=2}^{N} (k - 2) = (N-1)(N-2)/2` at `N = m + 2`, in the form
`2 ∑ ≤ (m+1) m`. -/
private lemma sum_sub_two_le (m : ℕ) :
    2 * ∑ k ∈ Finset.range (m + 3), (k - 2) ≤ (m + 1) * m := by
  induction m with
  | zero => decide
  | succ m ih =>
    rw [Finset.sum_range_succ, mul_add]
    have e : m + 3 - 2 = m + 1 := by omega
    rw [e]
    nlinarith [ih]

/-! ### The canonical presentations (`sec:arity-dependence`) -/

/-- The canonical presentations of the atom set `𝒜` with floor `c` on the core arities and
largest arity at most `N` (`sec:arity-dependence`): the core `S = {a + 1 : a ∈ 𝒜}`, the
canonical core profiles, supports in `{2, …, N}`, core probabilities at least `c`, and
composite profiles built by shallowest-leaf grafting along expressions of `k - 1` in the
atoms. -/
def IsCanonical (A : Finset ℕ) (c : ℝ) (N : ℕ) (P : Presentation) : Prop :=
  P.S = A.image (· + 1)
  ∧ (∀ a ∈ A, P.D (a + 1) = canonicalProfile a)
  ∧ (∀ σ k, k ∈ P.supp σ → k ≤ N)
  ∧ (∀ σ a, a ∈ P.S → ENNReal.ofReal c ≤ P.ν σ a)
  ∧ ∀ σ k, k ∈ P.supp σ → ∃ as : List ℕ, (∀ a ∈ as, a ∈ A) ∧ as.sum + 1 = k
      ∧ P.C σ k = MTree.composite canonicalProfile as

namespace IsCanonical

variable {A : Finset ℕ} {c : ℝ} {N : ℕ} {P : Presentation} (hP : IsCanonical A c N P)
include hP

/-- The largest arity is at least `2`. -/
lemma two_le_N : 2 ≤ N := by
  obtain ⟨a, ha⟩ := P.S_nonempty
  have h1 := P.two_le_S a ha
  have h2 := hP.2.2.1 false a (P.S_subset_supp false ha)
  omega

/-- `#S = #𝒜`. -/
lemma card_S : P.S.card = A.card := by
  rw [hP.1]
  exact Finset.card_image_of_injective A (add_left_injective 1)

/-- The core floor. -/
lemma floor : ∀ σ a, a ∈ P.S → ENNReal.ofReal c ≤ P.ν σ a := hP.2.2.2.1

/-- A core profile has a leaf at depth one (`sec:return-times`). -/
lemma depthOne (hA : A.Nonempty) : ∃ a ∈ P.S, 1 ∈ (P.D a).leafDepths := by
  obtain ⟨a, ha⟩ := hA
  refine ⟨a + 1, ?_, ?_⟩
  · rw [hP.1]
    exact Finset.mem_image_of_mem _ ha
  · rw [hP.2.1 a ha]
    exact one_mem_leafDepths_canonicalProfile a

/-- **`thm:shallow-grafting`** for the canonical presentations: every supported profile has
height at most `L + ⌊log₂ N⌋`. -/
lemma height_C_le (hA1 : ∀ a ∈ A, 1 ≤ a) (σ : Bool) {k : ℕ} (hk : k ∈ P.supp σ) :
    (P.C σ k).height ≤ Lfix A + Nat.log 2 N := by
  obtain ⟨as, has, hsum, hC⟩ := hP.2.2.2.2 σ k hk
  have hk2 := P.two_le_supp σ k hk
  have hkN := hP.2.2.1 σ k hk
  have hne : as ≠ [] := by
    rintro rfl
    simp at hsum
    omega
  rw [hC]
  refine (MTree.height_composite_le canonicalProfile as (Lfix A) 1 le_rfl hne ?_ ?_ ?_).trans ?_
  · intro a ha
    exact leaves_canonicalProfile (hA1 a (has a ha))
  · intro a ha
    refine (height_canonicalProfile a).trans ?_
    unfold Lfix
    have h1 : a ≤ A.sup id := Finset.le_sup (f := id) (has a ha)
    have h2 := Nat.clog_mono_right 2 h1
    omega
  · intro a ha
    exact hA1 a (has a ha)
  · have h1 : 1 + as.sum - 1 ≤ N := by omega
    have h2 := Nat.log_mono_right (b := 2) h1
    omega

/-- `ℓ ≤ L + ⌊log₂ N⌋` (`sec:arity-dependence`). -/
lemma ell_le (hA1 : ∀ a ∈ A, 1 ≤ a) : P.ell ≤ Lfix A + Nat.log 2 N := by
  unfold Presentation.ell
  exact Finset.sup_le fun σ _ => Finset.sup_le fun k hk => hP.height_C_le hA1 σ hk

/-- `H = 2ℓ ≤ 2L + 2 log₂ N` (`sec:arity-dependence`). -/
lemma Hret_le (hA1 : ∀ a ∈ A, 1 ≤ a) : 2 * P.ell ≤ 2 * Lfix A + 2 * Nat.log 2 N := by
  have := hP.ell_le hA1
  omega

/-- **`eq:type-count`** for the canonical presentations: `T ≤ N²`
(`sec:arity-dependence`). -/
lemma card_live_le : P.live.card ≤ N ^ 2 := by
  obtain ⟨m, rfl⟩ : ∃ m, N = m + 2 := ⟨N - 2, by have := hP.two_le_N; omega⟩
  have h1 := P.card_live_le
  have key : ∀ σ, ∑ k ∈ P.supp σ, (k - 2) ≤ ∑ k ∈ Finset.range (m + 3), (k - 2) := by
    intro σ
    refine Finset.sum_le_sum_of_subset fun k hk => ?_
    rw [Finset.mem_range]
    have := hP.2.2.1 σ k hk
    omega
  have h2 := sum_sub_two_le m
  rw [Fintype.sum_bool] at h1
  have h3 := key true
  have h4 := key false
  calc P.live.card ≤ 2 + (∑ k ∈ P.supp true, (k - 2) + ∑ k ∈ P.supp false, (k - 2)) := h1
    _ ≤ 2 + (∑ k ∈ Finset.range (m + 3), (k - 2) + ∑ k ∈ Finset.range (m + 3), (k - 2)) := by
        gcongr
    _ ≤ (m + 2) ^ 2 := by nlinarith

/-- The inverse-probability sum of the core selection is at most `B₀` (`thm:atomic-normalisation`,
`sec:arity-dependence`). -/
lemma inverseSum_le {V : Type} (R : V → V → Prop) (zero : V) (μ : PMF V)
    (hc : (P.toModel R zero μ).IsCompat) (hb0 : rE μ R zero ≠ 0) (hc0 : 0 < c)
    (t : P.Live) :
    (P.selection R zero μ hc hb0).inverseSum 2 t ≤ ENNReal.ofReal (B0 A c) := by
  refine (P.inverseSum_le_of_floor R zero μ hc hb0 (by norm_num) hc0 hP.floor t).trans ?_
  refine ENNReal.ofReal_le_ofReal ?_
  unfold Presentation.coreInverseSum inverseSumOf
  rw [hP.card_S]
  exact card_mul_le_B0 A c

end IsCanonical

/-! ### The two finite sums (`sec:arity-dependence`) -/

/-- `S_H ≤ 2^{2L+1} N²` when `H ≤ 2L + 2 ⌊log₂ N⌋` (`sec:arity-dependence`). -/
lemma SH_le_of_le {H L N : ℕ} (hN : N ≠ 0) (hH : H ≤ 2 * L + 2 * Nat.log 2 N) :
    SH H ≤ 2 ^ (2 * L + 1) * (N : ℝ) ^ 2 := by
  have h1 : (2 : ℝ) ^ Nat.log 2 N ≤ N := by exact_mod_cast Nat.pow_log_le_self 2 hN
  have h2 : (2 : ℝ) ^ (H + 1) ≤ 2 ^ (2 * L + 1 + 2 * Nat.log 2 N) :=
    pow_le_pow_right₀ (by norm_num) (by omega)
  have h3 : (2 : ℝ) ^ (2 * L + 1 + 2 * Nat.log 2 N)
      = 2 ^ (2 * L + 1) * (2 ^ Nat.log 2 N) ^ 2 := by
    rw [pow_add, pow_mul']
  have h4 : ((2 : ℝ) ^ Nat.log 2 N) ^ 2 ≤ (N : ℝ) ^ 2 := pow_le_pow_left₀ (by positivity) h1 2
  unfold SH
  calc (2 : ℝ) ^ (H + 1) - 1 ≤ 2 ^ (H + 1) := by linarith
    _ ≤ 2 ^ (2 * L + 1 + 2 * Nat.log 2 N) := h2
    _ = 2 ^ (2 * L + 1) * (2 ^ Nat.log 2 N) ^ 2 := h3
    _ ≤ 2 ^ (2 * L + 1) * (N : ℝ) ^ 2 := by gcongr

/-- `x^{2k} ≤ N^{2 log₂ x}` when `2^k ≤ N` and `x > 1` (`sec:arity-dependence`:
`(16 B₀)^{2 log₂ N} = N^p`). -/
lemma pow_two_mul_le_rpow_logb {x : ℝ} (hx : 1 < x) {k N : ℕ} (hk : 2 ^ k ≤ N) :
    x ^ (2 * k) ≤ (N : ℝ) ^ (2 * Real.logb 2 x) := by
  have hx0 : 0 < x := by linarith
  have hl : 0 ≤ Real.logb 2 x := Real.logb_nonneg one_lt_two hx.le
  have e1 : (2 : ℝ) ^ Real.logb 2 x = x := Real.rpow_logb two_pos (by norm_num) hx0
  have hk' : ((2 : ℝ) ^ k) ≤ N := by exact_mod_cast hk
  calc x ^ (2 * k) = ((2 : ℝ) ^ Real.logb 2 x) ^ (2 * k) := by rw [e1]
    _ = (2 : ℝ) ^ (Real.logb 2 x * ((2 * k : ℕ) : ℝ)) := by
        rw [← Real.rpow_natCast, ← Real.rpow_mul (by norm_num)]
    _ = ((2 : ℝ) ^ (k : ℝ)) ^ (2 * Real.logb 2 x) := by
        rw [← Real.rpow_mul (by norm_num)]
        congr 1
        push_cast
        ring
    _ = ((2 : ℝ) ^ k) ^ (2 * Real.logb 2 x) := by rw [Real.rpow_natCast]
    _ ≤ (N : ℝ) ^ (2 * Real.logb 2 x) := Real.rpow_le_rpow (by positivity) hk' (by positivity)

/-- `G_H(x) ≤ x^{2L+1} N^{2 log₂ x}/(x - 1)` when `H ≤ 2L + 2 ⌊log₂ N⌋` and `x > 1`
(`sec:arity-dependence`). -/
lemma GH_le_of_le {H L N : ℕ} (hN : N ≠ 0) (hH : H ≤ 2 * L + 2 * Nat.log 2 N) {x : ℝ}
    (hx : 1 < x) :
    GH H x ≤ x ^ (2 * L + 1) * (N : ℝ) ^ (2 * Real.logb 2 x) / (x - 1) := by
  have hx1 : 0 < x - 1 := by linarith
  rw [le_div_iff₀ hx1]
  calc GH H x * (x - 1) = x ^ (H + 1) - 1 := geom_sum_mul x (H + 1)
    _ ≤ x ^ (H + 1) := by linarith
    _ ≤ x ^ (2 * L + 1 + 2 * Nat.log 2 N) := pow_le_pow_right₀ hx.le (by omega)
    _ = x ^ (2 * L + 1) * x ^ (2 * Nat.log 2 N) := pow_add x _ _
    _ ≤ x ^ (2 * L + 1) * (N : ℝ) ^ (2 * Real.logb 2 x) := by
        gcongr
        exact pow_two_mul_le_rpow_logb hx (Nat.pow_log_le_self 2 hN)

/-! ### The barrier at exponent two (`sec:arity-dependence`) -/

/-- The stopped weighted bound at exponent `2`: with `ζ, M ≤ 1/2`, `4 S_H² T² ζ ≤ 1`,
`f = 3ζ`, `R_μ = 1 + 2ζ` and `Z = 2 S_H ζ`, `E(M) ≤ 32 B G_H(16 B)(ζ + M²)`
(`sec:arity-dependence`). -/
lemma Ereal_two_le (H T : ℕ) {B t Mv S : ℝ} (hB : 1 ≤ B) (ht0 : 0 ≤ t) (ht : t ≤ 1 / 2)
    (hM0 : 0 ≤ Mv) (hM : Mv ≤ 1 / 2) (h4 : 4 * S ^ 2 * (T : ℝ) ^ 2 * t ≤ 1) :
    Ereal 2 H T B (3 * t) (1 + 2 * t) (2 * S * t) Mv
      ≤ 32 * B * GH H (16 * B) * (t + Mv ^ 2) := by
  have hB0 : 0 ≤ B := by linarith
  have hG : GH H (4 * B * (1 + 2 * t) * (1 + 2 * Mv)) ≤ GH H (16 * B) := by
    refine GH_mono H (by positivity) ?_
    have h : (1 + 2 * t) * (1 + 2 * Mv) ≤ 4 := by nlinarith [mul_nonneg ht0 hM0]
    calc 4 * B * (1 + 2 * t) * (1 + 2 * Mv) = 4 * B * ((1 + 2 * t) * (1 + 2 * Mv)) := by ring
      _ ≤ 4 * B * 4 := by gcongr
      _ = 16 * B := by ring
  have h1 : (1 + 2 * Mv) ^ 2 ≤ 4 := by nlinarith
  have h2 : ((T : ℝ) * (2 * S * t) + 2 * Mv) ^ 2 ≤ 8 * ((T : ℝ) * S * t) ^ 2 + 8 * Mv ^ 2 := by
    nlinarith [sq_nonneg ((T : ℝ) * (2 * S * t) - 2 * Mv)]
  have h3 : 8 * ((T : ℝ) * S * t) ^ 2 ≤ 2 * t := by
    have e : ((T : ℝ) * S * t) ^ 2 = t * (S ^ 2 * (T : ℝ) ^ 2 * t) := by ring
    rw [e]
    nlinarith
  have hbr : 2 * B * (1 + 2 * Mv) ^ 2 * (3 * t)
      + 2 * B * (1 + 2 * t) * ((T : ℝ) * (2 * S * t) + 2 * Mv) ^ 2
      ≤ 32 * B * (t + Mv ^ 2) := by
    have e1 : 2 * B * (1 + 2 * Mv) ^ 2 * (3 * t) ≤ 2 * B * 4 * (3 * t) := by
      gcongr
    have e2 : 2 * B * (1 + 2 * t) * ((T : ℝ) * (2 * S * t) + 2 * Mv) ^ 2
        ≤ 2 * B * 2 * (2 * t + 8 * Mv ^ 2) := by
      gcongr
      · linarith
      · linarith
    nlinarith
  have h0br : 0 ≤ 2 * B * (1 + 2 * Mv) ^ 2 * (3 * t)
      + 2 * B * (1 + 2 * t) * ((T : ℝ) * (2 * S * t) + 2 * Mv) ^ 2 := by
    have : 0 ≤ 2 * B := by linarith
    have : 0 ≤ 1 + 2 * t := by linarith
    positivity
  unfold Ereal
  calc GH H (4 * B * (1 + 2 * t) * (1 + 2 * Mv)) * (2 * B * (1 + 2 * Mv) ^ 2 * (3 * t)
        + 2 * B * (1 + 2 * t) * ((T : ℝ) * (2 * S * t) + 2 * Mv) ^ 2)
      ≤ GH H (16 * B) * (32 * B * (t + Mv ^ 2)) :=
        mul_le_mul hG hbr h0br (GH_nonneg H (by positivity))
    _ = 32 * B * GH H (16 * B) * (t + Mv ^ 2) := by ring

/-- The barrier left side at exponent `2` with `a = 381/512`, `b = 38`, `γ = 17/8`,
`C = 4 + 24 B`, `D_μ ≤ 1 + 3ζ`, `Z = 2 S ζ` and `E ≤ 32 B G (ζ + M²)`: it is at most
`a M + (98 + 31 S + 4480 B² G)(ζ + M²)` (`sec:arity-dependence`). -/
lemma barrier_two_le {t Mv S G B E : ℝ} (ht0 : 0 ≤ t) (ht : t ≤ 1 / 2) (hM0 : 0 ≤ Mv)
    (hM : Mv ≤ 1 / 2) (hB : 1 ≤ B) (hS : 0 ≤ S) (hE0 : 0 ≤ E)
    (hE : E ≤ 32 * B * G * (t + Mv ^ 2)) :
    t + (1 + 3 * t) * Qreal 2 (381 / 512) 38 (17 / 8) (4 + 8 * (2 + 1) * B) (2 * S * t) E Mv
      ≤ 381 / 512 * Mv + (98 + 31 * S + 4480 * B ^ 2 * G) * (t + Mv ^ 2) := by
  have hB0 : 0 ≤ B := by linarith
  unfold Qreal
  have hu : 1 + 3 * t ≤ 5 / 2 := by linarith
  have hu0 : 0 ≤ 1 + 3 * t := by linarith
  have X1 : (1 + 3 * t) * (381 / 512 * Mv) ≤ 381 / 512 * Mv + 3 / 2 * (t + Mv ^ 2) := by
    nlinarith [sq_nonneg (t - Mv), mul_nonneg ht0 hM0]
  have X2 : (1 + 3 * t) * (38 * Mv ^ 2) ≤ 95 * Mv ^ 2 := by nlinarith [sq_nonneg Mv]
  have X3 : (1 + 3 * t) * ((17 / 8 + 4 * 2 * Mv) * (2 * S * t)) ≤ 31 * (S * t) := by
    have h1 : 17 / 8 + 4 * 2 * Mv ≤ 49 / 8 := by linarith
    have h3 : 0 ≤ S * t := mul_nonneg hS ht0
    calc (1 + 3 * t) * ((17 / 8 + 4 * 2 * Mv) * (2 * S * t))
        ≤ 5 / 2 * (49 / 8 * (2 * S * t)) := by gcongr
      _ ≤ 31 * (S * t) := by nlinarith
  have X4 : (1 + 3 * t) * ((4 + 8 * (2 + 1) * B) * (1 + 2 * Mv) * E)
      ≤ 4480 * B ^ 2 * G * (t + Mv ^ 2) := by
    have h1 : 4 + 8 * (2 + 1) * B ≤ 28 * B := by linarith
    have h2 : 1 + 2 * Mv ≤ 2 := by linarith
    have h3 : 0 ≤ 4 + 8 * (2 + 1) * B := by linarith
    have h4 : 0 ≤ 1 + 2 * Mv := by linarith
    calc (1 + 3 * t) * ((4 + 8 * (2 + 1) * B) * (1 + 2 * Mv) * E)
        ≤ 5 / 2 * (28 * B * 2 * (32 * B * G * (t + Mv ^ 2))) := by gcongr
      _ = 4480 * B ^ 2 * G * (t + Mv ^ 2) := by ring
  have hSM : 0 ≤ S * Mv ^ 2 := mul_nonneg hS (sq_nonneg _)
  nlinarith [X1, X2, X3, X4, hSM, sq_nonneg Mv]

/-- The coefficient `98 + 31 S + 4480 B² G` is at most `C₂ N^p` when
`S ≤ 2^{2L+1} N²` and `G ≤ (16 B)^{2L+1} N^p/(16 B - 1)` (`sec:arity-dependence`). -/
lemma coefficient_le {S G B Np N2 : ℝ} (L : ℕ) (hB : 1 ≤ B) (hN2 : 0 ≤ N2)
    (hNp : 1 ≤ Np) (hN2p : N2 ≤ Np) (hS : S ≤ 2 ^ (2 * L + 1) * N2)
    (hG : G ≤ (16 * B) ^ (2 * L + 1) * Np / (16 * B - 1)) :
    98 + 31 * S + 4480 * B ^ 2 * G ≤ 500 * B ^ 2 * (16 * B) ^ (2 * L + 1) * Np := by
  set X := (16 * B) ^ (2 * L + 1) with hX
  have hX2 : (2 : ℝ) ^ (2 * L + 1) ≤ X := pow_le_pow_left₀ (by norm_num) (by linarith) _
  have hX1 : (1 : ℝ) ≤ X := one_le_pow₀ (by linarith)
  have hB2 : (1 : ℝ) ≤ B ^ 2 := one_le_pow₀ hB
  have hY1 : (1 : ℝ) ≤ B ^ 2 * X * Np := by
    calc (1 : ℝ) = 1 * 1 * 1 := by ring
      _ ≤ B ^ 2 * X * Np := by gcongr
  have hY0 : 0 ≤ B ^ 2 * X * Np := by linarith
  have hG15 : G ≤ X * Np / 15 := by
    refine hG.trans ?_
    refine div_le_div_of_nonneg_left (by positivity) (by norm_num) (by linarith)
  have hSY : S ≤ B ^ 2 * X * Np := by
    calc S ≤ 2 ^ (2 * L + 1) * N2 := hS
      _ ≤ X * Np := by gcongr
      _ = 1 * (X * Np) := (one_mul _).symm
      _ ≤ B ^ 2 * (X * Np) := by gcongr
      _ = B ^ 2 * X * Np := by ring
  have hGY : 4480 * B ^ 2 * G ≤ 299 * (B ^ 2 * X * Np) := by
    calc 4480 * B ^ 2 * G ≤ 4480 * B ^ 2 * (X * Np / 15) := by gcongr
      _ = (4480 / 15) * (B ^ 2 * X * Np) := by ring
      _ ≤ 299 * (B ^ 2 * X * Np) := by gcongr; norm_num
  calc 98 + 31 * S + 4480 * B ^ 2 * G
      ≤ 98 * (B ^ 2 * X * Np) + 31 * (B ^ 2 * X * Np) + 299 * (B ^ 2 * X * Np) := by
        gcongr
        linarith
    _ ≤ 500 * B ^ 2 * X * Np := by linarith

/-! ### The theorem (`sec:arity-dependence`) -/

namespace Model

variable {V I : Type} (M : Model V I)

/-- The four-law input at exponent `2` with the rational coefficients `a = 381/512`,
`b = 38`, `γ = 17/8` (`eq:mean-exponent-two`), at every height and every phase map. -/
private lemma fourLawAt_two (hc : M.IsCompat) {g : ℕ} (Θ : Phase M g) (h : ℕ)
    (Mb Zm E : ℝ≥0∞) :
    M.FourLawAt Θ 2 h (ENNReal.ofReal (381 / 512)) (ENNReal.ofReal 38)
      (ENNReal.ofReal (17 / 8)) Mb Zm E := by
  have key := M.fourLawAt_of_params hc paramsTwo.hα paramsTwo.hβ0 paramsTwo.hβ1
    paramsTwo.hu0 paramsTwo.hu1 paramsTwo.hL paramsTwo.hK paramsTwo.hL0 Θ h Mb Zm E
  have e1 : ENNReal.ofReal (2 * (paramsTwo.L + paramsTwo.K)) = ENNReal.ofReal (381 / 512) := by
    norm_num [paramsTwo]
  have e2 : ENNReal.ofReal (Cfun paramsTwo.α paramsTwo.L0 paramsTwo.u) = ENNReal.ofReal 38 := by
    show ENNReal.ofReal (Cfun 2 (1 / 4) (1 / 2)) = ENNReal.ofReal 38
    rw [Cfun_two]
  have e3 : ENNReal.ofReal (2 + 2 * paramsTwo.β) = ENNReal.ofReal (17 / 8) := by
    norm_num [paramsTwo]
  rw [e1, e2, e3] at key
  exact key

end Model

/-- **The real estimates of `sec:arity-dependence`** in one place: with the constants
`C₂ = 500 B² (16 B)^{2L+1}`, `C₁ = 2 C₂/(1-a)`, `c₁ = 1/(C₁² 2^{4L+4})`, `p = 2 log₂(16 B)`,
the bounds `H ≤ 2L + 2 log₂ N`, `T ≤ N²`, and `ζ ≤ c₁ N^{-2p}`, the value `M = C₁ N^p ζ`
satisfies `ζ, M ≤ 1/2`, `4 S_H² T² ζ ≤ 1`, and the real barrier
`ζ + (1 + 3ζ) Q(ζ, M) ≤ M` with `Z = 2 S_H ζ` and `E = E(M)` at `f = 3ζ`, `R_μ = 1 + 2ζ`. -/
lemma arity_real_bounds (L H T N : ℕ) {B C2 C1 c1 p t : ℝ} (hB1 : 1 ≤ B)
    (hC2 : C2 = 500 * B ^ 2 * (16 * B) ^ (2 * L + 1)) (hC1 : C1 = 1024 * C2 / 131)
    (hc1 : c1 = 1 / (C1 ^ 2 * 2 ^ (4 * L + 4))) (hp : p = 2 * Real.logb 2 (16 * B))
    (hN0 : N ≠ 0) (hH : H ≤ 2 * L + 2 * Nat.log 2 N) (hT : (T : ℝ) ≤ (N : ℝ) ^ 2)
    (ht0 : 0 ≤ t) (ht : t ≤ c1 * (N : ℝ) ^ (-(2 * p))) :
    t ≤ 1 / 2 ∧ 0 ≤ C1 * (N : ℝ) ^ p * t ∧ C1 * (N : ℝ) ^ p * t ≤ 1 / 2
    ∧ 4 * SH H ^ 2 * (T : ℝ) ^ 2 * t ≤ 1
    ∧ t + (1 + 3 * t) * Qreal 2 (381 / 512) 38 (17 / 8) (4 + 8 * (2 + 1) * B) (2 * SH H * t)
        (Ereal 2 H T B (3 * t) (1 + 2 * t) (2 * SH H * t) (C1 * (N : ℝ) ^ p * t))
        (C1 * (N : ℝ) ^ p * t)
      ≤ C1 * (N : ℝ) ^ p * t := by
  have hB0 : 0 ≤ B := by linarith
  -- the constants
  have hC2ge : 500 ≤ C2 := by
    rw [hC2]
    have h1 : (1 : ℝ) ≤ B ^ 2 := one_le_pow₀ hB1
    have h2 : (1 : ℝ) ≤ (16 * B) ^ (2 * L + 1) := one_le_pow₀ (by linarith)
    calc (500 : ℝ) = 500 * 1 * 1 := by ring
      _ ≤ 500 * B ^ 2 * (16 * B) ^ (2 * L + 1) := by gcongr
  have hC1ge : 2 ≤ C1 := by rw [hC1]; linarith
  have hC1pos : 0 < C1 := by linarith
  have h2pow : (1 : ℝ) ≤ 2 ^ (4 * L + 4) := one_le_pow₀ (by norm_num)
  have hc1pos : 0 < c1 := by rw [hc1]; positivity
  have hc1le : c1 ≤ 1 / 16 := by
    rw [hc1]
    have h1 : (4 : ℝ) ≤ C1 ^ 2 := by nlinarith
    have h2 : (16 : ℝ) ≤ 2 ^ (4 * L + 4) := by
      calc (16 : ℝ) = 2 ^ 4 := by norm_num
        _ ≤ 2 ^ (4 * L + 4) := pow_le_pow_right₀ (by norm_num) (by omega)
    rw [div_le_div_iff₀ (by positivity) (by norm_num)]
    nlinarith
  have hC1c1 : C1 ^ 2 * c1 ≤ 1 := by
    rw [hc1, show C1 ^ 2 * (1 / (C1 ^ 2 * 2 ^ (4 * L + 4))) = 1 / 2 ^ (4 * L + 4) by
      field_simp]
    exact div_le_one_of_le₀ h2pow (by positivity)
  have h2c1 : 2 ^ (4 * L + 4) * c1 ≤ 1 := by
    rw [hc1, show (2 : ℝ) ^ (4 * L + 4) * (1 / (C1 ^ 2 * 2 ^ (4 * L + 4))) = 1 / C1 ^ 2 by
      field_simp]
    exact div_le_one_of_le₀ (by nlinarith) (by positivity)
  have hp8 : 8 ≤ p := by
    rw [hp]
    have h16 : (16 : ℝ) ≤ 16 * B := by linarith
    have h1 : Real.logb 2 16 ≤ Real.logb 2 (16 * B) :=
      Real.logb_le_logb_of_le one_lt_two (by norm_num) h16
    have h2 : Real.logb 2 16 = 4 := by
      rw [show (16 : ℝ) = 2 ^ (4 : ℕ) by norm_num, Real.logb_pow,
        Real.logb_self_eq_one one_lt_two]
      norm_num
    linarith
  -- the largest arity
  have hN1 : (1 : ℝ) ≤ N := by exact_mod_cast Nat.one_le_iff_ne_zero.mpr hN0
  have hNr0 : (0 : ℝ) ≤ N := by linarith
  set Np := (N : ℝ) ^ p with hNp_def
  have hNp1 : 1 ≤ Np := Real.one_le_rpow hN1 (by linarith)
  have hNp0 : 0 ≤ Np := by linarith
  have hN2p : (N : ℝ) ^ 2 ≤ Np := by
    rw [hNp_def, ← Real.rpow_natCast]
    exact Real.rpow_le_rpow_of_exponent_le hN1 (by push_cast; linarith)
  have hN4p : (N : ℝ) ^ 4 ≤ Np := by
    rw [hNp_def, ← Real.rpow_natCast]
    exact Real.rpow_le_rpow_of_exponent_le hN1 (by push_cast; linarith)
  have hNneg : (N : ℝ) ^ (-(2 * p)) = (Np ^ 2)⁻¹ := by
    rw [hNp_def, Real.rpow_neg hNr0, mul_comm, Real.rpow_mul hNr0, Real.rpow_two]
  have hGH : GH H (16 * B) ≤ (16 * B) ^ (2 * L + 1) * Np / (16 * B - 1) := by
    rw [hNp_def, hp]
    exact GH_le_of_le hN0 hH (by linarith)
  clear_value Np
  -- the smallness of `ζ`
  have hkey : Np ^ 2 * t ≤ c1 := by
    rw [hNneg] at ht
    have hNp2 : 0 < Np ^ 2 := by positivity
    calc Np ^ 2 * t ≤ Np ^ 2 * (c1 * (Np ^ 2)⁻¹) := by gcongr
      _ = c1 := by field_simp
  have ht16 : t ≤ 1 / 16 := by
    have h1 : t ≤ Np ^ 2 * t := le_mul_of_one_le_left ht0 (one_le_pow₀ hNp1)
    linarith
  have ht12 : t ≤ 1 / 2 := by linarith
  set Mv := C1 * Np * t with hMv_def
  have hMv0 : 0 ≤ Mv := by positivity
  have hMv2 : Mv ^ 2 ≤ t := by
    have e : Mv ^ 2 = t * (C1 ^ 2 * (Np ^ 2 * t)) := by rw [hMv_def]; ring
    rw [e]
    calc t * (C1 ^ 2 * (Np ^ 2 * t)) ≤ t * (C1 ^ 2 * c1) := by gcongr
      _ ≤ t * 1 := by gcongr
      _ = t := mul_one t
  have hMv12 : Mv ≤ 1 / 2 := by nlinarith
  -- the two finite sums
  set S := SH H with hS_def
  have hS0 : 0 < S := SH_pos H
  have hSH : S ≤ 2 ^ (2 * L + 1) * (N : ℝ) ^ 2 := SH_le_of_le hN0 hH
  clear_value S
  have h4 : 4 * S ^ 2 * (T : ℝ) ^ 2 * t ≤ 1 := by
    have hST : S ^ 2 * (T : ℝ) ^ 2 ≤ 2 ^ (4 * L + 2) * Np ^ 2 := by
      calc S ^ 2 * (T : ℝ) ^ 2 ≤ (2 ^ (2 * L + 1) * (N : ℝ) ^ 2) ^ 2 * ((N : ℝ) ^ 2) ^ 2 := by
            gcongr
        _ = 2 ^ (4 * L + 2) * ((N : ℝ) ^ 4) ^ 2 := by ring
        _ ≤ 2 ^ (4 * L + 2) * Np ^ 2 := by gcongr
    calc 4 * S ^ 2 * (T : ℝ) ^ 2 * t = 4 * (S ^ 2 * (T : ℝ) ^ 2) * t := by ring
      _ ≤ 4 * (2 ^ (4 * L + 2) * Np ^ 2) * t := by gcongr
      _ = 2 ^ (4 * L + 4) * (Np ^ 2 * t) := by ring
      _ ≤ 2 ^ (4 * L + 4) * c1 := by gcongr
      _ ≤ 1 := h2c1
  -- the weighted bound and the barrier
  set G := GH H (16 * B) with hG_def
  have hG0 : 0 ≤ G := GH_nonneg H (by positivity)
  set Ev := Ereal 2 H T B (3 * t) (1 + 2 * t) (2 * S * t) Mv with hEv_def
  have hEr : Ev ≤ 32 * B * G * (t + Mv ^ 2) :=
    Ereal_two_le H T hB1 ht0 ht12 hMv0 hMv12 h4
  have hEv0 : 0 ≤ Ev := by
    rw [hEv_def, Ereal]
    have h1 : 0 ≤ 1 + 2 * t := by linarith
    have h2 : 0 ≤ 4 * B * (1 + 2 * t) * (1 + 2 * Mv) := by positivity
    have h3 := GH_nonneg H h2
    positivity
  clear_value G Ev
  have hW : 98 + 31 * S + 4480 * B ^ 2 * G ≤ C2 * Np := by
    rw [hC2]
    exact coefficient_le L hB1 (by positivity) hNp1 hN2p hSH hGH
  refine ⟨ht12, hMv0, hMv12, h4, ?_⟩
  have h1 := barrier_two_le ht0 ht12 hMv0 hMv12 hB1 hS0.le hEv0 hEr
  have h2 : (98 + 31 * S + 4480 * B ^ 2 * G) * (t + Mv ^ 2) ≤ C2 * Np * (t + Mv ^ 2) := by
    gcongr
  have h3 : C2 * Np * (t + Mv ^ 2) ≤ C2 * Np * (2 * t) := by
    have hCN : 0 ≤ C2 * Np := by positivity
    have : t + Mv ^ 2 ≤ 2 * t := by linarith
    exact mul_le_mul_of_nonneg_left this hCN
  have h4' : 381 / 512 * Mv + C2 * Np * (2 * t) = Mv := by
    rw [hMv_def, hC1]
    ring
  linarith

/-- **`sec:arity-dependence`, explicit form**: for a canonical presentation of the atom set
`𝒜` with floor `c` and largest arity `N`, every state law with `ζ_2 ≤ c₁ N^{-2p}` has
failure probability at most `C₁ N^p ζ_2` for the two fresh types at every height, with the
explicit constants `arityC1` and `arityc1`. The proof runs the height induction
`P_le_finite` with the explicit zero bound `Z = 2 S_H ζ`, the weighted bound
`E(M) ≤ 32 B₀ G_H(16 B₀)(ζ + M²)` and the barrier value `M = C₁ N^p ζ`. -/
theorem arity_dependence_explicit (A : Finset ℕ) (hA : A.Nonempty) (hA1 : ∀ a ∈ A, 1 ≤ a)
    {c : ℝ} (hc : 0 < c) (N : ℕ) (P : Presentation) (hP : IsCanonical A c N P)
    {V : Type} (R : V → V → Prop) (zero : V) (μ : PMF V)
    (hcompat : (P.toModel R zero μ).IsCompat)
    (hζ : (P.toModel R zero μ).zeta 2
      ≤ ENNReal.ofReal (arityc1 A c * (N : ℝ) ^ (-(2 * pExp A c)))) :
    ∀ σ σ' h, (P.toModel R zero μ).failProb (P.freshL σ) (P.freshL σ') h
      ≤ ENNReal.ofReal (arityC1 A c * (N : ℝ) ^ pExp A c) * (P.toModel R zero μ).zeta 2 := by
  intro σ σ' h
  have hζtop : (P.toModel R zero μ).zeta 2 ≠ ⊤ := ne_top_of_le_ne_top ENNReal.ofReal_ne_top hζ
  have hb0 : rE μ R zero ≠ 0 := (P.toModel R zero μ).rE_zero_ne_zero_of_zeta_ne_top hζtop
  obtain ⟨t, hteq, ht0⟩ : ∃ t : ℝ, (P.toModel R zero μ).zeta 2 = ENNReal.ofReal t ∧ 0 ≤ t :=
    ⟨_, (ENNReal.ofReal_toReal hζtop).symm, ENNReal.toReal_nonneg⟩
  rw [hteq] at hζ
  have hNneg0 : 0 ≤ arityc1 A c * (N : ℝ) ^ (-(2 * pExp A c)) :=
    mul_nonneg (arityc1_pos A c).le (Real.rpow_nonneg (Nat.cast_nonneg N) _)
  have ht : t ≤ arityc1 A c * (N : ℝ) ^ (-(2 * pExp A c)) :=
    (ENNReal.ofReal_le_ofReal_iff hNneg0).mp hζ
  -- the model data
  have hN0 : N ≠ 0 := by have := hP.two_le_N; omega
  have hHle : 2 * P.ell ≤ 2 * Lfix A + 2 * Nat.log 2 N := hP.Hret_le hA1
  have hTN : (P.live.card : ℝ) ≤ (N : ℝ) ^ 2 := by exact_mod_cast hP.card_live_le
  have hTc : ∀ i, (P.phase R zero μ).count i ≤ P.live.card := P.count_le_card R zero μ
  have hCR : (P.toModel R zero μ).CommonReturns (P.phase R zero μ) (2 * P.ell) :=
    (P.commonReturns_depthOne R zero μ P.S_nonempty (hP.depthOne hA)).2
  have hBs : ∀ u, (P.selection R zero μ hcompat hb0).inverseSum 2 u ≤ ENNReal.ofReal (B0 A c) :=
    hP.inverseSum_le R zero μ hcompat hb0 hc
  have hFP : (P.toModel R zero μ).FreshPositive := P.freshPositive R zero μ hcompat hb0
  have hfour : ∀ h Mb Zm E, (P.toModel R zero μ).FourLawAt (P.phase R zero μ) 2 h
      (ENNReal.ofReal (381 / 512)) (ENNReal.ofReal 38) (ENNReal.ofReal (17 / 8)) Mb Zm E :=
    fun h Mb Zm E => (P.toModel R zero μ).fourLawAt_two hcompat (P.phase R zero μ) h Mb Zm E
  -- the real estimates
  obtain ⟨ht12, hMv0, hMv12, h4, hbarR⟩ := arity_real_bounds (Lfix A) (2 * P.ell) P.live.card N
    (one_le_B0 A c) rfl rfl rfl rfl hN0 hHle hTN ht0 ht
  have hB0 : 0 ≤ B0 A c := (one_le_B0 A c).trans' zero_le_one
  have hB1 : 1 ≤ B0 A c := one_le_B0 A c
  have hS0 : 0 < SH (2 * P.ell) := SH_pos _
  have hZ0 : 0 ≤ 2 * SH (2 * P.ell) * t := by positivity
  -- the zero bound `Z = 2 S_H ζ`
  have hδ : (P.toModel R zero μ).delta ≤ ENNReal.ofReal t := by
    rw [← hteq]
    exact (P.toModel R zero μ).delta_le_zeta (by norm_num)
  have hZ : SHe (2 * P.ell) * ((P.toModel R zero μ).delta
      + (P.live.card : ℝ≥0∞) ^ 2 * (ENNReal.ofReal (2 * SH (2 * P.ell) * t)) ^ 2)
      ≤ ENNReal.ofReal (2 * SH (2 * P.ell) * t) := by
    have hreal : SH (2 * P.ell) * (t + (P.live.card : ℝ) ^ 2 * (2 * SH (2 * P.ell) * t) ^ 2)
        ≤ 2 * SH (2 * P.ell) * t := by
      have e : SH (2 * P.ell) * (t + (P.live.card : ℝ) ^ 2 * (2 * SH (2 * P.ell) * t) ^ 2)
          = SH (2 * P.ell) * t
            + (SH (2 * P.ell) * t) * (4 * SH (2 * P.ell) ^ 2 * (P.live.card : ℝ) ^ 2 * t) := by
        ring
      rw [e]
      have := mul_le_mul_of_nonneg_left h4 (mul_nonneg hS0.le ht0)
      linarith
    have e : ENNReal.ofReal (SH (2 * P.ell)
          * (t + (P.live.card : ℝ) ^ 2 * (2 * SH (2 * P.ell) * t) ^ 2))
        = SHe (2 * P.ell) * (ENNReal.ofReal t
          + (P.live.card : ℝ≥0∞) ^ 2 * (ENNReal.ofReal (2 * SH (2 * P.ell) * t)) ^ 2) := by
      rw [SHe_eq_ofReal, ENNReal.ofReal_mul hS0.le, ENNReal.ofReal_add ht0 (by positivity),
        ENNReal.ofReal_mul (by positivity : (0 : ℝ) ≤ (P.live.card : ℝ) ^ 2),
        ENNReal.ofReal_pow hZ0, ENNReal.ofReal_pow (Nat.cast_nonneg _), ENNReal.ofReal_natCast]
    calc SHe (2 * P.ell) * ((P.toModel R zero μ).delta
          + (P.live.card : ℝ≥0∞) ^ 2 * (ENNReal.ofReal (2 * SH (2 * P.ell) * t)) ^ 2)
        ≤ SHe (2 * P.ell) * (ENNReal.ofReal t
          + (P.live.card : ℝ≥0∞) ^ 2 * (ENNReal.ofReal (2 * SH (2 * P.ell) * t)) ^ 2) := by
          gcongr
      _ = ENNReal.ofReal (SH (2 * P.ell)
          * (t + (P.live.card : ℝ) ^ 2 * (2 * SH (2 * P.ell) * t) ^ 2)) := e.symm
      _ ≤ ENNReal.ofReal (2 * SH (2 * P.ell) * t) := ENNReal.ofReal_le_ofReal hreal
  -- the root quantities
  have hf : (P.toModel R zero μ).fRoot 2 ≤ ENNReal.ofReal (3 * t) := by
    calc (P.toModel R zero μ).fRoot 2 ≤ ENNReal.ofReal (1 + 2) * (P.toModel R zero μ).zeta 2 :=
          (P.toModel R zero μ).fRoot_le_zeta hcompat (by norm_num)
      _ = ENNReal.ofReal (3 * t) := by
          rw [hteq, ← ENNReal.ofReal_mul (by norm_num)]
          norm_num
  have hR : (P.toModel R zero μ).RmuC 2 ≤ ENNReal.ofReal (1 + 2 * t) := by
    calc (P.toModel R zero μ).RmuC 2 ≤ 1 + ENNReal.ofReal 2 * (P.toModel R zero μ).zeta 2 :=
          (P.toModel R zero μ).RmuC_le hcompat (by norm_num)
      _ = ENNReal.ofReal (1 + 2 * t) := by
          rw [hteq, ← ENNReal.ofReal_mul (by norm_num), ← ENNReal.ofReal_one,
            ← ENNReal.ofReal_add (by norm_num) (by positivity)]
  have hD : (P.toModel R zero μ).DmuC 2 ≤ ENNReal.ofReal (1 + 3 * t) := by
    calc (P.toModel R zero μ).DmuC 2
        ≤ 1 + ENNReal.ofReal (2 * 2 - 1) * (P.toModel R zero μ).zeta 2 :=
          (P.toModel R zero μ).DmuC_le hcompat (by norm_num)
      _ = ENNReal.ofReal (1 + 3 * t) := by
          rw [hteq, ← ENNReal.ofReal_mul (by norm_num), ← ENNReal.ofReal_one,
            ← ENNReal.ofReal_add (by norm_num) (by positivity)]
          norm_num
  -- the weighted bound `E(M)` and the child-pair bound `Q(M)`
  have hEv0 : 0 ≤ Ereal 2 (2 * P.ell) P.live.card (B0 A c) (3 * t) (1 + 2 * t)
      (2 * SH (2 * P.ell) * t) (arityC1 A c * (N : ℝ) ^ pExp A c * t) := by
    rw [Ereal]
    have h1 : 0 ≤ 1 + 2 * t := by linarith
    have h2 : 0 ≤ 4 * B0 A c * (1 + 2 * t) * (1 + 2 * (arityC1 A c * (N : ℝ) ^ pExp A c * t)) := by
      positivity
    have h3 := GH_nonneg (2 * P.ell) h2
    positivity
  have hE : Efun 2 (2 * P.ell) P.live.card (ENNReal.ofReal (B0 A c)) ((P.toModel R zero μ).fRoot 2)
      ((P.toModel R zero μ).RmuC 2) (ENNReal.ofReal (2 * SH (2 * P.ell) * t))
      (ENNReal.ofReal (arityC1 A c * (N : ℝ) ^ pExp A c * t))
      ≤ ENNReal.ofReal (Ereal 2 (2 * P.ell) P.live.card (B0 A c) (3 * t) (1 + 2 * t)
        (2 * SH (2 * P.ell) * t) (arityC1 A c * (N : ℝ) ^ pExp A c * t)) := by
    refine (Efun_mono 2 (2 * P.ell) P.live.card le_rfl hf hR le_rfl le_rfl).trans (le_of_eq ?_)
    exact Efun_ofReal 2 (by norm_num) (2 * P.ell) P.live.card hB0 (by positivity) (by positivity)
      hZ0 hMv0
  have hC : Cmix 2 (ENNReal.ofReal (B0 A c)) = ENNReal.ofReal (4 + 8 * (2 + 1) * B0 A c) := by
    rw [ENNReal.ofReal_add (by norm_num) (by positivity),
      ENNReal.ofReal_mul (by norm_num : (0 : ℝ) ≤ 8 * (2 + 1)),
      ENNReal.ofReal_mul (by norm_num : (0 : ℝ) ≤ 8)]
    simp only [ENNReal.ofReal_ofNat]
    rfl
  have hQ0 : 0 ≤ Qreal 2 (381 / 512) 38 (17 / 8) (4 + 8 * (2 + 1) * B0 A c)
      (2 * SH (2 * P.ell) * t)
      (Ereal 2 (2 * P.ell) P.live.card (B0 A c) (3 * t) (1 + 2 * t) (2 * SH (2 * P.ell) * t)
        (arityC1 A c * (N : ℝ) ^ pExp A c * t)) (arityC1 A c * (N : ℝ) ^ pExp A c * t) := by
    unfold Qreal
    have : 0 ≤ 4 + 8 * (2 + 1) * B0 A c := by linarith
    positivity
  have hQ : Qfun 2 (ENNReal.ofReal (381 / 512)) (ENNReal.ofReal 38) (ENNReal.ofReal (17 / 8))
      (Cmix 2 (ENNReal.ofReal (B0 A c))) (ENNReal.ofReal (2 * SH (2 * P.ell) * t))
      (Efun 2 (2 * P.ell) P.live.card (ENNReal.ofReal (B0 A c)) ((P.toModel R zero μ).fRoot 2)
        ((P.toModel R zero μ).RmuC 2) (ENNReal.ofReal (2 * SH (2 * P.ell) * t))
        (ENNReal.ofReal (arityC1 A c * (N : ℝ) ^ pExp A c * t)))
      (ENNReal.ofReal (arityC1 A c * (N : ℝ) ^ pExp A c * t))
      ≤ ENNReal.ofReal (Qreal 2 (381 / 512) 38 (17 / 8) (4 + 8 * (2 + 1) * B0 A c)
        (2 * SH (2 * P.ell) * t)
        (Ereal 2 (2 * P.ell) P.live.card (B0 A c) (3 * t) (1 + 2 * t) (2 * SH (2 * P.ell) * t)
          (arityC1 A c * (N : ℝ) ^ pExp A c * t)) (arityC1 A c * (N : ℝ) ^ pExp A c * t)) := by
    refine (Qfun_mono 2 _ _ _ _ le_rfl hE le_rfl).trans (le_of_eq ?_)
    rw [hC]
    exact Qfun_ofReal 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by linarith) hZ0
      hEv0 hMv0
  -- the barrier
  have hbar : (P.toModel R zero μ).zeta 2 + (P.toModel R zero μ).DmuC 2
      * Qfun 2 (ENNReal.ofReal (381 / 512)) (ENNReal.ofReal 38) (ENNReal.ofReal (17 / 8))
        (Cmix 2 (ENNReal.ofReal (B0 A c))) (ENNReal.ofReal (2 * SH (2 * P.ell) * t))
        (Efun 2 (2 * P.ell) P.live.card (ENNReal.ofReal (B0 A c))
          ((P.toModel R zero μ).fRoot 2) ((P.toModel R zero μ).RmuC 2)
          (ENNReal.ofReal (2 * SH (2 * P.ell) * t))
          (ENNReal.ofReal (arityC1 A c * (N : ℝ) ^ pExp A c * t)))
        (ENNReal.ofReal (arityC1 A c * (N : ℝ) ^ pExp A c * t))
      ≤ ENNReal.ofReal (arityC1 A c * (N : ℝ) ^ pExp A c * t) := by
    refine (add_le_add (le_of_eq hteq) (mul_le_mul' hD hQ)).trans ?_
    rw [← ENNReal.ofReal_mul (by linarith), ← ENNReal.ofReal_add ht0 (by positivity)]
    exact ENNReal.ofReal_le_ofReal hbarR
  -- the conclusion
  have hfail := (P.toModel R zero μ).failProb_le_finite_fresh hcompat hb0 hFP (by norm_num)
    (P.phase R zero μ) hTc hCR (P.selection R zero μ hcompat hb0) hBs
    (ENNReal.ofReal (381 / 512)) (ENNReal.ofReal 38) (ENNReal.ofReal (17 / 8)) hfour hZ hbar h
    (P.freshL σ) (P.freshL σ') (P.fresh_freshL R zero μ σ) (P.fresh_freshL R zero μ σ')
  refine hfail.trans (le_of_eq ?_)
  rw [hteq, ENNReal.ofReal_mul
    (mul_nonneg (arityC1_pos A c).le (Real.rpow_nonneg (Nat.cast_nonneg N) _))]

/-- **`sec:arity-dependence`**: constants `C₁, c₁ > 0` depending only on the atom set `𝒜`
and the floor `c` such that every canonical presentation with largest arity `N` and every
state law with `ζ_2 ≤ c₁ N^{-2p}` has failure probability at most `C₁ N^p ζ_2` for the two
fresh types at every height, where `p = 2 log₂(16 B₀)` and `B₀ = max{1, #𝒜 c^{-2}}`. -/
theorem arity_dependence (A : Finset ℕ) (hA : A.Nonempty) (hA1 : ∀ a ∈ A, 1 ≤ a) {c : ℝ}
    (hc : 0 < c) :
    ∃ C₁ c₁ : ℝ, 0 < C₁ ∧ 0 < c₁ ∧ ∀ (N : ℕ) (P : Presentation), IsCanonical A c N P →
      ∀ {V : Type} (R : V → V → Prop) (zero : V) (μ : PMF V),
        (P.toModel R zero μ).IsCompat →
        (P.toModel R zero μ).zeta 2 ≤ ENNReal.ofReal (c₁ * (N : ℝ) ^ (-(2 * pExp A c))) →
        ∀ σ σ' h, (P.toModel R zero μ).failProb (P.freshL σ) (P.freshL σ') h
          ≤ ENNReal.ofReal (C₁ * (N : ℝ) ^ pExp A c) * (P.toModel R zero μ).zeta 2 :=
  ⟨arityC1 A c, arityc1 A c, arityC1_pos A c, arityc1_pos A c,
    fun N P hP _ R zero μ hcompat hζ =>
      arity_dependence_explicit A hA hA1 hc N P hP R zero μ hcompat hζ⟩

/-- **`sec:arity-dependence`, on the infinite tree**: the same constants bound the failure
probability of the two fresh types on the whole tree. -/
theorem arity_dependence_infinite (A : Finset ℕ) (hA : A.Nonempty) (hA1 : ∀ a ∈ A, 1 ≤ a)
    {c : ℝ} (hc : 0 < c) :
    ∃ C₁ c₁ : ℝ, 0 < C₁ ∧ 0 < c₁ ∧ ∀ (N : ℕ) (P : Presentation), IsCanonical A c N P →
      ∀ {V : Type} [Countable V] [MeasurableSpace V] [MeasurableSingletonClass V]
        (R : V → V → Prop) (zero : V) (μ : PMF V),
        (P.toModel R zero μ).IsCompat →
        (P.toModel R zero μ).zeta 2 ≤ ENNReal.ofReal (c₁ * (N : ℝ) ^ (-(2 * pExp A c))) →
        ∀ σ σ', (P.toModel R zero μ).trajPair (P.freshL σ) (P.freshL σ')
            ((P.toModel R zero μ).InfMatchEv (P.freshL σ) (P.freshL σ'))ᶜ
          ≤ ENNReal.ofReal (C₁ * (N : ℝ) ^ pExp A c) * (P.toModel R zero μ).zeta 2 := by
  obtain ⟨C₁, c₁, hC₁, hc₁, hbound⟩ := arity_dependence A hA hA1 hc
  refine ⟨C₁, c₁, hC₁, hc₁, ?_⟩
  intro N P hP V _ _ _ R zero μ hcompat hζ σ σ'
  exact (P.toModel R zero μ).trajPair_infFail_le _ _ (hbound N P hP R zero μ hcompat hζ σ σ')

/-- **`sec:arity-dependence`, the `η` form**: with `μ(0) ≥ p₀ > 0`, constants depending also
on `p₀` such that `η_2 ≤ c₁ N^{-2p}` gives failure probability at most `C₁ N^p η_2` for the
two fresh types at every height. -/
theorem arity_dependence_eta (A : Finset ℕ) (hA : A.Nonempty) (hA1 : ∀ a ∈ A, 1 ≤ a) {c : ℝ}
    (hc : 0 < c) {p0 : ℝ} (hp0 : 0 < p0) (hp1 : p0 ≤ 1) :
    ∃ C₁ c₁ : ℝ, 0 < C₁ ∧ 0 < c₁ ∧ ∀ (N : ℕ) (P : Presentation), IsCanonical A c N P →
      ∀ {V : Type} (R : V → V → Prop) (zero : V) (μ : PMF V),
        (P.toModel R zero μ).IsCompat → ENNReal.ofReal p0 ≤ μ zero →
        (P.toModel R zero μ).eta 2 ≤ ENNReal.ofReal (c₁ * (N : ℝ) ^ (-(2 * pExp A c))) →
        ∀ σ σ' h, (P.toModel R zero μ).failProb (P.freshL σ) (P.freshL σ') h
          ≤ ENNReal.ofReal (C₁ * (N : ℝ) ^ pExp A c) * (P.toModel R zero μ).eta 2 := by
  obtain ⟨C₁, c₁, hC₁, hc₁, hbound⟩ := arity_dependence A hA hA1 hc
  refine ⟨C₁ / p0, p0 * c₁, by positivity, by positivity, ?_⟩
  intro N P hP V R zero μ hcompat hμ hη σ σ' h
  have hp : ENNReal.ofReal p0 ≠ 0 := (ENNReal.ofReal_pos.mpr hp0).ne'
  have hp1' : ENNReal.ofReal p0 ≤ 1 := ENNReal.ofReal_le_one.mpr hp1
  have hζη : (P.toModel R zero μ).zeta 2 ≤ (P.toModel R zero μ).eta 2 / ENNReal.ofReal p0 :=
    (P.toModel R zero μ).zeta_le_eta_div hcompat (by norm_num) hp hp1' hμ
  have hNp : 0 ≤ (N : ℝ) ^ (-(2 * pExp A c)) := Real.rpow_nonneg (Nat.cast_nonneg N) _
  have hζ : (P.toModel R zero μ).zeta 2
      ≤ ENNReal.ofReal (c₁ * (N : ℝ) ^ (-(2 * pExp A c))) := by
    refine hζη.trans ?_
    rw [ENNReal.div_le_iff hp ENNReal.ofReal_ne_top, ← ENNReal.ofReal_mul (mul_nonneg hc₁.le hNp)]
    refine hη.trans (le_of_eq ?_)
    congr 1
    ring
  calc (P.toModel R zero μ).failProb (P.freshL σ) (P.freshL σ') h
      ≤ ENNReal.ofReal (C₁ * (N : ℝ) ^ pExp A c) * (P.toModel R zero μ).zeta 2 :=
        hbound N P hP R zero μ hcompat hζ σ σ' h
    _ ≤ ENNReal.ofReal (C₁ * (N : ℝ) ^ pExp A c)
        * ((P.toModel R zero μ).eta 2 / ENNReal.ofReal p0) := by gcongr
    _ = ENNReal.ofReal (C₁ / p0 * (N : ℝ) ^ pExp A c) * (P.toModel R zero μ).eta 2 := by
        rw [div_mul_eq_mul_div, ENNReal.ofReal_div_of_pos hp0, div_eq_mul_inv, div_eq_mul_inv]
        ring

/-! ### Existence of canonical presentations (`sec:common-generators`, `sec:profile-depths`) -/

/-- The expression of `n` in the atoms `𝒜`: the one-term expression `[n]` when `n` is an
atom, otherwise a chosen list of atoms summing to `n` (the empty list outside the generated
semigroup). -/
noncomputable def canonicalExpr (A : Finset ℕ) (n : ℕ) : List ℕ :=
  if n ∈ A then [n]
  else if h : n ∈ AddSubmonoid.closure (A : Set ℕ) then
    Classical.choose (AddSubmonoid.exists_list_of_mem_closure h)
  else []

/-- The chosen expression consists of atoms and sums to the element. -/
lemma canonicalExpr_spec {A : Finset ℕ} {n : ℕ} (h : n ∈ AddSubmonoid.closure (A : Set ℕ)) :
    (∀ a ∈ canonicalExpr A n, a ∈ A) ∧ (canonicalExpr A n).sum = n := by
  unfold canonicalExpr
  by_cases h1 : n ∈ A
  · rw [ite_eq_left h1]
    simp [h1]
  · rw [ite_eq_right h1, dite_eq_left h]
    obtain ⟨hmem, hsum⟩ := Classical.choose_spec (AddSubmonoid.exists_list_of_mem_closure h)
    exact ⟨fun a ha => Finset.mem_coe.mp (hmem a ha), hsum⟩

/-- An atom has the one-term expression. -/
lemma canonicalExpr_of_mem {A : Finset ℕ} {n : ℕ} (h : n ∈ A) : canonicalExpr A n = [n] := by
  unfold canonicalExpr
  rw [ite_eq_left h]

/-- The supported arities of the two sides are at least `2` with shifted arity in the
generated semigroup. -/
private lemma canonical_supp_facts {A : Finset ℕ} {suppL suppR : Finset ℕ}
    (h2L : ∀ k ∈ suppL, 2 ≤ k) (h2R : ∀ k ∈ suppR, 2 ≤ k)
    (hgenL : ∀ k ∈ suppL, k - 1 ∈ AddSubmonoid.closure (A : Set ℕ))
    (hgenR : ∀ k ∈ suppR, k - 1 ∈ AddSubmonoid.closure (A : Set ℕ)) (σ : Bool) (k : ℕ)
    (hk : k ∈ (if σ then suppR else suppL)) :
    2 ≤ k ∧ k - 1 ∈ AddSubmonoid.closure (A : Set ℕ) := by
  cases σ
  · exact ⟨h2L k (by simpa using hk), hgenL k (by simpa using hk)⟩
  · exact ⟨h2R k (by simpa using hk), hgenR k (by simpa using hk)⟩

/-- **The canonical presentation** of two arity laws with finite supports in `{2, 3, …}`
containing the core `{a + 1 : a ∈ 𝒜}` and every shifted arity in the semigroup generated by
`𝒜` (`sec:common-generators`, `sec:profile-depths`): the canonical core profiles and the
composites of the chosen atomic expressions. -/
noncomputable def canonicalPresentation (A : Finset ℕ) (hA : A.Nonempty)
    (hA1 : ∀ a ∈ A, 1 ≤ a) (νL νR : PMF ℕ) (suppL suppR : Finset ℕ)
    (hL : ∀ k, νL k ≠ 0 ↔ k ∈ suppL) (hR : ∀ k, νR k ≠ 0 ↔ k ∈ suppR)
    (h2L : ∀ k ∈ suppL, 2 ≤ k) (h2R : ∀ k ∈ suppR, 2 ≤ k)
    (hSL : A.image (· + 1) ⊆ suppL) (hSR : A.image (· + 1) ⊆ suppR)
    (hgenL : ∀ k ∈ suppL, k - 1 ∈ AddSubmonoid.closure (A : Set ℕ))
    (hgenR : ∀ k ∈ suppR, k - 1 ∈ AddSubmonoid.closure (A : Set ℕ)) : Presentation where
  S := A.image (· + 1)
  D := fun a => canonicalProfile (a - 1)
  ν := fun σ => if σ then νR else νL
  supp := fun σ => if σ then suppR else suppL
  C := fun _ k => MTree.composite canonicalProfile (canonicalExpr A (k - 1))
  mem_supp := by
    intro σ k
    cases σ
    · simpa using hL k
    · simpa using hR k
  S_nonempty := hA.image _
  two_le_S := by
    intro a ha
    obtain ⟨a', ha', rfl⟩ := Finset.mem_image.mp ha
    have := hA1 a' ha'
    omega
  D_leaves := by
    intro a ha
    obtain ⟨a', ha', rfl⟩ := Finset.mem_image.mp ha
    show (canonicalProfile (a' + 1 - 1)).leaves = a' + 1
    rw [Nat.add_sub_cancel]
    exact leaves_canonicalProfile (hA1 a' ha')
  D_noGraft := fun a _ => noGraft_canonicalProfile _
  D_node := fun a _ => canonicalProfile_node _
  S_subset_supp := by
    intro σ
    cases σ
    · simpa using hSL
    · simpa using hSR
  two_le_supp := fun σ k hk => (canonical_supp_facts h2L h2R hgenL hgenR σ k hk).1
  C_leaves := by
    intro σ k hk
    obtain ⟨hk2, hkΛ⟩ := canonical_supp_facts h2L h2R hgenL hgenR σ k hk
    obtain ⟨hmem, hsum⟩ := canonicalExpr_spec hkΛ
    show (MTree.composite canonicalProfile (canonicalExpr A (k - 1))).leaves = k
    rw [MTree.leaves_composite canonicalProfile _
      (fun a ha => leaves_canonicalProfile (hA1 a (hmem a ha))), hsum]
    omega
  C_gnode := by
    intro σ k hk
    obtain ⟨hk2, hkΛ⟩ := canonical_supp_facts h2L h2R hgenL hgenR σ k hk
    obtain ⟨-, hsum⟩ := canonicalExpr_spec hkΛ
    have hne : canonicalExpr A (k - 1) ≠ [] := by
      intro hnil
      rw [hnil, List.sum_nil] at hsum
      omega
    obtain ⟨a, as, has⟩ := List.exists_cons_of_ne_nil hne
    show ∃ l r, MTree.composite canonicalProfile (canonicalExpr A (k - 1)) = MTree.gnode l r
    rw [has]
    exact MTree.composite_cons canonicalProfile a as fun b _ => canonicalProfile_node b
  C_allComp := by
    intro σ k hk
    obtain ⟨-, hkΛ⟩ := canonical_supp_facts h2L h2R hgenL hgenR σ k hk
    obtain ⟨hmem, -⟩ := canonicalExpr_spec hkΛ
    show MTree.AllComp (A.image (· + 1)) (fun a => canonicalProfile (a - 1))
      (MTree.composite canonicalProfile (canonicalExpr A (k - 1)))
    refine allComp_shift (A := A) (D := fun a => canonicalProfile (a - 1))
      (D' := canonicalProfile) (fun a => by simp) _ ?_
    exact MTree.allComp_composite A canonicalProfile _
      (fun a _ => ⟨noGraft_canonicalProfile a, canonicalProfile_node a⟩) hmem
  C_core := by
    intro σ a ha
    obtain ⟨a', ha', rfl⟩ := Finset.mem_image.mp ha
    show MTree.composite canonicalProfile (canonicalExpr A (a' + 1 - 1))
      = MTree.markRoot (canonicalProfile (a' + 1 - 1))
    rw [Nat.add_sub_cancel, canonicalExpr_of_mem ha', MTree.composite_singleton]

/-- The canonical presentation is canonical (`sec:arity-dependence`) when the supports lie
in `{2, …, N}` and the core probabilities are at least `c` on both sides. -/
theorem isCanonical_canonicalPresentation (A : Finset ℕ) (hA : A.Nonempty)
    (hA1 : ∀ a ∈ A, 1 ≤ a) (c : ℝ) (N : ℕ) (νL νR : PMF ℕ) (suppL suppR : Finset ℕ)
    (hL : ∀ k, νL k ≠ 0 ↔ k ∈ suppL) (hR : ∀ k, νR k ≠ 0 ↔ k ∈ suppR)
    (h2L : ∀ k ∈ suppL, 2 ≤ k) (h2R : ∀ k ∈ suppR, 2 ≤ k)
    (hSL : A.image (· + 1) ⊆ suppL) (hSR : A.image (· + 1) ⊆ suppR)
    (hgenL : ∀ k ∈ suppL, k - 1 ∈ AddSubmonoid.closure (A : Set ℕ))
    (hgenR : ∀ k ∈ suppR, k - 1 ∈ AddSubmonoid.closure (A : Set ℕ))
    (hNL : ∀ k ∈ suppL, k ≤ N) (hNR : ∀ k ∈ suppR, k ≤ N)
    (hfloorL : ∀ a ∈ A, ENNReal.ofReal c ≤ νL (a + 1))
    (hfloorR : ∀ a ∈ A, ENNReal.ofReal c ≤ νR (a + 1)) :
    IsCanonical A c N
      (canonicalPresentation A hA hA1 νL νR suppL suppR hL hR h2L h2R hSL hSR hgenL hgenR) := by
  refine ⟨rfl, fun a _ => ?_, ?_, ?_, ?_⟩
  · show canonicalProfile (a + 1 - 1) = canonicalProfile a
    rw [Nat.add_sub_cancel]
  · intro σ k hk
    cases σ
    · exact hNL k hk
    · exact hNR k hk
  · intro σ a ha
    obtain ⟨a', ha', rfl⟩ := Finset.mem_image.mp ha
    cases σ
    · exact hfloorL a' ha'
    · exact hfloorR a' ha'
  · intro σ k hk
    obtain ⟨hk2, hkΛ⟩ := canonical_supp_facts h2L h2R hgenL hgenR σ k hk
    obtain ⟨hmem, hsum⟩ := canonicalExpr_spec hkΛ
    exact ⟨canonicalExpr A (k - 1), hmem, by omega, rfl⟩

/-- **Existence of canonical presentations**: two arity laws with finite supports in
`{2, …, N}` containing the core `{a + 1 : a ∈ 𝒜}`, every shifted arity in the semigroup
generated by `𝒜`, and core probabilities at least `c`, have a canonical presentation with
the given laws and supports (`sec:arity-dependence`). -/
theorem exists_canonical (A : Finset ℕ) (hA : A.Nonempty) (hA1 : ∀ a ∈ A, 1 ≤ a) (c : ℝ)
    (N : ℕ) (νL νR : PMF ℕ) (suppL suppR : Finset ℕ)
    (hL : ∀ k, νL k ≠ 0 ↔ k ∈ suppL) (hR : ∀ k, νR k ≠ 0 ↔ k ∈ suppR)
    (h2L : ∀ k ∈ suppL, 2 ≤ k) (h2R : ∀ k ∈ suppR, 2 ≤ k)
    (hSL : A.image (· + 1) ⊆ suppL) (hSR : A.image (· + 1) ⊆ suppR)
    (hgenL : ∀ k ∈ suppL, k - 1 ∈ AddSubmonoid.closure (A : Set ℕ))
    (hgenR : ∀ k ∈ suppR, k - 1 ∈ AddSubmonoid.closure (A : Set ℕ))
    (hNL : ∀ k ∈ suppL, k ≤ N) (hNR : ∀ k ∈ suppR, k ≤ N)
    (hfloorL : ∀ a ∈ A, ENNReal.ofReal c ≤ νL (a + 1))
    (hfloorR : ∀ a ∈ A, ENNReal.ofReal c ≤ νR (a + 1)) :
    ∃ P : Presentation, IsCanonical A c N P ∧ P.ν = (fun σ => if σ then νR else νL)
      ∧ P.supp = (fun σ => if σ then suppR else suppL) :=
  ⟨canonicalPresentation A hA hA1 νL νR suppL suppR hL hR h2L h2R hSL hSR hgenL hgenR,
    isCanonical_canonicalPresentation A hA hA1 c N νL νR suppL suppR hL hR h2L h2R hSL hSR
      hgenL hgenR hNL hNR hfloorL hfloorR, rfl, rfl⟩

end GraphMarkovMatching.Stopped
