/-
Finite renewal generators and quantitative cascade estimates for an
offspring law of unbounded support.

The zero side of the exponential-tail screen ledger must remain a finite
list.  `exists_finite_renewal_support` extracts a finite set of charged
counters whose renewal depths generate every sufficiently large multiple
of the gcd of *all* charged renewal depths.  This is the precise finite
generator statement needed for the relaxed zero lists; no minimum
positive atom is involved.
-/
import GraphMarkovMatching.Grammar.Accessible
import GraphMarkovMatching.Process.Kernel

namespace GraphMarkovMatching

open scoped ENNReal Classical

/-- The branching semigroup generated by the shifted charged counters. -/
def shiftedSupportSemigroup (ν : PMF ℕ) : AddSubmonoid ℕ :=
  AddSubmonoid.closure ((fun k : ℕ => k - 1) '' ν.support)

/-- Finite generation of the shifted-support semigroup is automatic for
every offspring law: every additive submonoid of `ℕ` is finitely generated.
Thus this property cannot by itself strengthen an exponential-tail
hypothesis.  (The previously claimed large-counter seed obstruction is
removed separately by component-in-mixture pruning.) -/
theorem shiftedSupportSemigroup_fg (ν : PMF ℕ) :
    (shiftedSupportSemigroup ν).FG :=
  Nat.addSubmonoid_fg _

/-- Eventual saturation of the shifted-support semigroup: apart from a
finite initial set, every shifted arity `m` in the semigroup is represented
by a charged arity `m + 1`.  The shift on the conclusion is essential. -/
def EventuallyChargesShiftedSemigroup (ν : PMF ℕ) : Prop :=
  ∃ K : ℕ, ∀ m : ℕ, K ≤ m → m ∈ shiftedSupportSemigroup ν → ν (m + 1) ≠ 0

lemma EventuallyChargesShiftedSemigroup.of_ge
    {ν : PMF ℕ} (hν : EventuallyChargesShiftedSemigroup ν) :
    ∃ K : ℕ, ∀ m : ℕ, K ≤ m →
      m ∈ shiftedSupportSemigroup ν → ν (m + 1) ≠ 0 :=
  hν

/-- Every charged arity contributes its predecessor to the shifted-support
semigroup. -/
lemma shifted_mem_of_succ_ne_zero {ν : PMF ℕ} {m : ℕ}
    (hm : ν (m + 1) ≠ 0) :
    m ∈ shiftedSupportSemigroup ν := by
  apply AddSubmonoid.subset_closure
  exact ⟨m + 1, hm, by simp⟩

/-- Eventual saturation says exactly that, above one threshold, membership
in the shifted semigroup is equivalent to positivity of the correspondingly
shifted atom.  No conclusion about atoms in other residue classes follows. -/
theorem EventuallyChargesShiftedSemigroup.eventually_succ_ne_zero_iff
    {ν : PMF ℕ} (hν : EventuallyChargesShiftedSemigroup ν) :
    ∃ K : ℕ, ∀ m : ℕ, K ≤ m →
      (ν (m + 1) ≠ 0 ↔ m ∈ shiftedSupportSemigroup ν) := by
  obtain ⟨K, hK⟩ := hν
  exact ⟨K, fun m hm => ⟨shifted_mem_of_succ_ne_zero, hK m hm⟩⟩

/-- All fresh-return depths belonging to charged counters. -/
def tailDepthSet (ν : PMF ℕ) : Set ℕ :=
  {d | ∃ k, (ν k : ℝ≥0∞) ≠ 0 ∧ d ∈ toFresh k}

/-- The full renewal-depth set is nonempty. -/
lemma tailDepthSet_nonempty (ν : PMF ℕ) : (tailDepthSet ν).Nonempty := by
  obtain ⟨k, hk⟩ := ν.support_nonempty
  obtain ⟨d, hd⟩ := toFresh_nonempty k
  exact ⟨d, k, hk, hd⟩

/-- Renewal depths are positive, hence their set-gcd is nonzero. -/
lemma tailDepthSet_setGcd_ne_zero (ν : PMF ℕ) :
    Nat.setGcd (tailDepthSet ν) ≠ 0 := by
  intro hzero
  have hsub := Nat.setGcd_eq_zero_iff.mp hzero
  obtain ⟨d, hd⟩ := tailDepthSet_nonempty ν
  have hd0 : d = 0 := by simpa using hsub hd
  obtain ⟨k, _, hdk⟩ := hd
  have := one_le_of_mem_toFresh k d hdk
  omega

/-- **Finite renewal support.**  There is a nonempty finite set `S₀` of
charged counters and a conductor `R` such that every sufficiently large
multiple of the gcd of all charged return depths belongs to the additive
semigroup generated by `depthSet S₀`.

Mathlib's Frobenius theorem first supplies finitely many return depths.
For each of them we choose one charged counter realizing that depth. -/
theorem exists_finite_renewal_support (ν : PMF ℕ) :
    ∃ S₀ : Finset ℕ, S₀.Nonempty
      ∧ (∀ k ∈ S₀, (ν k : ℝ≥0∞) ≠ 0)
      ∧ ∃ R, ∀ m, R ≤ m → Nat.setGcd (tailDepthSet ν) ∣ m →
          m ∈ AddSubmonoid.closure ((depthSet S₀ : Set ℕ)) := by
  obtain ⟨t, R, ht, hspan⟩ :=
    Nat.exists_mem_span_nat_finset_of_ge (s := tailDepthSet ν)
  obtain ⟨k₀, hk₀⟩ := ν.support_nonempty
  let pick : {d // d ∈ t} → ℕ := fun d => Classical.choose (ht d.property)
  have hpick : ∀ d : {d // d ∈ t},
      (ν (pick d) : ℝ≥0∞) ≠ 0 ∧ d.1 ∈ toFresh (pick d) := fun d =>
    Classical.choose_spec (ht d.property)
  let S₀ : Finset ℕ := insert k₀ (Finset.univ.image pick)
  refine ⟨S₀, ⟨k₀, Finset.mem_insert_self _ _⟩, ?_, R, ?_⟩
  · intro k hk
    rcases Finset.mem_insert.mp hk with rfl | hk
    · exact hk₀
    · obtain ⟨d, _, rfl⟩ := Finset.mem_image.mp hk
      exact (hpick d).1
  · intro m hm hdvd
    have hmspan := hspan m hm hdvd
    have hmclosure : m ∈ AddSubmonoid.closure ((t : Set ℕ)) :=
      (Submodule.span_nat_eq_addSubmonoidClosure (t : Set ℕ)).le hmspan
    refine AddSubmonoid.closure_mono ?_ hmclosure
    intro d hd
    have hdt : d ∈ t := Finset.mem_coe.mp hd
    let ds : {d // d ∈ t} := ⟨d, hdt⟩
    have hkS : pick ds ∈ S₀ := Finset.mem_insert_of_mem
      (Finset.mem_image_of_mem pick (Finset.mem_univ ds))
    exact Finset.mem_coe.mpr
      (Finset.mem_biUnion.mpr ⟨pick ds, hkS, (hpick ds).2⟩)

/-- A strengthened finite-core form: finitely many charged counters can be
chosen so that their renewal depths generate every charged renewal depth,
not merely every sufficiently large one.  The finitely many depths below
the conductor are added explicitly. -/
theorem exists_finite_renewal_support_closure (ν : PMF ℕ) :
    ∃ S₀ : Finset ℕ, S₀.Nonempty
      ∧ (∀ k ∈ S₀, (ν k : ℝ≥0∞) ≠ 0)
      ∧ ∀ d ∈ tailDepthSet ν,
          d ∈ AddSubmonoid.closure ((depthSet S₀ : Set ℕ)) := by
  obtain ⟨S, hSne, hSch, R, hR⟩ := exists_finite_renewal_support ν
  let D : Finset ℕ := (Finset.range R).filter (· ∈ tailDepthSet ν)
  let pick : {d // d ∈ D} → ℕ := fun d =>
    Classical.choose (show d.1 ∈ tailDepthSet ν from (Finset.mem_filter.mp d.2).2)
  have hpick : ∀ d : {d // d ∈ D},
      (ν (pick d) : ℝ≥0∞) ≠ 0 ∧ d.1 ∈ toFresh (pick d) := fun d =>
    Classical.choose_spec
      (show d.1 ∈ tailDepthSet ν from (Finset.mem_filter.mp d.2).2)
  let S₀ : Finset ℕ := S ∪ Finset.univ.image pick
  refine ⟨S₀, ?_, ?_, ?_⟩
  · obtain ⟨k, hk⟩ := hSne
    exact ⟨k, Finset.mem_union_left _ hk⟩
  · intro k hk
    rcases Finset.mem_union.mp hk with hkS | hkD
    · exact hSch k hkS
    · obtain ⟨d, _, rfl⟩ := Finset.mem_image.mp hkD
      exact (hpick d).1
  · intro d hd
    by_cases hdR : d < R
    · have hdD : d ∈ D := Finset.mem_filter.mpr
        ⟨Finset.mem_range.mpr hdR, hd⟩
      let ds : {d // d ∈ D} := ⟨d, hdD⟩
      apply AddSubmonoid.subset_closure
      exact Finset.mem_coe.mpr (Finset.mem_biUnion.mpr
        ⟨pick ds,
          Finset.mem_union_right _
            (Finset.mem_image_of_mem pick (Finset.mem_univ ds)),
          (hpick ds).2⟩)
    · have hdc : d ∈ AddSubmonoid.closure ((depthSet S : Set ℕ)) :=
        hR d (by omega) (Nat.setGcd_dvd_of_mem_closure
          (AddSubmonoid.subset_closure hd))
      refine AddSubmonoid.closure_mono ?_ hdc
      intro e he
      obtain ⟨k, hkS, hek⟩ := Finset.mem_biUnion.mp (Finset.mem_coe.mp he)
      exact Finset.mem_coe.mpr (Finset.mem_biUnion.mpr
        ⟨k, Finset.mem_union_left _ hkS, hek⟩)

/-! ### Quantitative target returns -/

/-- A formal target exposes no counter larger than `N`. -/
def TgtBounded (N : ℕ) : Tgt → Prop
  | Tgt.F => True
  | Tgt.Z k => k ≤ N
  | Tgt.Fk k => k ≤ N

/-- A bounded target reaches `F` in a depth whose square is at most
`8(N+1)`. -/
lemma exists_descend_F_sq_le (S : Finset ℕ) {N : ℕ} {t : Tgt}
    (ht : TgtBounded N t) :
    ∃ d, Descend S d t Tgt.F ∧ d * d ≤ 8 * (N + 1) := by
  cases t with
  | F => exact ⟨0, Descend.refl _, by omega⟩
  | Z k =>
      obtain ⟨d, hd⟩ := toFresh_nonempty k
      refine ⟨d, descend_of_mem_toFresh k d hd _ (fun _ h => h), ?_⟩
      exact le_trans (sq_le_eight_mul_succ_of_mem_toFresh k d hd)
        (Nat.mul_le_mul_left 8 (Nat.succ_le_succ ht))
  | Fk k =>
      obtain ⟨d, hd⟩ := toFresh_nonempty k
      refine ⟨d, descend_of_mem_toFresh k d hd _ (fun _ h => h), ?_⟩
      exact le_trans (sq_le_eight_mul_succ_of_mem_toFresh k d hd)
        (Nat.mul_le_mul_left 8 (Nat.succ_le_succ ht))

/-- A bounded cell on an actual successor ray reaches `F` within the
same quadratic depth budget. -/
lemma exists_cell_F_sq_le (S : Finset ℕ) {N n : ℕ} (c : ℕ → Tgt)
    (hc : ∀ q, c (q + 1) ∈ tgtSucc S (c q))
    (ht : TgtBounded N (c n)) :
    ∃ m, c (n + m) = Tgt.F ∧ m * m ≤ 8 * (N + 1) := by
  cases hcn : c n with
  | F => exact ⟨0, by simp [hcn], by omega⟩
  | Z k =>
      have hk : k ≤ N := by simpa [hcn, TgtBounded] using ht
      have hnext := hc n
      rw [hcn] at hnext
      obtain ⟨m, hm, hF⟩ := hits_F_of_gpair hc k n hnext
      refine ⟨m, hF, ?_⟩
      exact le_trans (sq_le_eight_mul_succ_of_mem_toFresh k m hm)
        (Nat.mul_le_mul_left 8 (Nat.succ_le_succ hk))
  | Fk k =>
      have hk : k ≤ N := by simpa [hcn, TgtBounded] using ht
      have hnext := hc n
      rw [hcn] at hnext
      obtain ⟨m, hm, hF⟩ := hits_F_of_gpair hc k n hnext
      refine ⟨m, hF, ?_⟩
      exact le_trans (sq_le_eight_mul_succ_of_mem_toFresh k m hm)
        (Nat.mul_le_mul_left 8 (Nat.succ_le_succ hk))

/-- **Quantitative anchored pruning.**  If the cell ray and the seed
zero list expose no counter larger than `N`, then some screen is
self-pruned after the conductor `R`, at an index `n` satisfying
`(n-R)^2 ≤ 32(N+1)`.  This is the quantitative form of the path
argument needed to turn an exponential counter tail into Gaussian
decay in path length. -/
theorem exists_screen_prune_sq_le {S : Finset ℕ} {d₀ R N : ℕ}
    (hR : ∀ m, R ≤ m → (depthSet S).gcd id ∣ m →
      m ∈ AddSubmonoid.closure ((depthSet S : Set ℕ)))
    (sc : ℕ → GScreen)
    (hpath : ∀ n, sc (n + 1) ∈ screenSucc S (sc n))
    (hanch : Anchored S d₀ (sc 0))
    (hne : (sc 0).zlist.Nonempty)
    (hcell : ∀ n, TgtBounded N (sc n).cell)
    (hzero : ∀ t ∈ (sc 0).zlist, TgtBounded N t) :
    ∃ n, R ≤ n ∧ (sc n).cell ∈ (sc n).zlist
      ∧ (n - R) * (n - R) ≤ 32 * (N + 1) := by
  have hanchn : ∀ n, Anchored S (d₀ + n) (sc n) := by
    intro n
    induction n with
    | zero => exact hanch
    | succ n ihn => exact ihn.step (hpath n)
  have hzl := screenPath_zlist sc hpath
  have hcpath : ∀ n, (sc (n + 1)).cell ∈ tgtSucc S ((sc n).cell) :=
    fun n => screenSucc_cell (hpath n)
  obtain ⟨t₀, ht₀⟩ := hne
  obtain ⟨s, hs, hsbd⟩ := exists_descend_F_sq_le S (hzero t₀ ht₀)
  have hFs : Tgt.F ∈ (zsucc S)^[s] ((sc 0).zlist) :=
    mem_zsucc_iter_of_descend ht₀ hs
  have hds : d₀ + s ∈ AddSubmonoid.closure ((depthSet S : Set ℕ)) :=
    (hanchn 0).2 t₀ ht₀ s hs
  obtain ⟨m, hFcell, hmbd⟩ :=
    exists_cell_F_sq_le S (fun n => (sc n).cell) hcpath (hcell (s + R))
  have hdn : d₀ + (s + R + m)
      ∈ AddSubmonoid.closure ((depthSet S : Set ℕ)) := by
    have h1 := (hanchn (s + R + m)).1
    rw [hFcell] at h1
    exact h1.mem_of_F
  have hgs : (depthSet S).gcd id ∣ d₀ + s := by
    have h1 := Nat.setGcd_dvd_of_mem_closure hds
    rwa [setGcd_coe_finset] at h1
  have hgn : (depthSet S).gcd id ∣ d₀ + (s + R + m) := by
    have h1 := Nat.setGcd_dvd_of_mem_closure hdn
    rwa [setGcd_coe_finset] at h1
  have hgap : (depthSet S).gcd id ∣ R + m := by
    have h1 := Nat.dvd_sub hgn hgs
    rwa [show d₀ + (s + R + m) - (d₀ + s) = R + m from by omega] at h1
  have hclgap : R + m ∈ AddSubmonoid.closure ((depthSet S : Set ℕ)) :=
    hR (R + m) (by omega) hgap
  have hFn : Tgt.F ∈ (sc (s + R + m)).zlist := by
    rw [hzl (s + R + m),
      show s + R + m = R + m + s from by omega,
      Function.iterate_add_apply]
    exact mem_zsucc_iter_of_descend hFs (descend_closure hclgap)
  refine ⟨s + R + m, by omega, ?_, ?_⟩
  · rw [hFcell]
    exact hFn
  · have hsub : s + R + m - R = s + m := by omega
    rw [hsub]
    nlinarith

end GraphMarkovMatching
